<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<div class="block block-dashboard-info">
    <div class="block-content">
        <div class="box box-information">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Email')) ?></span>
            </strong>
            <div class="box-content">
                <p>
                    <!--<?= $block->escapeHtml($block->getEmail()) ?><br>-->
                    <?= $block->escapeHtml('haresh.patel@silvertouch.com') ?><br>
                    
<br>                </p>
            </div>
        </div>
        
           <div class="box box-information">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Password')) ?></span>
            </strong>
            <div class="box-content">
                <p>
                    <?= $block->escapeHtml($block->getPassword()) ?><br>
                </p>
            </div>
        </div>
    </div>
</div>
