<?php
	$ordersPacakge = $block->getOrderDataCollection();
	$orders = json_decode(json_encode($ordersPacakge['data']), true);
	$page = $ordersPacakge['page'];
	$total =  $ordersPacakge['total']; 
	$totalPage = ceil($total/30);
	$back_redirect = $this->getBaseUrl()."customerorder/customer/index";	
?>
	<!--- tables div -->
	
		
		<table class="orderList">
			<tr>
				<th></th>
				<th class="item-sort" sort-type='DESC' data-sort-by="DocStatus"> <span class="grid-shorting" > Status  <i class="fa b2b-grid-sort-icon fa-sort"></i></span></th>
				<th class="item-sort" sort-type='DESC' data-sort-by="DocNum"> <span class="grid-shorting" > SO Number <i class="fa b2b-grid-sort-icon fa-sort"></i></span></th>
				<th class="item-sort" sort-type='DESC' data-sort-by="NumatCardPo"> <span class="grid-shorting" > PO Number <i class="fa b2b-grid-sort-icon fa-sort"></i></span></th>
				<th class="item-sort" sort-type='DESC' data-sort-by="CreateDate"> <span class="grid-shorting" > Order Date <i class="fa b2b-grid-sort-icon fa-sort"></i> </span> </th>
				<th class="item-sort" sort-type='DESC' data-sort-by="TotalQTYUnits"> <span class="grid-shorting" > Ordered <i class="fa b2b-grid-sort-icon fa-sort"></i> </span> </th>
				<th class="item-sort" sort-type='DESC' data-sort-by="TotalOpen"> <span class="grid-shorting" > Open <i class="fa b2b-grid-sort-icon fa-sort"></i> </span> </th>
				<th class="item-sort" sort-type='DESC' data-sort-by="TotalShipped"> <span class="grid-shorting" > Shipped <i class="fa b2b-grid-sort-icon fa-sort"></i> </span></th>
				<th class="item-sort" sort-type='DESC' data-sort-by="DocTotal"> <span class="grid-shorting" > Total Order <i class="fa b2b-grid-sort-icon fa-sort"></i> </span> </th>
				<th>Action</th>
			</tr>      
			<?php
			$ordered = 0;
			$open = 0;
			$shipped = 0;
			$total_order = 0;			
			if($total > 0)
			{
				$count = $page * 30 + 1;
				foreach($orders as $order)
				{
					$ordered += $order['TotalQTYUnits'] > 0 ? $order['TotalQTYUnits'] : 0;
					$open += $order['TotalOpen'] > 0 ? $order['TotalOpen'] : 0;
					$shipped += $order['TotalShipped'] > 0 ? $order['TotalShipped'] : 0;
					$total_order += $order['DocTotal'] > 0 ? $order['DocTotal'] : 0;
					
					$id_b_e = base64_encode($order['Id']);
					if($order['dataFrom'] == 'V')
					{
						$id_b_e = base64_encode($order['DocNum']);
					}
					
					$order_view_url = $block->getBaseUrl().'customerorder/customer/orderview/id/'.$id_b_e.'/back/'.base64_encode($back_redirect).'/df/'.base64_encode($order['dataFrom']);		
					if($order['DocStatus'] == "Draft")	{
							$order_view_url = $block->getBaseUrl().'customerorder/customer/payment?back_order_id='.$id_b_e.'&back_po_number='.base64_encode($order['NumatCardPo']);
					}
				?>

					<tr option-redirect = "<?php echo $order_view_url;?>" style="cursor: pointer;">
						<td class="option-redirect"><?= $count; ?></td>
						<td class="option-redirect"><?php echo ($order['DocStatus'] == 'PartiallyShipped') ? 'Partially Shipped' : $order['DocStatus'];?></td>
						<td class="option-redirect"><?php echo ($order['DocNum'] != '') ? $order['DocNum'] : "";?></td>
						<td class="option-redirect"><?php echo ($order['NumatCardPo'] != '') ? $order['NumatCardPo'] : "-";?></td>
						<td class="option-redirect"><?php echo ($order['CreateDate'] != '') ? $order['CreateDate'] : "";?></td>
						<td class="option-redirect"><?php echo ($order['TotalQTYUnits'] > 0) ? number_format((int)$order['TotalQTYUnits']) : 0.00;?></td>
						<td class="option-redirect"><?php echo ($order['TotalOpen'] > 0) ? number_format((int)$order['TotalOpen']) : 0.00;?></td>
						<td class="option-redirect"><?php echo ($order['TotalShipped'] > 0) ? number_format((int)$order['TotalShipped']) : 0.00;?></td>
						<td class="option-redirect">$<?php echo number_format((float)$order['DocTotal'],2);?></td>
						<td>
							<?php if($order['DocStatus'] == "Draft"){ ?>
								<a class="newLinkText" href="<?php echo $this->getBaseUrl();?>customerorder/customer/neworder/id/<?php echo base64_encode($order['Id']);?>/ncp/<?php echo base64_encode($order['NumatCardPo']);?>"><span class="fa fa-pencil"></span></a>
								<a class="newLinkText" onclick="return confirm('Are you sure you want to delete this PO?');" href="<?php echo $this->getBaseUrl();?>customerorder/customer/delete/id/<?php echo base64_encode($order['Id']).'/back/'.base64_encode($back_redirect);?>/"><span class="fa fa-close"></span></a>
							<?php } ?>
						</td>
					</tr>

				<?php
				$count++;
			}?>
			<tfoot>
				<tr class="paginationRow" id="paginationId" data-id=1>
					<td colspan="10" class="testTable" rowspan="1">
						<div class="fa-pull-right d-flex">
							<div class="fa-pull-left recordTotal"> Displaying <?= $page * 30+1 ?> to <?= $count-1 ?> of <?= $total ?></div>
							<?php if($total > 30){?>
								<div class="pagination">
									<div class="dataTables_paginate paging_full_numbers" id="example_paginate">
										<?php if($page > 0){ ?>
											<a class="paginate_button first" aria-controls="example" data-dt-idx="1" tabindex="0" id="example_first"><span class="pageIcon first"></span></a>
											<a class="paginate_button previous" aria-controls="example" data-dt-idx="<?= $page  ?>" tabindex="0" id="example_previous"><span class="pageIcon previous"></span></a>	
										<?php } ?>
										<span class="cdatatableDetails">
											<input type="text" value="<?= $page +1  ?>" class="direct-serach" data-dt-idx="<?= $page +1  ?>"> / <?= $totalPage ?>
										</span>
										<?php if($page < $totalPage){ ?>
											<a class="paginate_button next" aria-controls="example" data-dt-idx="<?= $page+2 ?>" tabindex="0" id="example_next"><span class="pageIcon next"></span></a>
											<a class="paginate_button last" aria-controls="example" data-dt-idx="<?= $totalPage; ?>" tabindex="0" id="example_last"><span class="pageIcon last"></span></a>
										<?php } ?>
									</div>
								</div>
							<?php } ?>
						</div>
					</td>
				</tr>
				<tr>
					<td colspan="5" align="right">TOTAL QUANTITIES:</td>
					<td><?php echo number_format((int)$ordered);?></td>
					<td><?php echo number_format((int)$open);?></td>
					<td><?php echo number_format((int)$shipped);?></td>
					<td>$<?php echo number_format($total_order,2);?></td>
					<td></td>
				</tr>
			</tfoot>
			<?php
		}
		else
		{?>
			<tr>
				<td class="no-records" colspan="10" >No Orders Found!</td>            
			</tr>
		<?php } ?>
	</table>
