<?php
/** @var \Magestore\Bannerslider\Block\SliderItem $block */
$styleSlide = $block->getSlider()->getStyleSlide();
$slider = $block->getSlider();
$htmlId   = $block->getCarouselsliderHtmlId();
$bannerCollection = $block->getBannerCollection();
$banner_id = "#".$htmlId;

if (count($bannerCollection) > 0) :
?>
<section id="sliderSection" class="sliderSection">
	<div id="<?php echo $htmlId;?>" class="carousel slide" data-ride="carousel">
		<!-- Indicators -->
		<ul class="carousel-indicators">
			<?php
				$banner_cnt = 0;
				foreach ($bannerCollection as $banner): ?>
				<li data-target="#<?php echo $htmlId;?>" data-slide-to="<?php echo $banner_cnt;?>" <?php if ($banner_cnt == 0 ) : ?>class="active" <?php endif;?>></li>
			<?php $banner_cnt++; endforeach;?>
		</ul>
		<!-- The slideshow -->
		<div class="carousel-inner">
			<?php
				$banner_cnt = 0;
				foreach ($bannerCollection as $banner): ?>
					<div class="carousel-item <?php if ($banner_cnt == 0 ) : ?>active<?php endif;?>">
					<img src="<?php echo $block->getBannerImageUrl($banner) ?>" alt="<?php echo $banner->getImageAlt() ?>" class="w-100">
					<div class="carousel-caption">
						<h2 class="textOne"><?php echo $block->escapeHtml($slider->getTitle()); ?></h2><br/>
						<h3 class="textTwo"><?php echo $banner->getCaption(); ?></h3><br/>
						<a href="<?php echo $banner->getClickUrl() ?>" class="btn btn-primary"><?php echo __('Read More');?></a>
					</div>
				</div>
			<?php $banner_cnt++; endforeach;?>
			
		</div>
		<!-- Left and right controls -->
		<a class="carousel-control-prev" href="#<?php echo $htmlId;?>" data-slide="prev">
			<span class="carousel-control-prev-icon"></span>
		</a>
		<a class="carousel-control-next" href="#<?php echo $htmlId;?>" data-slide="next">
			<span class="carousel-control-next-icon"></span>
		</a>
	</div>
</section>
<script type="text/javascript">require([ 'jquery','jquery.bootstrap'], function($){ $("#<?php echo $htmlId;?>").carousel(); });</script>
<?php endif;?>