<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Recommended Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    default:
        $exist = null;
}

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$logourlobj = $objectManager->get('\Magento\Theme\Block\Html\Header\Logo');

$logourl =  $logourlobj->getViewFileUrl('images/logo-55.png');
?>

<?php if ($exist):?>

<div class="block <?= /* @escapeNotVerified */ $class ?>">
	<span class="logoStrip"> <img src="<?php echo $logourl;?>" alt="" title=""></span>
    <div class="block-title title">
        <strong id="block-<?= /* @escapeNotVerified */ $class ?>-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */ $title ?></strong>
    </div>
     <div class="block-content content">   
	<div class="prodSlider_related products list items product-items">
		<?php $iterator = 1; ?>
		<?php foreach ($items as $_item): ?>

		<?php $available = ''; ?>
		
		
		<div class="item product product-item">
			<?= /* @escapeNotVerified */ '<!-- ' . $image . '-->' ?>
			<a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
				<?= $block->getImage($_item, $image)->toHtml() ?>
			</a>
			<div class="product details product-item-details">
				<strong class="product name product-item-name">
					<a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>">
                            <?= $block->escapeHtml($_item->getName()) ?>
					</a>
                </strong>
				<?php $collcationValue =  $_item->getResource()->getAttribute('collecttion')->getFrontend()->getValue($_item); ?>
				<div class="show-product-dis-box">
					<?php if($collcationValue): ?>
					 <span><?php echo $collcationValue; ?> collection </span>
					 <?php endif;?>
                     <?php
                        $_children = ''; 
                        $_children = $_item->getTypeInstance()->getUsedProducts($_item);
                        $colorarr = array();                    
                        foreach ($_children as $child){
                            $colorarr[$child->getColor()] = $child->getColor();
                        }
                        if(count($colorarr) > 0) {
                            $count_color = count($colorarr); ?>
                            <span class="color-total"><?php echo  '('.$count_color. ' colors)'; ?></span>
                    <?php  } ?>
				</div>
				<div class="show-product-dis-box-more">
					<span><lable>Style No.</lable></span>
					<span><?php echo $_item->getSku();?></span>
				</div>
			</div>
		</div>
			
		<?php endforeach ?>
	</div>
</div>
	</div>
<script>
require(['functions'],function($, owlCarousel){
    (function($) {
        $(document).ready( function(){   
	if( $(".prodSlider_related").length > 0) {
        $('.prodSlider_related').owlCarousel({
             loop:true
            ,autoplay:true
            ,autoplayTimeout:5000
            ,smartSpeed:2200
            ,margin:70
            ,nav:false
            ,dots:false
			//,itemElement: 'owl-item'
			, items : 4
            ,responsive:{
                0:{
                    items:1
                },
                640:{
                    items:2
                },
				1024:{
                    items:3
				},
				1270:{
                    items:4
					}
            }
            
        });
    }	
});
    })(jQuery);
});
</script>
<?php endif;?>

