<div class="footerLogo"><a href="<?= $block->getUrl('') ?>"><img src="<?php echo $block->getViewFileUrl('images/footer-logo.png'); ?>" alt="" /></a>
	<div class="socialIcons">
		<a href="<?php echo $block->getFacebookUrl();?>" target="_blank"><span class="fa fa-facebook"></span></a>
		<a href="<?php echo $block->getLinkdinUrl();?>" target="_blank"><span class="fa fa-instagram"></span></a> 
		<a href="<?php echo $block->getTwitterUrl();?>" target="_blank"><span class="fa fa-twitter"></span></a> 
		<a href="<?php echo $block->getGooglePlusUrl();?>" target="_blank"><span class="fa fa-youtube-play"></span></a>
	</div>
</div>