<?php
	/**
		* Copyright © Magento, Inc. All rights reserved.
		* See COPYING.txt for license details.
	*/
	
	// @codingStandardsIgnoreFile
	
	/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */


$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl();
?>
<div class="cf sidebarSearch">
	<form class="form po_search col-lg-12"
					  action="<?php echo $baseUrl.'customerorder/customer/index';?>"
					  id="po_search"
					  method="get"
					  data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
					  data-mage-init='{"validation":{}}'>
		<span class="searchLable">Search an existing order</span>
		<div class="searchInput">
			<input type="text" name="po_number" placeholder="P.O. Number or Order Number" data-validate="{required:true}" >
		</div>
		<button type="submit" class="themeBtn action save" title="Search"><span>Search</span></button>
	</form>
</div>