<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $base_url = $storeManager->getStore()->getBaseUrl();
?>
<div class="col-lg-12">
<div class="sliderTitle contPagelogo"><span class="logoStrip"><img src="<?php echo $base_url;?>pub/media/wysiwyg/logo-55_1.png" alt=""></span></div>
</div>
<div class="offset-md-2 col-md-8 contAddress  text-center">
	<div class="offset-md-3 col-md-6">
	<h2><?php echo $block->getStoreName();?></h2>
	<p><?php echo $block->getStreetAddress().' '.$block->getStreetAddressLineOne();?> </br>
	<?php echo $block->getCity().', '.$block->getRegionName().' '.$block->getPostCode();?></p>
	<div><strong><?= $block->escapeHtml(__('P')) ?> | </strong><a href="tel:<?php echo $block->getStorePhoneNumber();?>"><?php echo $block->getStorePhoneNumber();?></a></div>
	<div><strong><?= $block->escapeHtml(__('Toll Free')) ?> | </strong><a href="tel:<?php echo $block->getStoreTollFreeNo();?>"><?php echo $block->getStoreTollFreeNo();?></a></div>
	<div><strong><?= $block->escapeHtml(__('F')) ?> | </strong><?php echo $block->getStoreFaxNo();?></div>
	<div><strong><?= $block->escapeHtml(__('E')) ?> | </strong><a href="mailto:<?php echo $block->getStoreEmail();?>"><?php echo $block->getStoreEmail();?></a></div>
	</div>
</div>