<div class="accountPageContainer">
<h1 class="page-title">Purchase Order Drafts <a href="" class="themeBtn alignRight">Place a New Order</a></h1>
<strong>Select an order to continue editing.</strong>

<br/><br/>
<div class="orderTable">
	<table class="orderList">
		<tr>
        	<th></th>
			<th></th>
            <th>Status</th>
            <th>SO Number</th>
            <th>PO Number</th>
            <th>Order Date</th>
            <th>Ordered</th>
            <th>Open</th>
            <th>Pack</th>
            <th>Shipped</th>
            <th>Total Order</th>
			<th>Open Amount</th>
        </tr>
        <tr>
        	<td><input type="checkbox" /></td>
			<td>1</td>
            <td>Open</td>
            <td></td>
            <td>163622</td>
            <td> 27 Nov 2017</td>
            <td>100</td>
            <td>160</td>
            <td>0</td>
            <td>0</td>
            <td>$975.00</td>
            <td>$975.00</td>            
        </tr>
        <tr>
        	<td><input type="checkbox" /></td>
			<td>2</td>
            <td>Pending</td>
            <td></td>
            <td>1355466</td>
            <td> 26 Nov 2017</td>
            <td>30</td>
            <td>30</td>
            <td>0</td>
            <td>0</td>
            <td>$177.66</td>
            <td>$177.66</td>            
        </tr>
        <tr>
        	<td><input type="checkbox" /></td>
			<td>3</td>
            <td>Pending</td>
            <td></td>
            <td>1355466</td>
            <td> 26 Nov 2017</td>
            <td>100</td>
            <td>100</td>
            <td>0</td>
            <td>0</td>
            <td>$975.00</td>
            <td>$975.00</td>            
        </tr>
        <tr>
        	<td><input type="checkbox" /></td>
			<td>4</td>
            <td>Pending</td>
            <td></td>
            <td>1355466</td>
            <td> 26 Nov 2017</td>
            <td>200</td>
            <td>200</td>
            <td>0</td>
            <td>0</td>
            <td>$2,900.00</td>
            <td>$2,900.00</td>            
        </tr>
        
	</table>
	
</div>


</div>