<div class="container">
	<div class="row">
		<form class="form groups col-lg-12"
			  action="<?php echo $this->getUrl().'inquiries/groups/index'?>"
			  id="groups-form"
			  method="post"
			  data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
			  data-mage-init='{"validation":{}}'>
			  
			  <div class="col-md-12 groupBusiness mb-5">	
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('group_page')->toHtml();?>
				</div>
				
				<div class="offset-md-3 col-md-6">
					<div class="input-group">
						<label><?= $block->escapeHtml(__('Name')) ?><span class="reqField">*</span></label>
						<input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Sttl\Inquiries\Helper\Data')->getPostValue('name') ?: $this->helper('Sttl\Inquiries\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
					</div>
					<div class="input-group">
						<label><?= $block->escapeHtml(__('Email')) ?><span class="reqField">*</span></label>
						<input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Sttl\Inquiries\Helper\Data')->getPostValue('email') ?: $this->helper('Sttl\Inquiries\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
					</div>
					<div class="input-group">
						<label><?= $block->escapeHtml(__('Message')) ?></label>
						<textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('Message')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper('Sttl\Inquiries\Helper\Data')->getPostValue('comment')) ?></textarea>
					</div>
					<?= $block->getChildHtml('form.additional.info') ?>
					<div class="clearfix">
						<input type="hidden" name="hideit" id="hideit" value="" />
						<input type="submit" class="btn-primary float-right" value="<?= $block->escapeHtml(__('SEND')) ?>" />
					</div>

				</div>
		</form>
	</div>
</div>
<!--<script type="text/javascript">
    require(["jquery"],function($) {
        $(document).ready(function() {
            var customurl = "<?php echo $this->getUrl().'sttl_inquiries/groups/index'?>";
            $.ajax({
                url: customurl,
                type: 'POST',
                dataType: 'json',
                data: {
                    customdata1: 'test1',
                    customdata2: 'test2',
                },
            complete: function(response) {             
                country = response.responseJSON.default_country;
                state = response.responseJSON.state;         
                console.log(state+' '+country);   
                },
                error: function (xhr, status, errorThrown) {
                    console.log('Error happens. Try again.');
                }
            });
        });
    });
</script> -->