<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
 
$curren_url =  $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
$base_url = $block->getBaseUrl();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();

?>
<style>
    #signUpModal .modal-content .messages {
        display: none;
    }
    
</style>
	<div class="copyRight">
      <div class="container"><?= /* @escapeNotVerified */ $block->getCopyright() ?>
        <ul class="bottomLinks">
          <?php echo $this->getLayout()
			->createBlock('Magento\Cms\Block\Block')
			->setBlockId('copyright_link')
			->toHtml(); ?>
        </ul>
      </div>
    </div>
	
  <!-- Coming Soon popup -->

<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $base_url = $storeManager->getStore()->getBaseUrl();

?>
<style>
    #loginModal .modal-content .messages {
        display: none;
    }
    
</style>
<div class="modal fade block block-customer-login comingSoon" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">
      <div class="modalContainer block-content" aria-labelledby="block-customer-login-heading">
      <div class="messages">
            <div class="message message-error error">
                <div></div>
            </div>
          </div>
        <div class="quickViewCont">        
      <div class="container bg-primary p-2">
      
        <div class="row">
          <div class="col-md-4 offset-md-4 text-center">
            <a href="#" title="" class="mobileLogo" style="display:inline;"  height="37" width="37"><img height="37" width="37" src="<?php echo $this->getViewFileUrl('images/mobile-logo-white.png'); ?>"></a>
          </div>
          <div class="col-md-4">
            <button type="button" data-dismiss="modal" class="close mfp-close-inside"><i class="fa fa-times"></i></button>
          </div>
        </div>
      </div>
      <div class="comingSoonTxt center" id="comingSoonForm">
        <h3>Coming Soon!</h3>
		<p>Our online Customer Portal will be available soon.
        Sign up below to stay updated!</p>
          <form novalidate id="coming-validate-detail" action="<?php echo $base_url; ?>newsletter/subscriber/new/" method="post" data-mage-init='{"validation": {"errorClass": "mage-error"}}' >
		  <span class="news-coming-show-message subscribeNote"></span>
            <div class="comingSoonForm left" >
			
              <label>Email</label>
              <input  name="email" id="comingemail" type="email"
                  data-validate="{required:true, 'validate-email':true}"/>
              <input type="hidden" name="submitby" value="Customer Portal">
              <div class="center">
               <button class="themeBtn" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" >
                  <span><?= $block->escapeHtml(__('Submit')) ?></span>
                  </button>
              </div>
        </div>
        </form>
		
      </div>
    </div>   
    
    </div>
</div>
</div>
</div>
</div>
<!--<script type="text/x-magento-init">
    {
        "#loginModal": {
            "Sttl_Adaruniforms/js/process-popup-login": {
                "popupTitle": "<?php /* @escapeNotVerified */ echo __('Newsletter'); ?>"
            }
        }
    }
</script>-->
<script type="text/javascript">
    require(["jquery"],function($) {
        $(document).ready(function() {
            var self = this,
                message_show = $('.news-coming-show-message'),
                form = $('#coming-validate-detail');
            form.submit(function (e) {
                if (form.validation('isValid')) {
                    var email = $("#comingemail").val();
                    var url = form.attr('action');
                    e.preventDefault();
                    $.ajax({
                        url: url,
                        dataType: 'json',
                        type: 'POST',
                        showLoader: true,
                        data: {email: email}
                    }).done(function (data) {
                        message_show.html(data.msg);
                        if (data.error) {
                            message_show.addClass('message-error error');
                            message_show.removeClass('message-success');
                            message_show.show();
                        } else {
                            $("#comingemail").val('');
                            message_show.removeClass('message-error error');
                            message_show.addClass('message-success');
                            $('#comingSoonForm').html('<h3>THANK YOU</h3><p>Thank you for signing up! Check your inbox soon for special offers, our latest innovation and products, and more!</p><div class="inputArea"><button class="signupBtn newsclosebtn" title="Close" data-dismiss="modal" type="submit"> <span>Close</span> </button></div>');
                        }
                        /**setTimeout(function() {
                            message_show.hide();
                        }, 5000);**/
                    });
                }
            });

        });
    });
</script>
	
<!--<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <div class="modalContainer">
                <div class="cf">
                    <span class="close" data-dismiss="modal" aria-label="Close">
                      <span class="fa fa-close"></span>
                    </span>
                </div>
				<h3>Welcome Back</h3>
                <div class="inputArea">
                	<label>Customer Code</label>
                    <input type="text" class="textInput" placeholder="CUSTOMER CODE"/>
                </div>
                <div class="inputArea">
                	<label>Password</label>
                	<input type="password" class="textInput" placeholder="PASSWORD"/>
              	</div>
                <div class="btnRow">
                    <input type="button" class="signupBtn" value="Submit" />
                    <span class="note">Don't have an account? Contact us <a href="<?= $block->getUrl('') ?>contact">here</a> to set one up now!</span>
                </div>
        </div>
      </div>
      
    </div>
  </div>
</div>-->

<?php /*if($request->getFullActionName() == 'cms_index_index') {  

?>

  <div class="modal fade" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="signUpModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <div class="messages">
            <div class="message message-error error">
                <div></div>
            </div>
          </div>
          <div class="modalContainer">
            <div class="leftSection">&nbsp;</div>
              <div class="rightSection">
              <div id="signupBtn-contchnage">
                <h3>Sign up</h3>
                <p>Be the first to know about new release, promotions and exclusive offers on our upcoming Collections.</p>
                <div class="inputArea">
                  <form novalidate action="<?php echo $base_url; ?>adaruniforms/subscriber/new/" method="post" data-mage-init='{"validation": {"errorClass": "mage-error"}}' >
                  <input class="signupEmail" name="email" type="email"
                  placeholder="EMAIL ADDRESS"
                  data-validate="{required:true, 'validate-email':true}"/>
                  <button class="signupBtn" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" >
                  <span><?= $block->escapeHtml(__('Submit')) ?></span>
                  </button>

                  </form>
                </div>
              </div>
              </div>
          </div>
        </div>

      </div>
    </div>
  </div>
<script type="text/x-magento-init">
    {
        "#signUpModal": {
            "Magento_Theme/js/process-popup-newsletter": {
                "popupTitle": "<?php echo __('Newsletter'); ?>"
            }
        }
    }
</script>
<script type ="text/javascript">
    require(["jquery","jquery.bootstrap" ,"mage/cookies"], function ($,jquery) {
        function setCookie(name, value, days)
        {
            if (days) {
                var date = new Date();
                date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
                var expires = "; expires=" + date.toGMTString();
                console.log(expires);
            } else
                var expires = "";
              document.cookie = name + "=" + value + expires + "; path=/";
        }
        function getCookie(name)
        {
            var nameEQ = name + "=";
            var ca = document.cookie.split(';');
            for (var i = 0; i < ca.length; i++) {
                var c = ca[i];
                while (c.charAt(0) == ' ')
                    c = c.substring(1, c.length);
                if (c.indexOf(nameEQ) == 0)
                    return c.substring(nameEQ.length, c.length);
            }
            return null;
        }
        $(document).ready( function(){
            if (!$.mage.cookies.get("signUpModal")) {
               if(jQuery("#signUpModal").length) {
                  $('#signUpModal').modal();
                  $.mage.cookies.set('signUpModal', 'true');
                }
            }else{
              $('body').removeClass('modal-open');
              $('.modal-backdrop').remove();

            }
          });
      
    });
</script>
<?php }*/ ?>

	
	

