<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
$request = $objectManager->get('\Magento\Framework\App\Request\Http');
$cur_action = $request->getFullActionName();

$baseurl = $this->getBaseUrl();
$customerorderUrl = $baseurl."customerorder/customer/index";
$newOrderUr = $baseurl."customerorder/customer/neworder";
$dashboardurl = $baseurl."dashboard/index/index";

$helpersearch = $this->helper(\Magento\Search\Helper\Data::class);
?>

<?php if($customerSession->isLoggedIn()){ ?>
<div class="block mobile-block-collapsible-nav">
 <div class="content mobile-content autoScrollMenu" id="<?= /* @escapeNotVerified */ $block->getBlockCss() ?>">
   <ul class="footer-menu-bottom" >
    <li class="nav item  <?php if ($cur_action == "dashboard_index_index") {?>current<?php }?>" id="dashboard-page">
        <a href="<?php echo $dashboardurl;?>">
          <svg aria-hidden="true" height="26" width="26" focusable="false" data-prefix="fas" data-icon="chart-pie" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 544 512" class="svg-inline--fa fa-chart-pie fa-w-17"><path fill="currentColor" d="M527.79 288H290.5l158.03 158.03c6.04 6.04 15.98 6.53 22.19.68 38.7-36.46 65.32-85.61 73.13-140.86 1.34-9.46-6.51-17.85-16.06-17.85zm-15.83-64.8C503.72 103.74 408.26 8.28 288.8.04 279.68-.59 272 7.1 272 16.24V240h223.77c9.14 0 16.82-7.68 16.19-16.8zM224 288V50.71c0-9.55-8.39-17.4-17.84-16.06C86.99 51.49-4.1 155.6.14 280.37 4.5 408.51 114.83 513.59 243.03 511.98c50.4-.63 96.97-16.87 135.26-44.03 7.9-5.6 8.42-17.23 1.57-24.08L224 288z" class="" style="fill: #9eacb7; "></path></svg>
        <p>Dashboard</p>
      </a>
    </li>
    <li class="nav item" id="search_product_button">
        <a>
          <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"viewBox="0 0 512.005 512.005" style="enable-background:new 0 0 512.005 512.005;" xml:space="preserve">
            <g>
              <g>
                <path d="M505.749,475.587l-145.6-145.6c28.203-34.837,45.184-79.104,45.184-127.317c0-111.744-90.923-202.667-202.667-202.667 S0,90.925,0,202.669s90.923,202.667,202.667,202.667c48.213,0,92.48-16.981,127.317-45.184l145.6,145.6 c4.16,4.16,9.621,6.251,15.083,6.251s10.923-2.091,15.083-6.251C514.091,497.411,514.091,483.928,505.749,475.587z M202.667,362.669c-88.235,0-160-71.765-160-160s71.765-160,160-160s160,71.765,160,160S290.901,362.669,202.667,362.669z"/>
              </g> 
            </g> 
          </svg>
          <p>Search</p>
        </a>
      </li>
      <li class="nav item  <?php if ($cur_action == "customerorder_customer_index" && $block->getRequest()->getParam('q') == '') {?>current<?php }?>" id="order-page">
          <a href="<?php echo $customerorderUrl ;?>">
              <svg version="1.0" xmlns="http://www.w3.org/2000/svg"
               width="64.000000pt" height="64.000000pt" viewBox="0 0 64.000000 64.000000"
               preserveAspectRatio="xMidYMid meet">
              <metadata>
              Created by potrace 1.10, written by Peter Selinger 2001-2011
              </metadata>
              <g transform="translate(0.000000,64.000000) scale(0.100000,-0.100000)"
               stroke="none">
              <path d="M126 569 l-26 -20 0 -229 0 -229 26 -20 c25 -19 40 -21 194 -21 154
              0 169 2 194 21 l26 20 0 229 0 229 -26 20 c-25 19 -40 21 -194 21 -154 0 -169
              -2 -194 -21z m369 -249 l0 -225 -175 0 -175 0 -3 215 c-1 118 0 220 3 227 3
              11 43 13 177 11 l173 -3 0 -225z"/>
              <path d="M185 469 c-15 -23 16 -30 136 -27 102 3 124 6 124 18 0 12 -22 15
              -127 18 -85 2 -129 -1 -133 -9z"/>
              <path d="M185 390 c-3 -5 0 -13 7 -15 25 -10 253 -1 251 10 -4 14 -249 19
              -258 5z"/>
              <path d="M185 320 c-13 -21 8 -30 71 -30 57 0 64 2 64 20 0 18 -7 20 -64 20
              -36 0 -68 -4 -71 -10z"/>
              <path d="M390 160 c0 -11 7 -20 15 -20 8 0 15 9 15 20 0 11 -7 20 -15 20 -8 0
              -15 -9 -15 -20z"/>
              </g>
              </svg>
          <p>Orders</p>
        </a>
      </li>
      <li class="nav item  new-order <?php if ($cur_action == "customerorder_customer_neworder") {?>current<?php }?>">
            <a href="<?= $newOrderUr; ?>" id="neworder-page">
             <svg version="1.0" xmlns="http://www.w3.org/2000/svg"
                 width="64.000000pt" height="64.000000pt" viewBox="0 0 64.000000 64.000000"
                 preserveAspectRatio="xMidYMid meet">
                <metadata>
                Created by potrace 1.10, written by Peter Selinger 2001-2011
                </metadata>
                <g transform="translate(0.000000,64.000000) scale(0.100000,-0.100000)"
                 stroke="none">
                <path d="M126 569 l-26 -20 0 -229 0 -229 26 -20 c23 -18 41 -21 121 -21 82 0
                98 -3 124 -23 42 -30 135 -31 176 -1 97 72 98 195 1 267 -16 12 -48 22 -80 25
                -44 3 -59 0 -88 -20 -75 -51 -101 -136 -65 -211 11 -22 12 -27 2 -15 -10 13
                -33 18 -93 20 l-79 3 0 225 0 225 175 0 175 0 3 -111 c2 -102 4 -112 22 -117
                19 -5 20 0 20 113 0 116 -1 119 -26 139 -25 19 -40 21 -194 21 -154 0 -169 -2
                -194 -21z m413 -296 c85 -63 75 -186 -20 -236 -92 -49 -208 33 -195 137 12
                104 133 159 215 99z"/>
                <path d="M450 200 c0 -27 -3 -30 -30 -30 -16 0 -30 -4 -30 -10 0 -5 14 -10 30
                -10 27 0 30 -3 30 -30 0 -16 5 -30 10 -30 6 0 10 14 10 30 0 27 3 30 30 30 17
                0 30 5 30 10 0 6 -13 10 -30 10 -27 0 -30 3 -30 30 0 17 -4 30 -10 30 -5 0
                -10 -13 -10 -30z"/>
                <path d="M185 469 c-15 -23 16 -30 136 -27 102 3 124 6 124 18 0 12 -22 15
                -127 18 -85 2 -129 -1 -133 -9z"/>
                <path d="M185 390 c-3 -5 0 -13 7 -15 25 -10 253 -1 251 10 -4 14 -249 19
                -258 5z"/>
                <path d="M185 320 c-13 -21 8 -30 71 -30 57 0 64 2 64 20 0 18 -7 20 -64 20
                -36 0 -68 -4 -71 -10z"/>
                </g>
                </svg>
            <p>New Order</p>
          </a>
        </li>
        <li class="nav item  <?php if ($cur_action == "customerorder_customer_index" && $block->getRequest()->getParam('q') == 'd') {?>current<?php }?>" id="draft-page">
            <a href="<?php echo $customerorderUrl ;?>?q=d">
              <svg version="1.0" xmlns="http://www.w3.org/2000/svg"
               width="64.000000pt" height="64.000000pt" viewBox="0 0 64.000000 64.000000"
               preserveAspectRatio="xMidYMid meet">
              <metadata>
              Created by potrace 1.10, written by Peter Selinger 2001-2011
              </metadata>
              <g transform="translate(0.000000,64.000000) scale(0.100000,-0.100000)"
              stroke="none">
              <path d="M126 569 l-26 -20 0 -229 0 -229 26 -20 c23 -18 41 -21 121 -21 82 0
              98 -3 124 -23 42 -30 135 -31 176 -1 97 72 98 195 1 267 -16 12 -48 22 -80 25
              -44 3 -59 0 -88 -20 -75 -51 -101 -136 -65 -211 11 -22 12 -27 2 -15 -10 13
              -33 18 -93 20 l-79 3 0 225 0 225 175 0 175 0 3 -111 c2 -102 4 -112 22 -117
              19 -5 20 0 20 113 0 116 -1 119 -26 139 -25 19 -40 21 -194 21 -154 0 -169 -2
              -194 -21z m413 -296 c85 -63 75 -186 -20 -236 -92 -49 -208 33 -195 137 12
              104 133 159 215 99z"/>
              <path d="M481 247 c-8 -11 -5 -16 13 -25 27 -12 48 1 39 24 -7 18 -37 18 -52
              1z"/>
              <path d="M425 168 c-38 -58 -54 -108 -34 -108 15 0 79 67 102 108 31 54 5 34
              -42 -31 -54 -75 -68 -59 -16 19 20 30 35 58 32 61 -3 3 -22 -20 -42 -49z"/>
              <path d="M185 469 c-15 -23 16 -30 136 -27 102 3 124 6 124 18 0 12 -22 15
              -127 18 -85 2 -129 -1 -133 -9z"/>
              <path d="M185 390 c-3 -5 0 -13 7 -15 25 -10 253 -1 251 10 -4 14 -249 19
              -258 5z"/>
              <path d="M185 320 c-13 -21 8 -30 71 -30 57 0 64 2 64 20 0 18 -7 20 -64 20
              -36 0 -68 -4 -71 -10z"/>
              </g>
              </svg>
            <p>Drafts </p>
          </a>
        </li>
      </ul>
    </div>
  </div>
  <div class="search-product" style="display: none">
    <div class="cf sidebarSearch" >
      <form  class="form minisearch" data-mage-init='{"validation": {}}' id="search_mini_form" action="<?= /* @escapeNotVerified */ $helpersearch->getResultUrl() ?>" method="get" 	>
        <div class="searchInput required">
          <div class="control">
            <input data-mage-init='{"quickSearch":{"formSelector":"#search_mini_form", "url":"<?= /* @escapeNotVerified */ $helpersearch->getSuggestUrl()?>", "destinationSelector":"#search_autocomplete"} }'type="text"name="<?= /* @escapeNotVerified */ $helpersearch->getQueryParamName() ?>"value=""id = "autosearch"class="input-text required-entry"maxlength="<?= /* @escapeNotVerified */ $helpersearch->getMaxQueryLength() ?>"role="combobox"aria-haspopup="false"aria-autocomplete="both"placeholder="Search Style/Color"autocomplete="off"oninvalid="this.setCustomValidity('please Enter somthing in search box.')"onvalid="this.setCustomValidity('')"/> 
          </div>
          <button type="submit"title="<?= $block->escapeHtml(__('Search')) ?>"class="search"> 
            <span class="fa fa-search"></span>
          </button>
        </div>
      </form>
    </div>
    <div class="search-loader" style="display: none;">
        <div class="loader">
            <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
                 alt="<?= /* @escapeNotVerified */ __('Loading...') ?>">
        </div>
    </div>
  </div>
<?php } ?>
