<div class="col-sm-6">
<h3>Contact Us</h3>
<ul class="contactList">
<li class="location"><strong>Adar Medical Uniforms LLC</strong><br />
	<?php echo $block->getStreetAddress().' '.$block->getStreetAddressLineOne();?><br />
	<?php echo $block->getCity().', '.$block->getRegionName().' '.$block->getPostCode();?>
</li>
<li class="mail"><a href="mailto:<?php echo $block->getStoreEmail();?>"><?php echo $block->getStoreEmail();?></a></li>
<li class="callto"><a href="tel:1.<?php echo $block->getStoreTollFreeNo();?>">1.<?php echo $block->getStoreTollFreeNo();?></a></li>
</ul>
</div>