<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<span class="action nav-toggle"><span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span></span>
	<?php 
	if ($block->isHomePage()) {
		?><style>
		.innerPageContent{ display:none; }
		</style><?php 
	}
	?>
    <h1 class="logo">
		<a class="logoDesktop" href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
		 <img src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
				 alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
				 <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
				 <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
			/>
		</a>
		<a href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>" class="mobileLogo"> <img src="<?php echo $block->getViewFileUrl('images/mobile-logo.png'); ?>" alt="Adar Logo" title="Adar Logo" /> </a> 
	</h1>









	




