<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= /* @escapeNotVerified */ __('Sort By') ?><span id="sortshopByClose" class="shopByClose"></span></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
            <option value="<?= /* @escapeNotVerified */ $_key ?>"
                <?php if ($block->isOrderCurrent($_key)): ?>
                    selected="selected"
                <?php endif; ?>
                >
                <?php $title = ($_key == "filter_category") ? __("Category") :  $_order; ?>
                <?= $block->escapeHtml(__($title)) ?>
            </option>
        <?php endforeach; ?>
    </select>

    <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
        <a href="<?php echo $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true])."?&product_list_order=".$_key ?>"
            <?php $selected = "";
            if ($block->isOrderCurrent($_key)):
                $selected = "selected"; 
            endif; ?>
            class="sorterList mobile-sort-custom <?php echo $selected; ?>">
            <?php $title = ($_key == "filter_category") ? __("Category") :  $_order; ?>
                <?= $block->escapeHtml(__($title)) ?>
        </a>
    <?php endforeach; ?>
    <?php

    ?>
    <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <a title="<?= /* @escapeNotVerified */ __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
            <span><?= /* @escapeNotVerified */ __('Set Ascending Direction') ?></span>
        </a>
    <?php else: ?>
        <a title="<?= /* @escapeNotVerified */ __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
            <span><?= /* @escapeNotVerified */ __('Set Descending Direction') ?></span>
        </a>
    <?php endif; ?>
</div>
<script>
require(['functions','jquery.bootstrap'], function ($,jquery)
{
        'use strict';
        jQuery.noConflict();
        jQuery(document).ready( function(){
            jQuery("#sortshopByClose").click(function () {
                jQuery('.toolbar-sorter.sorter').hide();
                jQuery('body').removeClass('mobile-sortby-body');
            });
        });
            
});
</script>
<style type="text/css">

  .toolbar-sorter.sorter span.customSelect.sorter-options {
    line-height: 2;
    border: 1px solid black;
    border-radius: 2px;
    text-align: left;
    padding: 0 10px;
  }
  .toolbar-sorter.sorter span.customSelect.sorter-options:after {
    float: right;
    padding-top: 2px;
  }
    .toolbar.toolbar-products .toolbar-sorter.sorter label.sorter-label {
        display: inline-block !important;
    }
</style>
