<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create("Magento\Customer\Model\Session");
$_product = $block->getProduct();
$sku = $_product->getSku();
$brands_product_urls = $objectManager->get('Sttl\Importproductbrand\Model\Importproductbrand')
								->getCollection()
								->addFieldToFilter('brand_id', '1')
								->addFieldToFilter('sku', array('eq' => $_product->getSku()));
$brand_product_url = $brands_product_urls->getData();		

$helper = $this->helper('Sttl\Adaruniforms\Helper\Sap');
$values = $helper->getJsAllInventoryItems();
$filterBy = $sku;
$product_array = array_filter($values, function ($var) use ($filterBy) {
		return ($var['Style'] == $filterBy);
});
?>
<div class="container p-2 buyBtns" id="buyBtns">
	
		<?php if (!$customerSession->isLoggedIn()) { ?>
		<div class="buyBtnContainer">
			<div class="loginSection"><a href="<?php echo $block->getBaseUrl();?>storelocator"><?php echo __("BUY IN STORE");?></a></div>
		</div>
		<div class="buyBtnContainer">
			<div class="loginSection">
				<?php 
					if(count($brand_product_url) == 1 ){ ?>
						<a class="buyNow" target="_blank" href="<?= $brand_product_url[0]['brand_url'] ?>" ><?php echo __("BUY NOW");?></a>
				<?php }else{ ?>
						<a class="buyNow"  href="javascript:void(0);" id='disable' ><?php echo __("BUY NOW");?></a>	
					<?php } ?>
				</div>
		</div>
		<?php } else { ?>
	<div class="buyBtnContainer">
		<?php if(sizeof($product_array) == 0){ ?>
			<div class="loginSection">
				<span class="notavailable-product-detailpage"><?php echo __("NOT AVAILABLE");?>
				</span>
			</div>
		<?}else{ ?>
			<div class="loginSection">
				<a href="javascript:" id="<?php echo $sku; ?>" class="buyNowBtnMain" data-toggle="modal" data-target="#popupModal" style="pointer-events:none;opacity:0.5"><?php echo __("VIEW STOCK & PRICING");?>
					<span class="productinebuynow" id="productbuynow" style="display:;">
					<span id="productviewloding" class="loadShipping">
						<span class="loadDots">
							<span></span>
							<span></span>
							<span></span>
						</span>
					</span>
					</span>
				</a>
			</div>		
		<? } ?>
				
		</div>
		<?php } ?>
	
</div>
