<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getFrontendLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>

<?php if ($_attributeValue): ?>
    <div class="product attribute <?php /* @escapeNotVerified */ echo $_className?>">
        <?php if ($_attributeLabel != 'none'): ?><strong class="type"><?php /* @escapeNotVerified */ echo $_attributeLabel?></strong><?php endif; ?>

        <?php if(!is_array($_attributeValue)): ?>
		<div class="fabriccontent-subdiv">
            <div class="value" <?php /* @escapeNotVerified */ echo $_attributeAddAttribute;?>><?php /* @escapeNotVerified */ echo $_attributeValue; ?></div>
        </div>
        <div class="fabriccontent-value model-wears"><?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getModelWears(), 'model_wears') ?>
        </div>
        <?php else: ?>
		<div class="fabriccontent-subdiv">
            <?php foreach ($_attributeValue as $value): ?>
                <div class="value" <?php /* @escapeNotVerified */ echo $_attributeAddAttribute;?>><?php /* @escapeNotVerified */ echo $value; ?></div>
            <?php endforeach; ?>
            </div>
		<div class="fabriccontent-value model-wears"><?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getModelWears(), 'model_wears') ?></div>
        <?php endif; ?>
    </div>
<?php endif; ?>