<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$parent_style = $block->getParentStyle();
$this->product = $objectManager->get('\Magento\Catalog\Model\Product');
$getProductId = $this->product->getIdBySku($parent_style);
$product = $this->product->load($getProductId);
$CustomerData = $block->getCustomerData();
$CustomerData = $CustomerData[0];
$setSapdata = $block->getSapdata();
// echo "<pre>";
// print_r($CustomerData);
$_scopeConfig = $objectManager->create('Magento\Store\Model\StoreManager');
$mediaUrl = $_scopeConfig->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$placeholder_image = $mediaUrl.'catalog/product/placeholder/default/image_neworder.jpg';
if ($customerSession->isLoggedIn()): ?>
<?php $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
    $parent_style = $product->getSku();
    $collcationValue = $product->getResource()->getAttribute('collecttion')->getFrontend()->getValue($product);
    $style_status = "";
    //$parent_color_data = $block->getColorData($parent_style);
    $parent_color_data = $block->getParentColorData();
    if (isset($parent_color_data) && isset($parent_color_data['errors'])) { ?>  

    <div class="modal fade" id="popupModal" tabindex="-1" data-keyboard="false" data-backdrop="static" role="dialog" aria-labelledby="loginModal" aria-hidden="true" style="z-index: 1400;">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-body">
                <form class="form cart col-lg-12" action="<?php echo $this->getUrl() . 'adaruniforms/cart/add' ?>" id="cart-form" method="post" data-hasrequired="<?=$block->escapeHtmlAttr(__('* Required Fields')) ?>"data-mage-init='{"validation":{}}'>
                    <div class="modalContainer">
                        <div class="container bg-primary p-2">
                            <div class="row">
                                <div class="col-sm-4 col-md-4 place-an-order-back-button">
                                    <span  data-dismiss="modal" aria-label="Close">
                                </div>
                                <div class="col-sm-4 col-md-4 text-center place-an-order-text">
                                    <?php echo __("Place an Order"); ?>
                                </div>
                                <div class="col-sm-4 col-md-4" style="cursor:pointer;" data-dismiss="modal">
                                    <button type="button" class="productview-modal-close-inside"><i class="fa fa-times"></i></button>
                                </div>
                            </div>
                        </div>
                        <div class="container bg-light p-2">
                            <h4 class="col-md-12"><?php echo $parent_color_data['message']; ?></h4>
                        </div>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
    <?php
    } else {

        if (count($parent_color_data > 0)) {
            $style_status = $parent_color_data[$parent_style][0]['StyleStatus'];
        }
        //echo "<pre>";print_R($parent_color_data);exit;
        
?>
<?php
        $petiteSku = '';
        $tailSku = '';
        $regularSku = '';
        $currentsku = $parent_style;
        $check = substr($currentsku, -1);
        if (strtoupper($check) == strtoupper(trim('P')) || strtoupper($check) == strtoupper(trim('T'))) {
            $regularSku = substr($currentsku, 0, -1);
        } else {
            $regularSku = $parent_style;
        }
        if ($tailSku == '' && $petiteSku == '') {
            $tailSku = $regularSku . 'T';
            $petiteSku = $regularSku . 'P';
        }
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $petiteUrl = '';        
        if ($petiteSku !== '' && !in_array($petiteSku, $setSapdata)) {
            
            $petiteSku = '';
        }
        $tailUrl = '';
        if ($tailSku !== '' && !in_array($tailSku, $setSapdata) ) {
            $tailSku = '';
        }
        $regularUrl = '';
        if ($regularSku !== '' && $tailSku == '' && $petiteSku == '' ) {
            $regularUrl = '';            
        }
?>
<div id="posuccess-message" style="display: none;" >
  <p>Opertaion Successfully complated..</p>
</div>
<div class="modal fade" id="popupModal" tabindex="-1" data-keyboard="false" data-backdrop="static" role="dialog" aria-labelledby="loginModal" aria-hidden="true" style="z-index: 1400;">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <form class="form cart col-lg-12" action="<?php echo $this->getUrl() . 'adaruniforms/cart/add' ?>" id="cart-form" method="post" data-hasrequired="<?=$block->escapeHtmlAttr(__('* Required Fields')) ?>"data-mage-init='{"validation":{}}'>
                    <div class="modalContainer">
                        <div class="container bg-primary p-2">
                            <div class="row">
                                <div class="col-md-4 col-sm-4 place-an-order-back-button">
                                    <div class="move movea">
                                    <img src="<?php echo $this->getUrl() .'pub/media/wysiwyg/move.svg' ?>">
                                </div>
                                    <span  data-dismiss="modal" aria-label="Close">
                                        <?php if (!$customerSession->isLoggedIn()): ?>
                                    <?php echo __("Back"); //class="backtoproduct"
             ?></span>
                                    <?php
        endif; ?>
                                </div>
                                <div class="col-md-4 col-sm-4 text-center place-an-order-text">
                                    <?php echo __("Place an Order"); ?>
                                </div>
                                <div class="col-md-2 col-sm-2 close_button_head_prev"></div>
                                <div class="col-md-2 col-sm-2 close_button_head_viewstock" data-dismiss="modal" style="cursor:pointer !important;">
                                    <button type="button" class="productview-modal-close-inside"><i class="fa fa-times"></i></button>
                                </div>
                            </div>
                        </div>
                        <input type="hidden" id="flatDiscount" name="flatDiscount" value="<?=$CustomerData['FlatDiscount']?>">
                        <?php
        $getponumber = $block->getcustomponumber($customerSession->getCustomerId());
?>
                        <div class="container bg-light p-2">
                            <h4 class="col-md-12">Create a new purchase order, or add it to an existing one.</h4>
                            <div class="row add_update_po_section">
                                <div class="col-md-4">
                                    <input class="tabactive" name="po_number" type="text" placeholder="P.O NUMBER" value="">
                                    <span ></span>
                                </div>
                                <span>or</span>
                                <div class="col-md-4 text-center">
                                    <!--<input name="select_existing p.o." type="text" >-->
                                    <select  id="select_existing" name="select_existing_p_o">
                                    </select>
                                    <input type="hidden" name="sap_ponumber_id" value="" id="sap_ponumber_id">
                                    <input type="hidden" name="order_id" value="" id="order_id">

                                </div>
                                <div class="col-md-3">
                                    <div class="show-product-dis-box">
                                         <span><?php echo $collcationValue; ?> </span><br/>
                                         <span>Style: <span id="current_active_style_head"><?php echo $parent_style; ?></span></span></br>
                                         <span>Status: <span><?php echo $style_status; ?></span></span>
                                    </div>
                                </div>
                                <!--<div class="col-md-3">
                                    <input type="submit" class="btn-primary float-right" value="<?=$block->escapeHtml(__('Add To P.O.')) ?>" />
                                </div>-->
                            </div>

                        </div>
                        <div id="message" class="messages">
                            <div id="msg_text"></div>
                        </div>
            <?php if (isset($petiteSku) && $petiteSku != '' || isset($tailSku) && $tailSku != '') { ?>
          <div class="catBtns">
              <?php if (isset($regularSku) && $regularSku != '') { ?>
              <a href="javascript:void(0)" id="Regular" product-sku="<?php echo $regularSku; ?>" class="customBtns <?php if ($parent_style == $regularSku) {
                    echo 'activeCat';
                } ?>">Regular</a>
              <?php           } ?>
              <?php if (isset($petiteSku) && $petiteSku != '') { ?>
              <a href="javascript:void(0)" id="Petite" product-sku="<?php echo $petiteSku; ?>" class="customBtns <?php if ($parent_style == $petiteSku) {
                    echo 'activeCat';
                } ?>">Petite</a>
              <?php
            } ?>
              <?php if (isset($tailSku) && $tailSku != '') { ?>
              <a href="javascript:void(0)" id="Tall" product-sku="<?php echo $tailSku; ?>" class="customBtns <?php if ($parent_style == $tailSku) {
                    echo 'activeCat';
                } ?>">Tall</a> <!--activeCat-->
              <?php
            } ?>
          </div>
          <?php
        } ?>
               
          <div  id='color-data'>
            <div class="option-thumbnail" id="myTask">
        <?php
        $size_char_i = 0;
        foreach ($parent_color_data as $current_style => $current_style_data) {
        $main_color_array = [];
        $activeclass = '';
            foreach ($current_style_data as $key => $color_data) {
                if ($color_data['Color'] != '' && $color_data['ColorSwatch'] != '') {
                    if (!in_array($color_data['ColorCode'], $main_color_array)) {
    ?>
                        <div id="<?=$current_style?>DR<?=preg_replace('/[^a-zA-Z0-9_ %\[\]\.\(\)%&-]/s', '', $color_data['ColorCode']) ?>" class='<?=$size_char_i === 0 ? 'active' : '' ?>'>
                              <a class="btn-gallery">
                    <?php if ($color_data['U_WImage1']) { ?>    
                        <?php if ($size_char_i <= 0) { ?>
                                <img class="popupImage" src="<?=$color_data['U_WImage1'] ?>" alt="<?=$color_data['ColorCode'] ?>"  />
                            <?php
                            } else { ?>
                                        <img class="popupImage" src='<?=$color_data['U_WImage1'] ?>'  data-href='<?=$color_data['U_WImage1'] ?>'/>
                                    <?php
                            } ?>
                                <?php
                        } else { ?>
                                    <img src='<?=$placeholder_image?>' class="popupImage"  />
                                <?php
                        } ?>
                            </a>
                        </div>
                        <?php $main_color_array[] = $color_data['ColorCode'];
                        $size_char_i++;
                    }
                }
            }
        } ?>
    </div>
                        <?php
        $activetabcoun = 0;
    foreach ($parent_color_data as $current_style => $current_style_data) {
        $main_color_array = array();
        $main_color_html = '<div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">';
        $main_color_i = $fashionColor_i = 0;
        $main_color_class = '';
        $main_size_char_html = '<div class="tab-content order-table" id="nav-tabContent"> ';
        $colorChange = '';
        $size_char_i = 0;
        $coreColor = '';
        $fashionColor = '';
        $fashionColorName = '';
        $first_option_color = '';
        $defaultcoreselectedcolor = "";
        $defaultfashionselectedcolor = '';
        $main_color_array = array();
        $eta_date = array();
        $activetabclass = "";
        if($activetabcoun === 0){
            $activetabclass = "active";
        }else{
            $activetabclass = "";
        }


        // echo "<span>".$current_style"</span>";

        echo "<div id='" . $current_style . "' class='product_options ".$activetabclass."'><div id='overlay' style='display:none'></div>";
            $activetabcoun++;
            foreach ($current_style_data as $key => $color_data) {
                if ($color_data['Color'] != '' && $color_data['ColorSwatch'] != '') {
                    $eta_row_avail_to_show = false;
                    if (!in_array($color_data['ColorCode'], $main_color_array)) {
                        if ($main_color_i != 0) {
                            $main_color_class = '';
                            //$main_color_aria = '';
                            $main_color_aria = 'aria-selected="true"';
                        }
                        if ($main_color_i == 0) {
                            $main_color_class = 'active';
                            $main_color_aria = 'aria-selected="false"';
                        }
                        if ($color_data['ColorStatus'] === 'Core') {
                            if ($main_color_i == 0) {
                                $defaultcoreselectedcolor = $color_data['Color'];
                            }
                            $coreColor.= '<div id="core" class="' . $main_color_class . ' swatch-option image "  data-toggle="tab" href="#'.$current_style . $color_data['ColorCode'] . '" option-color-code ="' . preg_replace('/[^a-zA-Z0-9_ %\[\]\.\(\)%&-]/s', '', $color_data['ColorCode']) . '" option-color-status = "' . $color_data['ColorStatus'] . '" option-style-status = "' . $color_data['StyleStatus'] . '" tabindex="' . $key . '" option-id="' . $color_data['Style'] . '" option-core-color-name = "' . $color_data['Color'] . '" option-tooltip-thumb="' . strtolower($color_data['ColorSwatch']) . '" option-tooltip-value="' . strtolower($color_data['ColorSwatch']) . '" role="tab" aria-controls="' . $color_data['ColorCode'] . '" ' . $main_color_aria . ' style="background: url(' . strtolower($color_data['ColorSwatch']) . ') no-repeat center; background-size: 650%;">

                                <div class="box-hover">
                                    <img class="in2" src="'.$this->getUrl().'/pub/media/wysiwyg/swatcher_image.svg">
                                    <img class="in1" src=' . strtolower($color_data['ColorSwatch']) . '>
                                </div>

                                <span class="swatch_img"><input name="style" type="hidden" value ="' . $current_style . '"><input name="qty_change_' . $color_data['ColorCode'] . '"class="qty_change" id="qty_change_' . $color_data['ColorCode'] . '" type="hidden" value ="0"> </span><div class="bottom-tooltip-active"><p class="color-active">' . $color_data['Color'] . '</p></div></div>';
                        } else if ($color_data['ColorStatus'] !== '') {
                            if ($main_color_i == 0) {
                                $defaultfashionselectedcolor = $color_data['Color'];
                            }
                            if ($fashionColor_i == 0) {
                                $fashionColorName = $color_data['Color'];
                                $first_option_color = $color_data['ColorStatus'];
                            }
                            $fashionColor.= '<div id="fashion" class="' . $main_color_class . ' swatch-option image "  data-toggle="tab" href="#'.$current_style . $color_data['ColorCode'] . '" option-color-code ="' . preg_replace('/[^a-zA-Z0-9_ %\[\]\.\(\)%&-]/s', '', $color_data['ColorCode']) . '" option-color-status = "' . $color_data['ColorStatus'] . '" option-style-status = "' . $color_data['StyleStatus'] . '" tabindex="' . $key . '" option-id="' . $color_data['Style'] . '" option-fashion-color-name = "' . $color_data['Color'] . '" option-tooltip-thumb="' . strtolower($color_data['ColorSwatch']) . '" option-tooltip-value="' . strtolower($color_data['ColorSwatch']) . '" role="tab" aria-controls="' . $color_data['ColorCode'] . '" ' . $main_color_aria . ' style="background: url(' . strtolower($color_data['ColorSwatch']) . ') no-repeat center; background-size: 650%;">
                                <div class="box-hover">
                                    <img class="in2" src="'.$this->getUrl().'/pub/media/wysiwyg/swatcher_image.png">
                                    <img class="in1" src=' . strtolower($color_data['ColorSwatch']) . '>
                                </div>
                                <span class="swatch_img"><input name="style" type="hidden" value ="' . $current_style . '"><input name="qty_change_' . $color_data['ColorCode'] . '"class="qty_change" id="qty_change_' . $color_data['ColorCode'] . '" type="hidden" value ="0"> </span><div class="bottom-tooltip-active"><p class="color-active">' . $color_data['Color'] . '</p></div></div>';
                            $fashionColor_i++;
                        }
                        $main_color_i++;
                        $main_color_array[] = $color_data['ColorCode'];
                        $activeclass = '';
                        $filterBy = $color_data['ColorCode'];
                        $colorcode_array = array_filter($current_style_data, function ($var) use ($filterBy) {
                            return ($var['ColorCode'] == $filterBy);
                        });
                        $filterByEta = '';
                        $eta_array = array_filter($colorcode_array, function ($var) use ($filterByEta) {
                            return (!empty((int)$var["ETA"]));
                        });
                        if ($size_char_i == 0) {
                            $activeclass = 'active';
                        }
                        $main_size_char_html.= '<div class="tab-pane fade show ' . $activeclass . '" id="'. $current_style. $color_data['ColorCode'] . '" role="tabpanel">';
                        $tr_one = '<tr><td align="right">Size</td>';
                        $tr_two = '<tr><td align="right">Price</td>';
                        $tr_three = '<tr><td align="right">In Stock</td>';
                        // if (!empty($eta_array)) {
                        $tr_three1 = '<tr><td align="right" class="order_head_eta_title" width="75"><p class="head_restockdate_lable_p">Restock Date</p><p class="head_restockqty_lable_p">Restock QTY.</p></td>';
                        // }
                        $tr_four = '<tr><td align="right">Quantity</td>';
                        $tr_five = '<tr><td align="right">Total</td>';
                        foreach ($colorcode_array as $key => $value) {
                            $qty = (isset($value["ActualQty"]) && $value["ActualQty"] != '') ? $value["ActualQty"] : 0.00;
                            $show_qty = (isset($value["QtyAvailable"]) && $value["QtyAvailable"] != '') ? $value["QtyAvailable"] : 0.00;
                            $tr_one.= '<td align="center">' . $value['Size'] . '</td>';
                            if ($value["DisPrice"] < $value["UnitPrice"]) {
                                $tr_two.= '<td align="center" class="disprice"><span>' . $priceHelper->currency($value["DisPrice"], true, false) . '</span><span class="mainprice">' . $priceHelper->currency($value["UnitPrice"], true, false) . '</span> </td>';
                            } else {
                                $tr_two.= '<td align="center">' . $priceHelper->currency($value["UnitPrice"], true, false) . '</td>';
                            }
                            $tr_three.= '<td align="center">' . ((floatval($qty) >= 500) ? '500+' : floatval($qty)) . '</td>';
                            // $eta_date = array();
                            $eta_date = array(
                                "ETA1" => array(
                                    "Date" => date("m-d-y", strtotime($value["ETA1"])), 
                                    "Qty" => $value["EtaQty1"],
                                    "compare" => date("Y-m-d", strtotime($value["ETA1"])),
                                ), 
                                "ETA2" => array(
                                    "Date" => date("m-d-y", strtotime($value["ETA2"])), 
                                    "Qty" => $value["EtaQty2"],
                                    "compare" => date("Y-m-d", strtotime($value["ETA2"])),
                                ), 
                                "ETA3" => array(
                                    "Date" => date("m-d-y", strtotime($value["ETA3"])), 
                                    "Qty" => $value["EtaQty3"],
                                    "compare" => date("Y-m-d", strtotime($value["ETA3"])),
                                ));

                            date_default_timezone_set("America/New_York");
                            $currentdate = date('Y-m-d', strtotime('-7 days'));

                            if (!empty($eta_date)) {
                                $count = 1;
                                $tag_count = 0;
                                $eta_count_top = 0;
                                $eta_class = "eta-tooltip";
                                $eta_avail_to_show = false;
                                foreach ($eta_date as $keys => $datas) {
                                    if ($eta_date[$keys]["compare"] > $currentdate && !empty((int)$datas["compare"]) && $eta_date[$keys]["Qty"] > 0 && $eta_avail_to_show == false) {
                                        $eta_avail_to_show = true;
                                        $eta_row_avail_to_show = true;
                                        // echo $eta_avail_to_show;
                                        
                                    }
                                }
                                if ($eta_avail_to_show) {
                                    $tr_three1.= '<td class="order_head_eta_data" align="center">';
                                    foreach ($eta_date as $key => $date_eta) {
                                        if ($eta_date[$key]["compare"] > $currentdate && !empty((int)$date_eta["compare"]) && $eta_date[$key]["Qty"] > 0) {
                                            // $tr_one .= '<p class="eta-date-list">'.$count.'. '.$eta_date[$key]["Date"].' - '.$eta_date[$key]["Qty"] .'</p>';
                                            $eta_qty_show = $eta_date[$key]["Qty"];
                                            if ($eta_qty_show > 500) {
                                                $eta_qty_show = "500+";
                                            }
                                            $tr_three1.= '<div class="eta_date_qty_cont">';

                                            if(($currentdate < $eta_date[$key]["compare"]) && ($eta_date[$key]["compare"] < date('Y-m-d'))){
                                                $tr_three1 .= '<p class="eta_date_product_option_span eta_date_past_date">';

                                                $tr_three1 .= '<span class="back_date_tooltip">Receiving Delay: The receiving of this date is delayed with few days due to port congestion.</span>';

                                                $tr_three1 .= '<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 286.054 286.054" style="enable-background:new 0 0 286.054 286.054;" xml:space="preserve">
                                                        <g>
                                                            <path style="fill:#E2574C;" d="M143.027,0C64.04,0,0,64.04,0,143.027c0,78.996,64.04,143.027,143.027,143.027
                                                                c78.996,0,143.027-64.022,143.027-143.027C286.054,64.04,222.022,0,143.027,0z M143.027,259.236
                                                                c-64.183,0-116.209-52.026-116.209-116.209S78.844,26.818,143.027,26.818s116.209,52.026,116.209,116.209
                                                                S207.21,259.236,143.027,259.236z M143.036,62.726c-10.244,0-17.995,5.346-17.995,13.981v79.201c0,8.644,7.75,13.972,17.995,13.972
                                                                c9.994,0,17.995-5.551,17.995-13.972V76.707C161.03,68.277,153.03,62.726,143.036,62.726z M143.036,187.723
                                                                c-9.842,0-17.852,8.01-17.852,17.86c0,9.833,8.01,17.843,17.852,17.843s17.843-8.01,17.843-17.843
                                                                C160.878,195.732,152.878,187.723,143.036,187.723z"/>
                                                        </g>
                                                        </svg>';
                                                $tr_three1 .= '<span>'.$eta_date[$key]["Date"].'</span>';
                                                $tr_three1 .= '</p>';
                                                $tr_three1 .= '<p class="eta_qty_product_option_span eta_date_past_date">'.$eta_qty_show.'</p></div>';                                                
                                            }else{
                                                $tr_three1 .= '<p class="eta_date_product_option_span">'.$eta_date[$key]["Date"].'</p>';
                                                $tr_three1 .= '<p class="eta_qty_product_option_span">'.$eta_qty_show.'</p></div>';
                                            }
                                            
                                            $count++;
                                        }
                                    }
                                    $tr_three1.= '</td>';
                                } else {
                                    $tr_three1.= '<td align="center"></td>';
                                }
                                // if (empty((int)$value["ETA"])) {
                                //     $tr_three1 .= '<td align="center"></td>';
                                // } else {
                                //     $tr_three1 .= '<td align="center">' . date("m-d-y", strtotime($value["ETA"])) . '</td>';
                                // }
                                
                            }
                            $tr_four.= '<td align="center" class="qtyTd">
                                      <input name="qty[' . $value['Color'] . '][' . $value['Size'] . ']" type="text" pattern="[0-9]" min="1" class="checkvalue" autocomplete="off" max="' . floatval($qty) . '" ' . (($qty <= 0) ? '"' : "") . ' >
                                      <span class="maxqtyvaldi"></span>
                                      <input name="showprice[' . $value['Color'] . '][' . $value['Size'] . ']" type="hidden" value ="' . floatval($value["DisPrice"]) . '">
                                      <input name="selectcolor" type="hidden" value ="' . $value['Color'] . '">
                                      <input name="selectsize" type="hidden" value ="' . $value['Size'] . '">
                                      <input name="itemscode[' . $value['Color'] . '][' . $value['Size'] . ']" type="hidden" value ="' . $value['ItemCode'] . '">
                                      <input name="colorcode[' . $value['Color'] . '][' . $value['Size'] . ']" type="hidden" value ="' . $value['ColorCode'] . '">
                                      <input name="mainprice[' . $value['Color'] . '][' . $value['Size'] . ']" type="hidden" value ="' . floatval($value["UnitPrice"]) . '">
                                      <input name="DiscountPer[' . $value['Color'] . '][' . $value['Size'] . ']" type="hidden" value ="' . floatval($value["DisPercent"]) . '">
                                      <input name="DiscountPrice[' . $value['Color'] . '][' . $value['Size'] . ']" type="hidden" value ="' . floatval($value["DisPrice"]) . '">
                                      </td>';
                            $tr_five.= '<td align="center" class="total"><input class="unittotal" name="inpprice[' . $value['Color'] . '][' . $value['Size'] . ']" type="hidden" value =""><span class="showprice"></span></td>';
                        }
                        $tr_one.= '</tr>';
                        $tr_two.= '</tr>';
                        $tr_three.= '</tr>';
                        if ($eta_row_avail_to_show) {
                            $tr_three1.= '</tr>';
                        }
                        $tr_four.= '</tr>';
                        $tr_five.= '</tr>';
                        $main_size_char_html.= "<div class='colorContainer'><table class='table table-bordered table-responsive'>";
                        $main_size_char_html.= $tr_one;
                        $main_size_char_html.= $tr_two;
                        $main_size_char_html.= $tr_three;
                        if ($eta_row_avail_to_show) {
                            $main_size_char_html.= $tr_three1;
                        }
                        $main_size_char_html.= $tr_four;
                        $main_size_char_html.= $tr_five;
                        $main_size_char_html.= '</table><div  class="cf viewpouplink"><a href="javascript:" class="saveChng">Add/Update P.O.</a><a href="javascript:" class="discardChng" >Discard Changes</a><input name="submitcolor" type="hidden" value ="' . $value['Color'] . '"><input id="closepopup" name="closepopup" type="hidden" value =""></div><div class="lineitems"></div></div></div>';
                        $size_char_i++;
                    } else {
                    }
                }
            }
            if ($coreColor != '' || $fashionColor != '') {
                $main_color_html.= '<div class="swtach">';
            }
            if ($coreColor != '') {
                $main_color_html.= '
                  <div class="customorder-color core-color-section">
                      <div id="coreClass" class="colorImage active">
                          <span>Core Colors: </span>

                      </div>
                      <div class="swatch-color-container">' . $coreColor . '</div>
                  </div>';
            }
            if ($fashionColor != '') {
                $main_color_html.= '
                  <div class="customorder-color fashion-color-section">
                      <div id="fashionClass" class="colorImage">
                          <span>Fashion Colors:</span>

                      </div>
                      <div class="swatch-color-container">' . $fashionColor . '</div>
                  </div>';
            }
            $main_color_html.= '<div class="colorstatus"><span id="colorstatus">Selected Color Status : </span><span id="Status">' . $color_data['ColorStatus'] . '</span></div></div>';
            if ($coreColor === '' && $fashionColor === '') {
                $main_color_html.= '<span class="style-notfound custom-error message-error error">Item not found.</span>';
            }
            echo $main_color_html;
            echo "</div>";
            echo $main_size_char_html;
            // echo "<span>Tes</span>";
            echo "</div></div>";
        }
        foreach ($parent_color_data as $current_style => $current_style_data) {
            foreach ($current_style_data as $key => $values) {
                if ($values['Color'] != '' && $values['ColorSwatch'] != '') {
                    if (!in_array($values['ColorCode'], $main_color_array)) {
                        echo "<div id='" . $values['Style'] . "_" . str_replace("/", "", $values['ColorCode']) . "' class='collapseContainer cart-popup'>";
                        echo '<a href="#' . str_replace("/", "", $values['ColorCode']) . '" data-toggle="collapse" class="collapsed"><span class="swatch_img"><input name="style" type="hidden" value ="' . $current_style . '"><input name="qty_change_' . str_replace("/", "", $values['ColorCode']) . '"  class="qty_change" id="qty_change_' . str_replace("/", "", $values['ColorCode']) . '" type="hidden" value ="0">';
                        if (!empty($values['ColorSwatch'])) echo '<img src="' . strtolower($values['ColorSwatch']) . '" ></span>&nbsp;&nbsp;';
                        echo $values['Color'] . ' / ' . $values['ColorStatus'] . '</a>';
                        $main_color_array[] = $values['ColorCode'];
                        $filterBy = $values['ColorCode'];
                        $colorcode_array = array_filter($current_style_data, function ($var) use ($filterBy) {
                            return ($var['ColorCode'] == $filterBy);
                        });
                        echo "<div id='" . str_replace("/", "", $values['ColorCode']) . "' class='collapse'>";
                        $tr_one = '<tr><td align="right">Size</td>';
                        $tr_two = '<tr><td align="right">Price</td>';
                        $tr_three = '<tr><td align="right">In Stock</td>';
                        //$etacheck = $block->getchecketa($values['Style'],$values['ColorCode']);
                        $filterByEta = '';
                        // $eta_array = array_filter($colorcode_array, function ($var) use ($filterByEta) {
                        //      return ($var['ETA'] != '');
                        //  });
                        $eta_array = array_filter($colorcode_array, function ($var) use ($filterByEta) {
                            return (!empty((int)$var["ETA"]));
                        });
                        // if(!empty($eta_array))
                        // {
                        $tr_three1 = '<tr class=""><td align="right" width="75">Restock Date</td>';
                        // }
                        $tr_four = '<tr><td align="right">Quantity</td>';
                        $tr_five = '<tr><td align="right">Total</td>';
                        //$parent_color_data = $block->DatabyColor($values['Style'],$values['ColorCode']);
                        $qty = 0.00;
                        foreach ($colorcode_array as $key => $value) {
                            $qty = (isset($value["ActualQty"]) && $value["ActualQty"] != '') ? $value["ActualQty"] : 0.00;
                            $show_qty = (isset($value["QtyAvailable"]) && $value["QtyAvailable"] != '') ? $value["QtyAvailable"] : 0.00;
                            //echo "<pre>";print_R($value);
                            // if(floatval($value["QtyAvailable"]) > 0)
                            // {
                            $tr_one.= '<td align="center">' . $value['Size'] . '</td>';
                            if ($value["UnitPrice"] > $value["DisPrice"]) {
                                $tr_two.= '<td align="center" class="disprice aaa"><span>' . $priceHelper->currency($value["DisPrice"], true, false) . '</span> <span class="mainprice">' . $priceHelper->currency($value["UnitPrice"], true, false) . '</span></td>';
                            } else {
                                $tr_two.= '<td align="center">' . $priceHelper->currency($value["UnitPrice"], true, false) . '</td>';
                            }
                            $tr_three.= '<td align="center">' . floatval($show_qty) . ((floatval($show_qty) >= 100) ? '+' : '') . '</td>';
                            if (!empty($eta_array)) {
                                if (empty((int)$value["ETA"])) {
                                    $tr_three1.= '<td align="center"></td>';
                                } else {
                                    $tr_three1.= '<td align="center">' . date("m-d-y", strtotime($value["ETA"])) . '</td>';
                                }
                            }
                            $tr_four.= '<td align="center" class="qtyTd">
                                            <input name="qty[' . $value['Color'] . '][' . $value['Size'] . ']" type="text" pattern="[0-9]" min="1" class="checkvalue" autocomplete="off" max="' . floatval($qty) . '" ' . (($qty <= 0) ? '"' : "") . ' >
                                            <span class="maxqtyvaldi"></span>
                                            <input name="showprice[' . $value['Color'] . '][' . $value['Size'] . ']" type="hidden" value ="' . floatval($value["DisPrice"]) . '">
                                            <input name="selectcolor" type="hidden" value ="' . $value['Color'] . '">
                                            <input name="selectsize" type="hidden" value ="' . $value['Size'] . '">
                                            <input name="itemscode[' . $value['Color'] . '][' . $value['Size'] . ']" type="hidden" value ="' . $value['ItemCode'] . '">
                                            <input name="colorcode[' . $value['Color'] . '][' . $value['Size'] . ']" type="hidden" value ="' . $value['ColorCode'] . '">
                                            <input name="mainprice[' . $value['Color'] . '][' . $value['Size'] . ']" type="hidden" value ="' . floatval($value["UnitPrice"]) . '">
                                            <input name="DiscountPer[' . $value['Color'] . '][' . $value['Size'] . ']" type="hidden" value ="' . floatval($value["DisPercent"]) . '">
                                            <input name="DiscountPrice[' . $value['Color'] . '][' . $value['Size'] . ']" type="hidden" value ="' . floatval($value["DisPrice"]) . '">
                                            </td>';
                            $tr_five.= '<td align="center" class="total"><input class="unittotal" name="inpprice[' . $value['Color'] . '][' . $value['Size'] . ']" type="hidden" value =""><span class="showprice"></span></td>';
                            //  }
                            
                        }
                        $tr_one.= '</tr>';
                        $tr_two.= '</tr>';
                        $tr_three.= '</tr>';
                        if (!empty($eta_array)) {
                            $tr_three1.= '</tr>';
                        }
                        $tr_four.= '</tr>';
                        $tr_five.= '</tr>';
                        echo "<div class='colorContainer'><table class='table table-bordered table-responsive'>";
                        echo $tr_one;
                        echo $tr_two;
                        echo $tr_three;
                        if (!empty($eta_array)) {
                            echo $tr_three1;
                        }
                        echo $tr_four;
                        echo $tr_five;
                        echo '</table><div  class="cf viewpouplink"><a href="#" class="saveChng">Add/Update P.O.</a><a href="#" class="discardChng" >Discard Changes</a><input name="submitcolor" type="hidden" value ="' . $value['Color'] . '"><input id="closepopup" name="closepopup" type="hidden" value =""></div></div>';
                        echo "</div>";
                        echo "</div>";
                    }
                }
            }
        }
            echo "</div>";
        echo "<div class='container bg-light p-2  bottomBtn'><a class='btn-primary float-right' id='chekout'><strong>CHECKOUT</strong> : <span class='grandtotal'>$0.00</span><input type='hidden' id='hi_grandtotal' name='hi_grandtotal' value=''><input type='hidden' id='activetab_id' name='activetab_id' value=''><input type='hidden' id='chekouthidden' name='chekouthidden' value=''></a></div></div>";
?>


                            </div>
                        </form>
                        <div class="modal fade" id="removeUser" role="dialog" style="z-index: 1600;">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="quickViewCont">
                                        <div class="container bg-primary p-2">
                                            <div class="row">
                                                <div class="col-md-4 offset-md-4 text-center">
                                                    <a href="#" title="" class="mobileLogo" style="display:inline;" height="37" width="37"><img height="37" width="37" src="<?php echo $this->getUrl(); ?>/pub/static/frontend/sttl/adaruniforms/en_US/images/mobile-logo-white.png"></a>
                                                </div>
                                                <div class="col-md-4">
                                                    <!--<button type="button" data-dismiss="modal" class="close mfp-close-inside"><i class="fa fa-times"></i></button>-->
                                                </div>
                                            </div>
                                        </div>
                                        <div class="comingSoonTxt center">
                                            <div class="comingSoonTxt center">
                                                <p  class="mrgT20 padB20">Do you want to save and continue?</p>
                                            </div>
                                            <div class="center mrgB20">
                                                <button class="themeBtn" id="goback" data-dismiss="modal" type="button">Go Back</button>
                                                <button class="themeBtn mrgL20" id="savecontinue" type="submit">Save & Continue</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php
    }
endif;
?>


<div class="modal-content quickViewCont imgquickViewCont" id="imgquickViewCont">
  <div class="container">          
         <button type="button" class="mfp-close close-image-chart-popup"><i class="fa fa-times"></i></button>  
       <img src="<?php echo $this->getUrl(); ?>/pub/media/catalog/product/placeholder/default/image-placeholder.jpg" class="ProductShow"/>      
  </div>
</div>
<?php
echo $this->getLayout()->createBlock('Magento\Catalog\Block\Category\View')->setcustomer($customerSession)->setTemplate('Magento_Catalog::product/view/produtc_page_js.phtml')->toHtml();
?>