<?php
	/**
		* Copyright © Magento, Inc. All rights reserved.
		* See COPYING.txt for license details.
	*/
	
	// @codingStandardsIgnoreFile
	
	/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
	
	$helper = $this->helper('Sttl\Adaruniforms\Helper\Sap');
	$om = \Magento\Framework\App\ObjectManager::getInstance();
	$customerSession = $om->create('Magento\Customer\Model\Session');
	$customerName = $customerEmail = "";
	$customer_phone = 'N/A';
	$data = $helper->getCustomerDetails();
	if($customerSession->isLoggedIn()) {
		$customerName = $customerSession->getCustomer()->getName(); 
		$customerEmail = $customerSession->getCustomer()->getEmail();
		$customerPassword = $customerSession->getCustomer()->getPasswords();
		if (isset($data[0]["Phone1"]) && !empty($data[0]["Phone1"]))
		$customer_phone = str_replace("-",".",$data[0]["Phone1"]);
	}
	
	
?>
<div class="accountStatus">Account Status: <span>Active</span></div>
<div class="cf"></div>
<div class="block block-dashboard-info">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Account Details')) ?></strong>
		
	</div>
    
	
	<div class="block-content accountDtlSection">
		
		<div class="box box-information col-md-4"> 
			<strong class="box-title"> <span>Full Name:</span> </strong>
			<div class="box-content">
				<p><?php echo $customerName; ?><br>
				</p>
			</div>
			<div class="box-actions">
				<a class="action edit" data-toggle="modal" attr-type = "fullname" data-target="#customer-edit"><span><?= $block->escapeHtml(__('Edit')) ?></span></a>
				<!-- <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>">
					<span><?= $block->escapeHtml(__('Edit')) ?></span> 
				</a>-->
			</div>
		</div>
		
		
		<div class="box box-information emailBox"> <strong class="box-title"> <span>Email/User ID:</span></strong>
			<div class="box-content emailVal">
				<p>
					<?php echo $customerEmail; ?><br>
				</p>
			</div>
			<div class="box-actions">
				<a class="action edit" data-toggle="modal"  attr-type = "email" data-target="#customer-edit"><span><?= $block->escapeHtml(__('Edit')) ?></span></a>
				<!-- <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>">
					<span><?= $block->escapeHtml(__('Edit')) ?></span> 
				</a>-->
			</div>
		</div>
		
		
		<div class="box box-information pswdBox"> <strong class="box-title"> <span>Password:</span> </strong>
			<div class="box-content">
				<p>*****</p>
			</div>
			<div class="box-actions">
				<a class="action edit" data-toggle="modal" attr-type = "password" data-target="#customer-edit"><span><?= $block->escapeHtml(__('Edit')) ?></span></a>
				<!-- <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>">
					<span><?= $block->escapeHtml(__('Edit')) ?></span> 
				</a>-->
			</div>
		</div>
		
		<div class="box box-information col-md-4"> 
			<strong class="box-title"> <span>Phone Number:</span> </strong>
			<div class="box-content">
				<p><?php echo $customer_phone;?></p>
			</div>
		</div>
		
	</div>
	<script type="text/javascript">
		require(['jquery'], function($) {
			$('#customer-edit').on('show.bs.modal', function(e){
				var type = $(e.relatedTarget);
				var recipient = type.attr('attr-type');
				
				if (recipient == "email") {
					$("#change-email").attr("checked", true).change();
					$(".field-name-lastname, .field-name-firstname").hide();
				}
				if (recipient == "password") {
					$("#change-password").attr("checked", true).change();
					$(".field-name-lastname, .field-name-firstname").hide();
				}
			});
			
			$('#customer-edit').on('hide.bs.modal', function(e){
				var type = $(e.relatedTarget);
				var recipient = type.attr('attr-type');
				
				$("#change-email").attr("checked", false).change();
				$("#change-password").attr("checked", false).change();
				$(".field-name-lastname, .field-name-firstname").show();
			});
		});
	</script>
	
	
	
	
	
	
	
	
	
	
	
	
	<?php /*  ?>
		<div class="block-content">
        <div class="box box-information">
		<strong class="box-title">
		<span><?= $block->escapeHtml(__('Full Name')) ?></span>
		</strong>
		<div class="box-content">
		<p>
		<?= $block->escapeHtml($block->getName()) ?><br>
		</p>
		</div>
        </div>
        
        <div class="box box-information">
		<strong class="box-title">
		<span><?= $block->escapeHtml(__('Phone Number')) ?></span>
		</strong>
		<div class="box-content">
		<p>
		<?= $block->escapeHtml($block->getTelephone()) ?><br>
		</p>
		</div>
        </div>
		</div>
		
	<?php */ ?>
	
</div>
