<?php
	/**
		* Copyright © Magento, Inc. All rights reserved.
		* See COPYING.txt for license details.
	*/
	
	// @codingStandardsIgnoreFile
	
	/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
	
$helper = $this->helper('Sttl\Adaruniforms\Helper\Sap');
$data = $helper->getCustomerShippingAddressDetails();
if(isset($data) && !isset($data['errors'])) 
{
$CountryList =  $helper->getCountryList();

$StateListarray =  $helper->getStateList();
$StateList = json_encode($StateListarray);
?> 
<div class="block block-dashboard-info shippingBlock">
    <div class="block-title collapsed" data-toggle="collapse" data-target="#collapseFour" aria-expanded="true" aria-controls="collapseFour"><strong class="upperCaseText"><?= $block->escapeHtml(__('Shipping Information')) ?></strong>
	</div>
    <div id="collapseFour" class="block-content collapse paddL15" aria-labelledby="headingOne"> 
		<div class="box box-information">
			<strong class="box-title">
				Manage and add new shipping information.
			</strong>
			<div class="box-content">
				<select class="shippingMeethod" name="shippingaddress" id="shippingaddress">
					<option>Please Select</option>
					<?php if (isset($data) && !empty($data)) { 
						$cnt = 1;
						foreach($data as $addKey => $addVal) {
							$addVal["PhoneNo"] = '';
							$addVal["Id"] = $cnt;
							$default_add = ($addVal["DefaultAdd"] == "Y") ? "selected" : "";
							
							echo '<option value="'.$cnt.'" attr-CardName="'.$addVal["CardName"].'"  attr-addressID="'.$addVal["AddressID"].'" attr-addr1="'.$addVal["AddStreetNo"].'" attr-addr2="'.$addVal["Address2"].'" attr-State="'.$addVal["State"].'"  attr-ZipCode="'.$addVal["ZipCode"].'" attr-Country="'.$addVal["Country"].'" attr-city="'.$addVal["City"].','.$addVal["State"].' '.$addVal["ZipCode"].'" attr-city1="'.$addVal["City"].'" attr-blindDropship="'.$addVal["BlindDropship"].'" attr-tel="'.$addVal["PhoneNo"].'" '.$default_add.' >'.ucwords(strtolower($addVal["AddressID"])).'</option>';
					$cnt++; } } ?>
				</select>
				<div class="shipAddress"></div>
				<input type="submit" value="+ Add New Address" data-toggle="modal" data-target="#customer-edit-address"  class="themeBtn" />
				
			</div>
		</div>
		
	</div>
</div>
<script type="text/javascript">
    require(['jquery'], function($) {
		$(document).on("change", "#shippingaddress", function(){
			var Objsel = $(this).find('option:selected');
			
			var addline1 = $(Objsel).attr("attr-addr1"),
			addline2 = $(Objsel).attr("attr-addr2"),
			addline3 = $(Objsel).attr("attr-city"),
			addline4 = $(Objsel).attr("attr-tel"),

			attrcardname = $(Objsel).attr("attr-cardname"),
			attraddressid = $(Objsel).attr("attr-addressid"),
			attrzipcode = $(Objsel).attr("attr-zipcode"),
			attrcountry = $(Objsel).attr("attr-country"),
			attrstate = $(Objsel).attr("attr-state"),
			attrcity1 = $(Objsel).attr("attr-city1"),
			attrblindDropship = $(Objsel).attr("attr-blindDropship"),
			address = [];
			
			if (typeof addline1 !== typeof undefined && addline1 !== false && addline1.trim() != '') {
				address.push(addline1);
			}	
			
			if (typeof addline2 !== typeof undefined && addline2 !== false && addline2.trim() != '') {
				address.push(addline2);
			}
			
			if (typeof addline3 !== typeof undefined && addline3 !== false && addline3.trim() != '') {
				address.push(addline3);
			}
			
			if (typeof addline4 !== typeof undefined && addline4 !== false && addline4.trim() != '') {
				address.push(addline4);
			}
			
			if (address.length)
			$(".shipAddress").html(address.join("<br/>"));
			else 
			$(".shipAddress").html("");
		});
		
		$(function() {
			$('.modal.block-customer-edit-address').on('hidden.bs.modal', function(){
				$('#customer-edit-address-validate').find('input[type="text"]').val('');
				$('#Country [value="US"]').attr('selected', 'true');
				$("#Country").trigger('change');
				var validator = $("#customer-edit-address-validate").validate();
				validator.resetForm();
			});
			$("#shippingaddress").change();
		});
	});
	
</script>
<?php
/* 	<div class="block block-dashboard-info otherUsr">
	<div class="otherUserOverlay"></div>
	<div class="block-title"><strong class="upperCaseText">Other Users</strong> <span class="addUser">+ Add User</span></div>
    <div class="block-content">
	<table class="otherUserTable">
	<tr>
	<th>Name</th>
	<th>Email</th>
	<th>Password</th>
	<th>Access To</th>
	</tr>
	<tr>
	<td>Jordan Hill</td>
	<td>jordan@abc.com</td>
	<td>*****</td>
	<td><select><option>Everything</option></select>
	</tr>
	<tr>
	<td>Alex Friedman</td>
	<td>alex@abc.com</td>
	<td>*****</td>
	<td><select><option>Everything</option></select>
	</tr>
	</table>
	
    </div>
</div> */
?>
<div class="modal fade block block-customer-edit-address comingSoon commonPopup1" id="customer-edit-address" tabindex="-1" role="dialog" aria-labelledby="addressModal" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-body">
				<div class="modalContainer block-content" aria-labelledby="block-customer-login-heading">
					<div class="messages">
						<div class="message message-error error">
							<div></div>
						</div>
					</div>
					<div class="quickViewCont">        
						<div class="container bg-primary p-2">
							
							<div class="row">
								<div class="col-md-12 text-center customer-edit-title">
									<span class="popUpTitle"><?= $block->escapeHtml(__("Add Shipping Method"));?></span>
									<button type="button" data-dismiss="modal" class="close mfp-close-inside"><i class="fa fa-times"></i></button>
								</div>          
							</div>
						</div>
						<div class="registrationPage comingSoonTxt" id="comingSoonForm">
							<form class="form custom-customer-edit-address" action="<?= $block->escapeUrl($block->getUrl('customerlogin/ajax/editAddress')) ?>" method="post" id="customer-edit-address-validate" enctype="multipart/form-data" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" autocomplete="off" data-mage-init='{"validation": {"errorClass": "mage-error"}}'>
								<div class="response-msg"></div>
								<?= $block->getBlockHtml('formkey') ?>
								<div class="field field-name-fullname required">
									<label class="label " for="fullname"><span><?= $block->escapeHtml(__('Full Name')) ?></span><span class="reqField">*</span></label>
									<div class="control">
										<input type="text" autocomplete="off" id="fullname" name="fullname" value="" title="Full Name" class="input-text required-entry validate-no-html-tags valid" data-validate="{required:true}" aria-required="true" placeholder="Full Name">
									</div>
								</div>
								<div class="field field-name-address1">
									<label class="label " for="address1"><span><?= $block->escapeHtml(__('Address Line 1')) ?></span></label>
									<div class="control">
										<input type="text" autocomplete="off" id="address1" name="address1" value="" title="Address Line 1" class="input-text" placeholder="Address Line 1">
									</div>
								</div>
								<div class="field field-name-address2">
									<label class="label " for="address2"><span><?= $block->escapeHtml(__('Address Line 2')) ?></span></label>
									<div class="control">
										<input type="text" autocomplete="off" id="address2" name="address2" value="" title="Address Line 2" class="input-text" placeholder="Address Line 2">
									</div>
								</div>
								<div class="row">
									<div class="field field-name-state required col-md-6">
										<label class="label " for="Country"><span><?= $block->escapeHtml(__('Country')) ?><span class="reqField">*</span></span></label>
										<div class="control">
										<select class="validate-select" name="Country" id="Country" >
											<option value="">Select</option>
											<?php foreach($CountryList as $Country):?>
												<option  value="<?php echo $Country['CountryCode']?>"><?php echo $Country['CountryName']?></option>
											<?php endforeach;?>
										</select>
										<input type="hidden" name="ContryLable" id="ContryLable" value="">
										</div>
									</div>
									<div class="field field-name-state required col-md-6">
										<label class="label " for="state"><span><?= $block->escapeHtml(__('State')) ?><span class="reqField">*</span></span></label>
										<div class="control">
										<select class="validate-select" name="state" id="state" >
										<option contry-code="selected" value="">Select</option>
											<?php foreach($StateListarray as $State):?>
												<option contry-code="<?php echo $State['CountryCode']?>" value="<?php echo $State['StateCode']?>"><?php echo $State['StateName']?></option>
											<?php endforeach;?>
										</select>
										<input type="hidden" name="StateLable" id="StateLable" value="">
										</div>
									</div>
								</div>
								<div class="row">
									<div class="field field-name-city required col-md-6">
										<label class="label " for="city"><span><?= $block->escapeHtml(__('City')) ?></span><span class="reqField">*</span></label>
										<div class="control">
											<input type="text" autocomplete="off" id="city" name="city" value="" title="City" class="input-text required-entry validate-no-html-tags valid" data-validate="{required:true}" aria-required="true" placeholder="City">
										</div>
									</div>
									<div class="field field-name-zipcode required col-md-6">
										<label class="label " for="zipcode"><span><?= $block->escapeHtml(__('Zip Code')) ?></span><span class="reqField">*</span></label>
										<div class="control">
											<input type="text" autocomplete="off" id="zipcode" name="zipcode" value="" title="Zip Code" class="input-text required-entry validate-no-html-tags validate-zip valid validate-alphanum-with-spaces" data-validate="{required:true}" aria-required="true" placeholder="Zip Code">
										</div>
									</div>
								</div>
								<!--<div class="row">
								<div class="field field-name-phoneno col-md-6">
										<label class="label " for="phoneno"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
										<div class="control">
											<input type="text" id="phoneno" name="phoneno" value="" title="Phone Number" class="input-text valid"  placeholder="Phone Number">
										</div>
									</div>
								</div>	-->
								<?= $block->getChildHtml('form_additional_info') ?>
								<div class="actions-toolbar mt-2">
									<div class="text-center">
										<button type="submit" class="themeBtn action save" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>"><span><?= $block->escapeHtml(__('Submit')) ?></span></button>
									</div>
								</div>
							</form>
						</div>
					</div>   
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
    require(['jquery'], function($) {
    
 //    $(function() {
	// 	$.ajax({
	// 		url: "<?php echo $block->getBaseUrl().'customerorder/customer/inventorystatus' ?>",
	// 		type: "text",
	// 		showLoader: false,
	// 		processData:false,
	// 		contentType: false,
	// 		cache: false,
	// 		success: function(response){
	// 			var response = JSON.stringify(response);
	// 			var data = JSON.parse(response);
	// 			if (data.success) {
	// 				//opt2_items_json = data.allInventoryItems;
	// 				//skusdata = data.allInventoryItems;
	// 				//jeson = data.allitmescode;
	// 				//arrayData = jeson;
	// 				//autocomplete(document.getElementById("opt_two_sku"), arrayData);
	// 			} else {
	// 				//opt2_items_json = '';
	// 				//jeson = '';
	// 			}
	// 		}
	// 	});
	// });

	$(document).ready(function() {

		$('#Country [value="US"]').attr('selected', 'true');
			setTimeout(
          		function(){ 
          			$("#Country").trigger('change');
          			}, 3000);
			
		$("#state").children('option:gt(0)').hide();

		$("#Country").change(function() {
		    	var selectedoption = $(this).find('option:selected').val();
		    	$('#ContryLable').val($(this).find("option:selected").text());
		    	showstateoption(selectedoption)
		    }).trigger('change');

		    $("#state").children('option:gt(0)').hide();
		    $("#state").change(function() {
		    	$('#StateLable').val($(this).find("option:selected").text())
		     })
		});
		function showstateoption(selectedoption){
		$('#state option[value=""]').prop('selected', true);
		$("#state").children('option').hide();
		if($("#state").children('option[contry-code^="'+selectedoption+'"]').length > 0)
		{
			$("#state").children('option[contry-code^="'+selectedoption+'"]').show();	
		}else{
			$('#state option[value=""]').prop('selected', true);
			$("#state").children('option[contry-code^="selected"]').show();
			
		}
		

	}
      var changeText = "<?php echo __('Please Wait...') ?>";
	  var changeSubmit = "<?php echo __('Submit') ?>";
      var findButton = $('#customer-edit-address-validate').find('button[type=submit]'),
                form = $('#customer-edit-address-validate');
            form.submit(function (e) {
                if (form.validation('isValid')) {
                  var url = form.attr('action');
                  var formData = getFormData($(this));
                  var getalloptions = $("#shippingaddress>option");
                  var valIsExists = false;
                         $(getalloptions).each(function() {
	                     	if ($.trim($(this).attr("attr-cardname")).toLowerCase() == $.trim(formData.fullname).toLowerCase()) 
				            {
				            	valIsExists = true;
				            }
				        });
	                    if(valIsExists)
	                    {
	                    	showResponse('',"It seems like this address was previously added and saved. If you'd like to add it anyway please change the name in the 'Full Name' field to differ from the one you already added.",'false');
		                    return false;
	                    }
	              findButton.text(changeText);
                  findButton.attr("disabled", "disabled");
                    e.preventDefault();
                    $.ajax({
                      type: "POST",
                      url: url,
                      showLoader: true,
                      data: formData,
                      success: function(data) {
                      	  
                          if(data.error) {
                          	showResponse(data,'','false');
                            findButton.text(changeSubmit);
                            findButton.removeAttr('disabled');
                          } else {
                            showResponse(data,'','true');
                            setTimeout(function(){ location.reload(); }, 3000);                            
                          }
                      }
                  });
                }
            });

            function getFormData(formElem){
                var unindexed_array = formElem.serializeArray();
                var indexed_array = {};

                jQuery.map(unindexed_array, function(n, i){
                    indexed_array[n['name']] = n['value'];
                });

                return indexed_array;
            }

           function showResponse(data,Errordata,close) {
              if(data.error || Errordata) {
              	if(Errordata != '')
              	{
              		var error = Errordata;
              	}else{
              		var error = data.error;
              	}
                $('.block-customer-edit-address .response-msg').html("<div class='error'>"+error+"</div>");
              } else {
                $('.block-customer-edit-address .response-msg').html("<div class='success'>"+data.success+"</div>");
              }
              if(close == 'true')
              {
              		  setTimeout(
              		function(){ 
              			$('.response-msg').html(null); 
              			$(".mfp-close-inside").trigger("click");
              			 var findButton = $('#customer-edit-address-validate').find('button[type=submit]');
              			     findButton.text('Submit');
                    		findButton.removeAttr('disabled');
                    		
	          		}, 5000);
              }
            
            }
            
      });

  </script>
<?php

}
else if($data['type'] != 'server')
{
	echo $data['message'];
}
?>