<script>
require(['functions'],function($, owlCarousel){
    (function($) {
        $(document).ready( function(){
	if( $(".prodSlider").length > 0) {
		$('.prodSlider').owlCarousel({
			 loop:true
			,autoplay:true
			,autoplayTimeout:3000
			,smartSpeed:1200
			,margin:20
			,nav:false
			,dots:false
			,responsive:{
				0:{
					items:1
				},
				600:{
					items:3
				},
				1000:{
					items:5
				}
			}
		})
	}
	
	if( $(".langSelect").length > 0) {
		$('.langSelect').customSelect();
	}
	
});
    })(jQuery);
});
</script>