<?php
$helper = $this->helper('Sttl\Feature\Helper\Data');
$params = $this->getRequest()->getParams();
?>
<div class="search">
    <form id="search_feature_form" action="" method="get">
        <div class="fields">
            <div class="control">
                <input id="search_feature"
                       type="text"
                       name="keyword"
                       value="<?php if (isset($params['keyword'])) {
                           echo $params['keyword'];
                       } ?>"
                       placeholder="<?php echo __('Search feature here...'); ?>"
                       class="input-text"
                       autocomplete="off"/>
                <?php if (isset($params['char']) && $params['char'] != ''): ?>
                    <input id="search_feature_by_char"
                           type="hidden"
                           name="char"
                           value="<?php echo $params['char']; ?>"/>
                <?php endif; ?>
            </div>
        </div>
        <div class="actions">
            <button type="submit"
                    title="<?php echo $block->escapeHtml(__('Search')) ?>"
                    class="action search">
                <span><?php echo __('Search'); ?></span>
            </button>
            <?php if (isset($params['keyword']) || isset($params['char'])): ?>
                <button type="button"
                        onclick="window.location.href='<?php echo $helper->getFeatureUrl(); ?>'"
                        title="<?php echo $block->escapeHtml(__('Reset Filter')) ?>"
                        class="action search">
                    <span><?php echo __('Reset Filter'); ?></span>
                </button>
            <?php endif; ?>
        </div>
    </form>
</div>