<?php
/**
* Displays the payment form for orders created in adminhtml.
*
* @author      Century Business Solutions <support@centurybizsolutions.com>
* @copyright   Copyright (c) 2016 Century Business Solutions  (www.centurybizsolutions.com)
*/
$clientKey = $block->escapeHtml($block->getClientKey());
$requestCCAdmin = $block->getRequestCardCodeAdmin();

$savePayment = $block->getPaymentSavePayment();

$saveCardEnabled = $block->saveCardEnabled();

$deleteUrl = $block->getDeleteUrl();

$savedCardsCount = count($block->getSavedCards());

if ($saveCardEnabled || 1)
{
	//$savedCards = $block->getSavedCards();
	
	if ($savedCardsCount == 1 )
	{
		$savedCards[] = $block->getSavedCards();
	} else {
		$savedCards = $block->getSavedCards();
	}
	
//echo "<pre>";
//print_r($savedCards);
////print_r($requestCCAdmin); // admin cvv 1 or 0
////print_r($savePayment); // admin save payment method 1 or 0
//print_r($savedCardsCount);
//print_r('enabled');
//echo "</pre>";
//exit;
	
}
else
{
	$savedCards = [];
}

$wpData = [
    "clientKey" => $clientKey,
];

$serializedFormData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($wpData);
$_code = $block->getMethodCode();
$useVault = $block->hasToken();

?>

<input id="<?php echo $_code; ?>_payment_method" type="hidden" name="payment[method]" value="<?php echo $_code; ?>" />
<div id="payment_form_<?php echo $_code; ?>" class="admin__page-section-item" style="display:none;" data-mage-init='{"ebizcharge":<?php echo $serializedFormData; ?>}'>

	<?php if ($useVault) { ?>

		<fieldset class="admin__fieldset">
			
			<?php 
			//if (count($savedCards) == 1 )
			if ($savedCards)
			{ 		
			?>

				<div class="admin__field">
					<div class="admin__field-control control">
						<input type="hidden" name="payment[paymentToken]" id="payment_token" value="1" />
						<input type="hidden" name="payment[ebzc_cust_id]" value="<?php echo $block->getEbzcCustId(); ?>" />

						<input type="radio" class="ebzc_option" id="ebzc_option_saved" name="payment[ebzc_option]" value="saved" class="" disabled="" />		
						<label class="admin__field-label" for="ebzc_option_saved"><?php echo __('Select saved card'); ?></label>				
						
							<div class="admin__field-option show_saved_selected _required">

								<select id="<?php echo $_code; ?>_cc_token" name="payment[ebzc_method_id]" class="select admin__control-select saved_tokens required-entry">
									
									<?php
									$counter = 0;
									foreach ($savedCards as $savedCard) 
									{
									$savedCardnew = get_object_vars($savedCard);
									$counter = $counter + 1; 
									?>
									<option value="<?php echo $savedCardnew['MethodID']; ?>" <?php if (($savedCardnew['SecondarySort'] == 0 ) && ($counter == 1)) { echo 'selected="selected"' ; } ?><?php //echo $savedCardnew['SecondarySort'] ? 'selected="selected"' : ''; ?>>
									<?php echo $savedCardnew['MethodName']; ?>
									</option>
									<?php 
									} 
									?>
									
								</select>

							</div>

							<?php if ($requestCCAdmin): ?>

								<div class="admin__field-option show_saved_selected _required">
									<label class="label admin__field-label" for="<?php echo $_code; ?>_cc_cid"><span class="required"><?php echo __('CVV'); ?></span></label>
									<div class="admin__field-control control">
										<input type="text" id="<?php echo $_code; ?>_cc_cid" name="payment[cc_cid]" title="<?php echo __('Card Verification Number'); ?>" class="input-text admin__control-text validate-cc-cvn required-entry" value="" style="max-width: 100%; min-width: 8.5rem; width: auto;" />
									</div>
								</div>

							<?php endif; ?>

					</div>
				</div>
			
				<div class="admin__field">
					<div class="admin__field-control control">
						<input type="hidden" name="payment[paymentToken]" id="payment_token" value="1" />
						<input type="hidden" name="payment[ebzc_cust_id]" value="<?php echo $block->getEbzcCustId(); ?>" id="<?php echo $_code; ?>_cust_id" />
						<input type="hidden" name="<?php echo $_code; ?>_delete_url" value="<?php echo $deleteUrl . "ebizcharge/cards/inlineaction"; ?>" id="<?php echo $_code; ?>_delete_url" />				

							<input type="radio" class="ebzc_option" id="ebzc_option_update" name="payment[ebzc_option]" value="update" class="" disabled="" />		
							<label class="admin__field-label" for="ebzc_option_update"><?php echo __('Update saved card'); ?></label>				

							<div class="admin__field-option show_update_selected _required">

								<select id="<?php echo $_code; ?>_cc_token_update" name="payment[ebzc_method_id]" class="select admin__control-select saved_tokens_update required-entry">
									
									<?php 
									$counter = 0;
									foreach ($savedCards as $savedCard)
									{
										$savedCardnew = get_object_vars($savedCard);
										$counter = $counter + 1;
									?>
									
									<option value="<?php echo $savedCardnew['MethodID']; ?>" <?php if (($savedCardnew['SecondarySort'] == 0 ) && ($counter == 1)) { echo 'selected="selected"' ; } ?><?php //echo $savedCardnew['SecondarySort'] ? 'selected="selected"' : ''; ?>>
									<?php echo $savedCardnew['MethodName']; ?>
									</option>
									
									<?php } ?>
								
								</select>

							</div>

							<?php /*?><div class="admin__field-option show_update_selected _required">
				                <button type="button" class="button" value="delete" id="delete-payment">
				                    <span>Delete Payment Method</span>
				                </button>
			                </div><?php */?>
							
							<div id="<?php echo $_code; ?>_cc_type_exp_div" class="admin__field-option show_update_selected _required">
								<label class="label admin__field-label" for="<?php echo $_code; ?>_expiration_new" ><span class="required"><?php echo __('Expiration Date'); ?></span></label>
								<div class="admin__field-control control">
									
									<select id="<?php echo $_code; ?>_expiration_update" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry select admin__control-select">
									<?php $_ccExpMonth = $block->getInfoData('cc_exp_month'); ?>
									
									<?php foreach ($block->getCcMonths() as $k => $v): ?>
										
										<option value="<?php echo $k ? $k : ''; ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif; ?>><?php echo $v; ?></option>
									
									<?php endforeach; ?>
									</select>
									
									<?php $_ccExpYear = $block->getInfoData('cc_exp_year'); ?>
									
									<select id="<?php echo $_code; ?>_expiration_yr_update" name="payment[cc_exp_year]" class="year required-entry select admin__control-select">
									
									<?php foreach ($block->getCcYears() as $k => $v): ?>
										
										<option value="<?php echo $k ? $k : ''; ?>"<?php if ($k == $_ccExpYear): ?> selected="selected"<?php endif; ?>><?php echo $v; ?></option>
									
									<?php endforeach; ?>
									</select>

								</div>
							</div>

							<div class="admin__field-option show_update_selected _required">
								<label class="label admin__field-label" for="<?php echo $_code; ?>_avs_street"><span class="required"><?php echo __('AVS Street'); ?></span></label>
								<div class="admin__field-control control">
									<input type="text" id="<?php echo $_code; ?>_avs_street" name="payment[ebzc_avs_street]" title="<?php echo __('AVS Street'); ?>" class="input-text admin__control-text required-entry" value="" />
								</div>
							</div>

							<div class="admin__field-option show_update_selected _required">
								<label class="label admin__field-label" for="<?php echo $_code; ?>_avs_zip"><span class="required"><?php echo __('AVS Zip'); ?></span></label>
								<div class="admin__field-control control">
									<input type="text" id="<?php echo $_code; ?>_avs_zip" name="payment[ebzc_avs_zip]" title="<?php echo __('AVS Zip'); ?>" class="input-text admin__control-text required-entry" value="" />
								</div>
							</div>

							<?php if ($requestCCAdmin): ?>

								<div class="admin__field-option show_update_selected _required">
									<label class="label admin__field-label" for="<?php echo $_code; ?>_cc_cid_update"><span class="required"><?php echo __('CVV'); ?></span></label>
									<div class="admin__field-control control">
										<input type="text" id="<?php echo $_code; ?>_cc_cid_update" name="payment[cc_cid]" title="<?php echo __('Card Verification Number'); ?>" class="input-text admin__control-text validate-cc-cvn required-entry" value="" style="max-width: 100%; min-width: 8.5rem; width: auto;" />
									</div>
								</div>

							<?php endif; ?>

					</div>
				</div>

			<?php } ?>

			<div class="admin__field">
				<div class="admin__field-control control">

					<div class="admin__field-control control">
						<input type="radio" class="ebzc_option" id="ebzc_option_new" name="payment[ebzc_option]" value="new" class="" disabled="" />
						<label class="admin__field-label" for="ebzc_option_new"><?php echo __('Add new payment method'); ?></label>
						<input type="hidden" name="payment[cc_last4]" id="cc_last4" value="" />
					</div>

					<div class="admin__field-option show_new_selected _required">
						<label class="label admin__field-label" for="<?php echo $_code; ?>_cc_owner_new"><span class="required"><?php echo __('Name on Card'); ?></span></label>
						<div class="admin__field-control control">
							<input type="text" id="<?php echo $_code; ?>_cc_owner_new" name="payment[cc_owner]" title="<?php echo __('Name on Card'); ?>" class="input-text admin__control-text validate-cc-owner required-entry" value="" />
						</div>
					</div>

					<div class="admin__field-option show_new_selected _required">
						<label class=" label admin__field-label" for="<?php echo $_code; ?>_cc_type_new" ><span class="required"><?php echo __('Credit Card Type'); ?></span></label>
						<div class="admin__field-control control">
							
							<select id="<?php echo $_code; ?>_cc_type_new" name="payment[cc_type]" class="required-entry select admin__control-select validate-cc-type-select">
								
								<option value="">--<?php echo __('Please Select'); ?>--</option>
								
								<?php $_ccType = $block->getInfoData('cc_type'); ?>
								<?php foreach ($block->getCcAvailableTypes() as $_typeCode => $_typeName): ?>

									<option value="<?php echo $_typeCode; ?>"<?php if ($_typeCode == $_ccType): ?> selected="selected"<?php endif; ?>><?php echo $_typeName; ?></option>

								<?php endforeach ?>

							</select>

						</div>
					</div>

					<div class="admin__field-option show_new_selected _required">
						<label class="label admin__field-label" for="<?php echo $_code; ?>_cc_number_new"><span class="required"><?php echo __('Credit Card Number'); ?></span></label>
						<div class="admin__field-control control">
							<input type="text" id="<?php echo $_code; ?>_cc_number_new" name="payment[cc_number]" title="<?php echo __('Credit Card Number'); ?>" class="input-text admin__control-text validate-cc-number validate-cc-type required-entry" value="" />
						</div>
					</div>
					
					<div id="<?php echo $_code; ?>_cc_type_exp_div" class="admin__field-option show_new_selected _required">
						<label class="label admin__field-label" for="<?php echo $_code; ?>_expiration_new" ><span class="required"><?php echo __('Expiration Date'); ?></span></label>
						<div class="admin__field-control control">
							
							<select id="<?php echo $_code; ?>_expiration_new" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry select admin__control-select">
							<?php $_ccExpMonth = $block->getInfoData('cc_exp_month'); ?>
							
							<?php foreach ($block->getCcMonths() as $k => $v): ?>
								
								<option value="<?php echo $k ? $k : ''; ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif; ?>><?php echo $v; ?></option>
							
							<?php endforeach; ?>
							</select>
							
							<?php $_ccExpYear = $block->getInfoData('cc_exp_year'); ?>
							
							<select id="<?php echo $_code; ?>_expiration_yr_new" name="payment[cc_exp_year]" class="year required-entry select admin__control-select">
							
							<?php foreach ($block->getCcYears() as $k => $v): ?>
								
								<option value="<?php echo $k ? $k : ''; ?>"<?php if ($k == $_ccExpYear): ?> selected="selected"<?php endif; ?>><?php echo $v; ?></option>
							
							<?php endforeach; ?>
							</select>

						</div>
					</div>

					<?php if ($requestCCAdmin): ?>

						<div class="admin__field-option show_new_selected _required">
							<label class="label admin__field-label" for="<?php echo $_code; ?>_cc_cid_new"><span class="required"><?php echo __('CVV'); ?></span></label>
							<div class="admin__field-control control">
								<input type="text" id="<?php echo $_code; ?>_cc_cid_new" name="payment[cc_cid]" title="<?php echo __('Card Verification Number'); ?>" class="input-text admin__control-text validate-cc-cvn required-entry" value="" style="max-width: 100%; min-width: 8.5rem; width: auto;" />
							</div>
						</div>

					<?php endif; ?>

					<?php if (!$savePayment): ?>

						<div class="admin__field-option show_new_selected _required">
			                <input type="checkbox" checked="checked" name="payment[ebzc_save_payment]" id="<?php echo $_code; ?>_save_payment"  title="<?php echo __('Save My Credit Card Info'); ?>" value="1" />
			                <label for="<?php echo $_code; ?>_save_payment" class="label">
			                    <span><?php echo __('Save this credit card information.'); ?></span>
			                </label>
		                </div>

		            <?php else: ?>

		            	<div class="admin__field-option show_new_selected _required">
			                <input type="hidden" checked="checked" name="payment[ebzc_save_payment]" id="<?php echo $_code; ?>_save_payment"  title="<?php echo __('Save My Credit Card Info'); ?>" value="1" />
		                </div>

		            <?php endif; ?>

				</div>
			</div>

		</fieldset>

	<?php } else { ?>

		<fieldset class="admin__fieldset">
			<div class="admin__field">

				<div class="admin__field-control control">
					<input type="hidden" name="payment[paymentToken]" id="payment_token" value="0" />
					<input type="hidden" name="payment[ebzc_cust_id]" value="<?php echo $block->getEbzcCustId(); ?>" />
					<input type="hidden" name="payment[cc_last4]" id="cc_last4" value="" />
					<input type="hidden" id="ebzc_option_new" name="payment[ebzc_option]" value="new" />
				</div>

				<div class="admin__field-control control">
					
					<div class="admin__field-option show_new_selected _required">
						<label class="label admin__field-label" for="<?php echo $_code; ?>_cc_owner"><span class="required"><?php echo __('Name on Card'); ?></span></label>
						<div class="admin__field-control control">
							<input type="text" id="<?php echo $_code; ?>_cc_owner" name="payment[cc_owner]" title="<?php echo __('Name on Card'); ?>" class="input-text admin__control-text validate-cc-owner required-entry" value="" />
						</div>
					</div>

					<div class="admin__field-option show_new_selected _required">
						<label class=" label admin__field-label" for="<?php echo $_code; ?>_cc_type" ><span class="required"><?php echo __('Credit Card Type'); ?></span></label>
						<div class="admin__field-control control">
							
							<select id="<?php echo $_code; ?>_cc_type" name="payment[cc_type]" class="required-entry select admin__control-select validate-cc-type-select">
								
								<option value="">--<?php echo __('Please Select'); ?>--</option>

							<?php $_ccType = $block->getInfoData('cc_type'); ?>
							
							<?php foreach ($block->getCcAvailableTypes() as $_typeCode => $_typeName): ?>

								<option value="<?php echo $_typeCode; ?>"<?php if ($_typeCode == $_ccType): ?> selected="selected"<?php endif; ?>><?php echo $_typeName; ?></option>

							<?php endforeach ?>

							</select>

						</div>
					</div>

					<div class="admin__field-option show_new_selected _required">
						<label class="label admin__field-label" for="<?php echo $_code; ?>_cc_number"><span class="required"><?php echo __('Credit Card Number'); ?></span></label>
						<div class="admin__field-control control">
							<input type="text" id="<?php echo $_code; ?>_cc_number" name="payment[cc_number]" title="<?php echo __('Credit Card Number'); ?>" class="input-text admin__control-text validate-cc-number validate-cc-type" value="" />
						</div>
					</div>
					
					<div id="<?php echo $_code; ?>_cc_type_exp_div" class="admin__field-option show_new_selected _required">
						<label class="label admin__field-label" for="<?php echo $_code; ?>_expiration" ><span class="required"><?php echo __('Expiration Date'); ?></span></label>
						<div class="admin__field-control control">
							
							<select id="<?php echo $_code; ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry select admin__control-select">

							<?php $_ccExpMonth = $block->getInfoData('cc_exp_month'); ?>

							<?php foreach ($block->getCcMonths() as $k => $v): ?>

								<option value="<?php echo $k ? $k : ''; ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif; ?>><?php echo $v; ?></option>
							
							<?php endforeach ?>

							</select>

							<?php $_ccExpYear = $block->getInfoData('cc_exp_year'); ?>

							<select id="<?php echo $_code; ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry select admin__control-select">
							
							<?php foreach ($block->getCcYears() as $k=>$v): ?>
								
								<option value="<?php echo $k ? $k : ''; ?>"<?php if($k == $_ccExpYear): ?> selected="selected"<?php endif; ?>><?php echo $v; ?></option>
							
							<?php endforeach ?>

							</select>

						</div>
					</div>

					<?php if ($requestCCAdmin): ?>

						<div class="admin__field-option show_new_selected _required">
							<label class="label admin__field-label" for="<?php echo $_code; ?>_cc_cid"><span class="required"><?php echo __('CVV'); ?></span></label>
							<div class="admin__field-control control">
								<input type="text" id="<?php echo $_code; ?>_cc_cid" name="payment[cc_cid]" title="<?php echo __('Card Verification Number'); ?>" class="input-text admin__control-text validate-cc-cvn required-entry" value="" style="max-width: 100%; min-width: 8.5rem; width: auto;" />
							</div>
						</div>

					<?php endif; ?>

				</div>

			</div>
		</fieldset>
	
	<?php } ?>

</div>