<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list template
 *
 * @var $block \Magefan\Blog\Block\Post\PostList
 */
?>
<?php
$_postCollection = $block->getPostCollection();
?>
<div class="blog-widget-recent blog-widget-recent-masonry tab-pane fade" id="press" role="tabpanel" aria-labelledby="profile-tab">

<?php if (!$_postCollection->count()): ?>
    <div class="message info empty"><div><?php echo __('We can\'t find posts matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getAdditionalHtml() ?>
    <div class="post-list-wrappercustom blogAndPressWrap">
        <?php $iterator = 1; ?>
        <ol class="post-listcustom">
            <?php foreach ($_postCollection as $_post): ?>
                <?php echo $block->getPostHtml($_post) ?>
            <?php endforeach; ?>
            <span class="hidden"></span>
        </ol>
    </div>

    <?php echo $block->getToolbarHtml() ?>
    <?php echo $this->getChildHtml('addthisJsCustom'); ?>
<?php endif; ?>
</div>
