<div class="container">
<div class="row">
<div class="col-md-12 mediaPage">
<h2 class="center">Adar Media Room</h2>
<div class="mediaPageWrap">
<ul id="mediaTab" class="nav nav-tabs">
<li class="nav-item"><a id="blog-tab" class="nav-link active" href="#blog" data-toggle="tab">Blog</a></li>
<li class="nav-item"><a id="press-tab" class="nav-link" href="#press" data-toggle="tab">Press</a></li>
<li class="nav-item"><a id="gallery-tab" class="nav-link" href="#gallery" data-toggle="tab">Gallery</a></li>
</ul>
<div id="myTabContent" class="tab-content">
<div id="gallery" class="tab-pane fade">
<div class="row">
<div class="col-md-12">
"haresh"


</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>