<script>
    require(["jquery", 'underscore', 'Magento_Ui/js/modal/modal'], function($, _, modal) { 

        //  $(document).ready(function() {
        //     var documentPadding = 30;
        //     var firstAttempt = true;
        //     var lastHeight = 0, curHeight = 0;
        //     var parentBody = window.parent.document.body;
        //     $('.mfp-preloader', parentBody).css('display', 'none');          
        //     $('.reviews-actions a').attr('target', '_parent');
        //     $('.product-social-links a').attr('target', '_parent');          
        //     setInterval(function(){
        //         if (firstAttempt) {
        //             curHeight =  $('.page-wrapper').outerHeight(true) + documentPadding;
        //         } else {
        //             curHeight =  $('.page-wrapper').outerHeight(true) ;
        //         }                
        //         documentHeight =  curHeight + "px";
        //         if ( curHeight != lastHeight ) {
        //             $('.mfp-inline-holder .mfp-content', parentBody).animate({
        //                 'height': documentHeight
        //             }, 500);
        //             lastHeight = curHeight;
        //             firstAttempt = false;
        //         }
        //     }, 500);
        // });


        $(document).on('ajaxComplete', function(event, xhr, settings) {
            var parentBody = window.parent.document.body;
            var cartMessage = false;
            console.log(window.weltpixel_quickview);
            var closeSeconds = parseInt(window.weltpixel_quickview.closeSeconds);
            var showShoppingCheckoutButtons = parseInt(window.weltpixel_quickview.showShoppingCheckoutButtons);
            if (settings.type.match(/get/i) && _.isObject(xhr.responseJSON)) {
                var result = xhr.responseJSON;
                if (_.isObject(result.messages)) {
                    var messageLength = result.messages.messages.length;
                    var message = result.messages.messages[0];
                    if (messageLength && message.type == 'success') {
                        cartMessage = message.text;
                    }
                }
                if (_.isObject(result.cart) && _.isObject(result.messages)) {
                    var messageLength = result.messages.messages.length;
                    var message = result.messages.messages[0];
                    if (messageLength && message.type == 'success') {
                        cartMessage = message.text;
                    }
                }
                if (cartMessage) {
                    window.parent.weltpixel_quickview.showMiniCartFlag = true;
                }
                if (showShoppingCheckoutButtons && cartMessage) {
                    $('<div />').html('').modal({
                        title: cartMessage,
                        autoOpen: true,
                        buttons: [{
                            text: $.mage.__('Continue Shopping'),
                            attr: {
                                'data-action': 'confirm'
                            },
                            'class': 'action primary',
                            click: function() {
                                this.closeModal();
                                $('.mfp-close', parentBody).trigger('click');
                            }
                        }, {
                            text: $.mage.__('Go To Checkout'),
                            attr: {
                                'data-action': 'cancel'
                            },
                            'class': 'action primary',
                            click: function() {
                                parent.window.location = '<?php echo $block->getUrl('checkout', ['_secure' => true]); ?>'
                            }
                        }]
                    });
                }
                if (closeSeconds && cartMessage) {
                    setTimeout(function() {
                        $('.mfp-close', parentBody).trigger('click');
                    }, closeSeconds * 1000);
                }
            }
        });
    });
</script> <?php $_helper = $this->helper('WeltPixel\Quickview\Helper\Data');
            $customCss = $_helper->getCustomCSS(); ?> <?php if (strlen($customCss)) : ?> <style>
        <?php echo $customCss; ?>
    </style> <?php endif; ?>