<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\TaxImportExport\Block\Adminhtml\Rate\ImportExport */
?>
<div class="import-export-tax-rates">
    <?php if (!$block->getIsReadonly()) :?>
    <div class="import-tax-rates">
        <?php if ($block->getUseContainer()) :?>
        <form id="import-form"
              class="admin__fieldset"
              action="<?= $block->escapeUrl($block->getUrl('childskus/example_excel/index')) ?>"
              method="post"
              enctype="multipart/form-data">
        <?php endif; ?>
            <?= $block->getBlockHtml('formkey') ?>
            <div class="fieldset admin__field">
                <label for="import_rates_file" class="admin__field-label"><span><?= $block->escapeHtml(__('Excel File')) ?></span></label>
                <div class="admin__field-control">
                    <input type="file"
                           id="import_rates_file"
                           name="import_rates_file"
                           class="input-file required-entry"/>
                    <?= $block->getButtonHtml(__('Import'), '', 'import-submit') ?>
                    <span style="display: block; font-size: 10px;">Only xlsx file formate allowed..</span>
                </div>
            </div>
        <?php if ($block->getUseContainer()) :?>
        </form>
        <?php endif; ?>
        <script>
require(['jquery', 'Magento_Ui/js/modal/alert', "mage/mage", "loadingPopup", 'mage/translate'], function(jQuery, uiAlert){

    jQuery('#import-form').mage('form').mage('validation');
    (function ($) {
        $('.import-submit').click(function(){
            if($(':input[name="import_rates_file"]').val()) {
                $('body').loadingPopup({
                    timeout: false
                });

                $(this.form).submit();
            } else {
                uiAlert({
                    content: $.mage.__('Please select a file to import!')
                });
            }
        });
    })(jQuery);

});
</script>
    </div>
    <?php endif; ?>
</div>
