<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
// $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
// $catId = $category ? $category->getId() : null ;
?>
<?php
    // echo $this->getLayout()
    //       ->createBlock('Magento\Cms\Block\Block')
    //       ->setBlockId('Addition')
    //       ->toHtml();
     // $cid = 9;
     // $c = $objectManager->create('Magento\Catalog\Model\Category')->load();
     // echo $c->getResource()->getAttribute('logoimage')->getFrontend()->getValue($c);die;
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items test">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): 
                    // $proCats = $_product->getCategoryIds();    
                    // $catIds= array_merge([], $proCats); 
                    // var_dump($catIds);
            	  // if(@$catId === '86'){

               //          $blocks = $this->getLayout()->getBlock('category.product.type.details.renderers.configurable');
               //          echo $blocks->setProduct($_product)->toHtml();
               //      }

                ?> 


                <?php //echo "<pre>";print_R($_product->getData());exit;?>
                <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php $tag =  $_product->getResource()->getAttribute('is_new')->getFrontend()->getValue($_product);
                        if($tag == 'Yes'){?>                            
                        <div class="magento_tag new">
                              <span class="new-lable">
                                    <?php echo __('New'); ?>           
                                </span>
                        </div>
                    <?php } ?>
                  <?php 
                  $productImage = $block->getImage($_product, $image);
                  /*
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php
                    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                    $product = $objectManager->get('Magento\Catalog\Model\Product')->load($_product->getId());
                    if($product->getMainproductimage())
                    {
                        $imagesArray = explode(",",$product->getMainproductimage());
                        ?>
                        <span class="product-image-container">
                            <span class="product-image-wrapper">
                                <img class="product-image-photo"
                                <?= $block->getCustomAttributes() ?>
                                src="<?= $imagesArray[0] ?>"
                                alt="<?= $block->stripTags($block->getLabel(), null, true) ?>"/>
                                <img class="product-image-photo product-hove-image" src="<?php echo $imagesArray[1]; ?>"/>
                                </span>
                        </span>

                    <?php }else{
                    ?>
                        <?= $productImage->toHtml() ?>
                      <?php }?> 
                        
                    </a>
                    <?php */ ?>
                    <?= $productImage->toHtml() ?>
                     <span class="color-date">
                                        <?php 
                                            if($_product->getTypeId() == 'configurable'){
                                                
                                            $date_available = $_product->getResource()->getAttribute('overlay_text')->getFrontend()->getValue($_product);
                                            if($date_available){
                                                // $specntdate = date("M d, Y", strtotime($date_available . ' +1 day')); 
                                                echo $date_available;
                                                }
                                            } 
                                            ?>
                                      </span>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <?php $collcationValue =  $_product->getResource()->getAttribute('collecttion')->getFrontend()->getValue($_product); ?>

                    <div class="show-product-dis-box">
                        <div class="dis-set">                           
                             <!-- <span><span class="<?php echo strtolower(str_replace(' ', '_', $collcationValue)); ?>"><?php echo $collcationValue; ?></span> collection </span> -->
                                <?php 
                                    if($collcationValue){
                                        // echo "aaa";
                                        // echo "$collcationValue";die;
                                        $logoimage = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId(strtolower(str_replace(' ', '_', $collcationValue)).'_product')->toHtml();
                                        $d_flex = $logoimage != '' ? 'd-flex' :'';
                                    }
                                ?>

                                 
                            
                            <div class="category-products-info <?= $d_flex ?>">
                                <?php if($logoimage != '' ){ ?>
                                    <div class="<?php echo strtolower(str_replace(' ', '_', $collcationValue)); ?> product-logo"><?= $logoimage?></div> 
                                <?php }else{ ?>
                                      <span><?php echo $collcationValue; ?> collection </span>
                                <?php } ?>
                                    <div class="show-product-dis-box-more">
                                        <span><lable>Style:</lable></span>
                                        <span><?php echo $_product->getSku();?></span>
                                    </div>
                            </div>
                        </div>
                          <?php
                        $_children = ''; 
                        $_children = $_product->getTypeInstance()->getUsedProducts($_product);
                        $colorarr = array();                    
                        foreach ($_children as $child){
                            $colorarr[$child->getColor()] = $child->getColor();
                        }
                        if(count($colorarr) > 0) {
                            $count_color = count($colorarr); 
                            if($count_color == 1)
                            {?> 
                                <span class="color-total"><?php echo  '('.$count_color. ' color)'; ?></span>
                              <?php
                            }else{
                                ?>
                            <span class="color-total"><?php echo  '('.$count_color. ' colors)'; ?></span>
                    <?php  }
                    } ?>
                    </div>

                        <!--<?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>-->
                        <?= $block->getProductDetailsHtml($_product) ?>
                        <?php
                        //echo $this->getRequest()->getParams('q');
                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
                        $store_base_url = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);

                        /*Welpixel_QuickView Start*/
                        $scopconfig = $objectManager->get('\Magento\Framework\App\Config\ScopeConfigInterface');
                        $isEnabled = $scopconfig->getValue('weltpixel_quickview/general/enable_product_listing',  \Magento\Store\Model\ScopeInterface::SCOPE_STORE);

                        if($isEnabled){
                            $buttonStyle =  'weltpixel_quickview_button_' . $scopconfig->getValue('weltpixel_quickview/general/button_style',  \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
                        ?>
                            <a class="weltpixel-quickview <?php echo $buttonStyle;?>" data-quickview-url="<?php echo $store_base_url;?>weltpixel_quickview/catalog_product/view/id/<?php echo $_product->getId();?>/" href="#quickView-popup"><div>Quick View</div><span></span></a>
                        <?php } 
                        /*Welpixel_QuickView End*/
                        ?>
                        <a class="weltpixel-quickview weltpixel_quickview_button_v2_alt searh-page" data-quickview-url="<?php echo $store_base_url;?>weltpixel_quickview/catalog_product/view/id/<?php echo $_product->getId();?>/" href="javascript:void(0);"><div>Quick View</div><span></span></a>

                        <!--<div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                       class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>-->
                    </div>
                </div>
                <?php

                  

                 ?>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
