<div class="modal fade" id="popupModal" tabindex="-1" data-keyboard="false" data-backdrop="static" role="dialog" aria-labelledby="loginModal" aria-hidden="true" style="z-index: 1400;">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body">
            <div class="container bg-primary p-2">
                <div class="row">
                    <div class="col-md-4 col-sm-4 place-an-order-back-button">
                        <div class="move movea">
                        <img src="<?=$this->getBaseUrl()?>/pub/media/wysiwyg/move.svg">
                    </div>
                    </div>
                    <div class="col-md-4 col-sm-4 text-center place-an-order-text">
                        Place an Order
                    </div>
                    <div class="col-md-2 col-sm-2"></div>
                    <div class="col-md-2 col-sm-2 close_popup" data-dismiss="modal" style="cursor:pointer !important;">
                        <button type="button" class="productview-modal-close-inside"><i class="fa fa-times"></i></button>
                    </div>
                    </div>
                </div>
                <div class="popup-animation">
                    <form class="form cart col-lg-12" action="<?php echo $this->getUrl() . 'adaruniforms/cart/add' ?>" id="cart-form" method="post" data-hasrequired="<?=$block->escapeHtmlAttr(__('* Required Fields')) ?>"data-mage-init='{"validation":{}}'>
                        <div class="modalContainer">
                            
                            <div class="container product-info">
                                
                            </div>
                        </div>
                    </form>
                    <div id="quickcheckoutcont" class="hide"></div>
                    <div id="quickcheckoutconfirmetion" class="hide"></div>
                </div>
                <div class="container bg-light p-2  bottomBtn">
                    <a href="#" class="opacity-down btn-primary float-right" id="chekout">
                        <strong>CHECKOUT</strong> : <span class="grandtotal">$0.00</span>
                            <input type="hidden" id="hi_grandtotal" name="hi_grandtotal" value="0.00">
                            <input type="hidden" id="activetab_id" name="activetab_id" value="">
                            <input type="hidden" id="chekouthidden" name="chekouthidden" value="">
                        </a>
                    <a id="quickcheckoutelink" class="opacity-down">1 CLICK CHECKOUT</a>
                    <button type="button" class="themeBtn quickcheckoutsubmit submitorder_sttl" style="display: none;">SUBMIT ORDER</button>
                    <button type="button" class="backbuttonclose" style="display: none;">Back</button>
                </div>                    
            </div>
            <div class="quickViewbodyloader" style="display: none">
                <div data-role="loader" class="loading-mask lezzy-popup" >
                    <div class="loader"> <img src="<?= $this->getViewFileUrl('') ?>/images/loader-1.gif" alt="Loading..."> </div>
                </div>
            </div>

        </div>
    </div>
</div>
<div id="posuccess-message" style="">
  <p></p>
</div>
<div class="modal-content quickViewCont imgquickViewCont" id="imgquickViewCont">
  <div class="container">
         <button type="button" class="mfp-close close-image-chart-popup"><i class="fa fa-times"></i></button>
       <img src="<?=$this->getBaseUrl()?>/pub/media/catalog/product/placeholder/default/image-placeholder.jpg" class="ProductShow"/>
  </div>
</div>
<?php if($block->isLoggedIn()):?>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Catalog/js/view/render_viewstockpopup": {
            "baseurl" : "<?= $block->getBaseUrl(); ?>",
            "poConfig" : <?= /* @noEscape */ $block->getPoSwatchConfig(); ?> ,
            "poCheck" : <?= /* @noEscape */ $block->getPoCheckConfig(); ?> ,
            "customersFlatDiscount" : <?= $block->getCustomersFlatDiscount(); ?>,
            "customersBulcDiscount" : <?= $block->getCustomersBulkDiscount(); ?>
        }
    }
}
</script>
<?php endif?>