<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$currentProduct = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$_product = $currentProduct;
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$images = $_product->getMediaGalleryImages();

$media_dir = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                    ->getStore()
                    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA)."catalog/product/placeholder/";
?>
<?php
    $first_image = '';
    if($images->count()>0)
    {

        ?>
        <div class="product-view-custom-media-">
            <div class="popup_magnify_icon" style="display:none;">
                  <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 396.819 396.819" style="enable-background:new 0 0 396.819 396.819;width: 20%;transform: rotate(270deg);" xml:space="preserve">
                    <g>
                        <g>
                            <path d="M352.103,44.679c-59.237-59.401-155.412-59.535-214.813-0.298c-57.316,57.157-59.741,149.218-5.515,209.314l-11.6,11.6
                                c-9.372-9.373-24.568-9.375-33.941-0.003c-0.001,0.001-0.002,0.002-0.003,0.003l-79.2,79.2
                                c-9.373,9.372-9.375,24.568-0.003,33.941c0.001,0.001,0.002,0.002,0.003,0.003l11.312,11.312c9.372,9.369,24.564,9.369,33.936,0
                                l79.2-79.2c9.373-9.372,9.375-24.568,0.003-33.941c-0.001-0.001-0.002-0.002-0.003-0.003l11.6-11.6
                                c62.24,56.247,158.292,51.388,214.539-10.851C411.948,194.037,409.521,101.856,352.103,44.679z M120.175,299.231l-79.2,79.2
                                c-3.124,3.123-8.188,3.123-11.312,0l-11.312-11.32c-3.118-3.123-3.118-8.181,0-11.304l79.2-79.2c3.164-3.025,8.148-3.025,11.312,0
                                l11.312,11.32C123.293,291.05,123.293,296.108,120.175,299.231z M340.799,248.327c-53.112,53.11-139.223,53.109-192.333-0.003
                                s-53.109-139.223,0.003-192.333c53.111-53.109,139.219-53.109,192.33,0C393.824,109.139,393.824,195.179,340.799,248.327z"></path>
                        </g>
                    </g>
                    <g>
                        <g>
                            <path d="M329.479,67.303L329.479,67.303l-11.312,11.312c40.545,40.644,40.545,106.436,0,147.08l11.312,11.312
                                C376.275,190.117,376.275,114.193,329.479,67.303z"></path>
                        </g>
                    </g>
                  </svg>
                </div>
                <div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
                    <div data-role="loader" class="loading-mask">
                        <div class="loader">
                            <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-2.gif') ?>"
                                 alt="<?= /* @escapeNotVerified */ __('Loading...') ?>">
                        </div>
                    </div>
                </div>

            <?php
            $i = 2;
            // echo count($images);
            // die;
            foreach($images as $child)
            {
                $productImage = $_imagehelper->init($_product, 'product_page_image_large')->setImageFile($child->getFile())->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(TRUE)->getUrl();
                $productImagedata = $_imagehelper->init($_product, 'product_page_image_large')
                ->setImageFile($child->getFile())->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(TRUE) ->getUrl();

				if($first_image == '')
				{
					$first_image = $productImage;
				}


                if($_product->getImage() != $child->getFile())
                {
                    $show = false;
                    if($i == 5)
                    {
                    ?>
                    <?php if($child->getMediaType() == "external-video") {
                        $show = true;
                    ?>
                        <div class="image-video">
                        <!--<div data-role="loader" >
                                <div class="loader-youtube" style="display: none">
                                    <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-2.gif') ?>"
                                         alt="<?= /* @escapeNotVerified */ __('Loading...') ?>">
                                </div>
                        </div>
							<div class="fotorama-video-container" style="position: relative;">
								<img class="image-7 image-video-youtube" src="<?php echo (isset($first_image) && $first_image != '') ? $first_image : $productImage; ?>" data-video="<?php echo $child->getVideoUrl(); ?>?autoplay=1&loop=1&playlist=Wktw43TG6_4" />
							</div>-->

                            <?php
                            $videos_em_code = explode("/",$child->getVideoUrl());
                            $playlist = '';
                            if(isset($videos_em_code[4]))
                            {
                                $playlist =$videos_em_code[4];
                            }
                            ?>
                            <iframe id="youtube-iframe" width="100%" height="778px" src="<?php echo $child->getVideoUrl(); ?>?autoplay=1&rel=0&loop=1&playlist=<?php echo $playlist ?>" allow="autoplay;"></iframe>
                        </div>
                    <?php }
                    if($show){$i = 4;}
                        if(empty($show)){
                        ?>
                        <div class="image-<?php echo $i;?>">

                                  <img data-id="smallthumbs-<?php echo $_product->getId();?>" data-img="<?php echo $productImagedata; ?>" src="<?php echo $productImage; ?>"/>

                             <!-- <img data-id="smallthumbs-<?php echo $_product->getId();?>" data-img="<?php echo $productImagedata; ?>" src="<?php echo $productImage; ?>"/> -->
                        </div>
                    <?php
                        }
                    }
                    else
                    {
                    ?>
                    <div class="image-<?php echo $i;?>">

                              <img data-id="smallthumbs-<?php echo $_product->getId();?>" data-img="<?php echo $productImagedata; ?>" src="<?php echo $productImage; ?>"/>

                         <!-- <img data-id="smallthumbs-<?php echo $_product->getId();?>" data-img="<?php echo $productImagedata; ?>" src="<?php echo $productImage; ?>"/> -->
                    </div>
                    <?php
                    }
                    ?>
                    <?php
                    $i++;
                }
            }
            ?>
        </div>
       <?php
    }
    else
    {
    ?>
        <div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
            <div data-role="loader" class="loading-mask">
                <div class="loader">
                    <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-2.gif') ?>"
                         alt="<?= /* @escapeNotVerified */ __('Loading...') ?>">
                </div>
            </div>
        </div>
    <?php
    }
?>
<script>
    /**require(["jquery"], function ($) {
        $(document).ready(function() {
            $('.fotorama-video-container').click(function(){
                $('.loader-youtube').show();
                video = '<iframe width="100%" height="745" src="'+ $('.image-video-youtube').attr('data-video') +'"></iframe>';
               $(this).replaceWith(video);
               $('.loader-youtube').hide();
             });
        });
    });

    require(["jquery"], function ($) {
        $(document).ready(function() {
            $("#youtube-iframe")[0].src += "&autoplay=1";
                ev.preventDefault();
        });
    });**/
</script>
<!--Fix for jumping content. Loader must be the same size as gallery.-->
<script>

    var config = {
            "width": <?= /* @escapeNotVerified */ $block->getImageAttribute('product_page_image_medium', 'width') ?>,
            "thumbheight": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_small', 'height')
                        ?: $block->getImageAttribute('product_page_image_small', 'width'); ?>,
            "navtype": "<?= /* @escapeNotVerified */ $block->getVar("gallery/navtype") ?>",
            "height": <?= /* @escapeNotVerified */ $block->getImageAttribute('product_page_image_medium', 'height') ?>
        },
        thumbBarHeight = 0,
        loader = document.querySelectorAll('[data-gallery-role="gallery-placeholder"] [data-role="loader"]')[0];

    if (config.navtype === 'horizontal') {
        thumbBarHeight = config.thumbheight;
    }

    loader.style.paddingBottom = ( config.height / config.width * 100) + "%";
</script>
<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @escapeNotVerified */ $block->getMagnifier() ?>,
                "data": <?= /* @escapeNotVerified */ $block->getGalleryImagesJson() ?>,
                "options": {
                    "nav": "thumbs",
                        "loop": "false",
                    <?php if (($block->getVar("gallery/keyboard"))): ?>
                        "Keyboard": "false",
                    <?php endif; ?>
                        "arrows": "false",
                    <?php if (($block->getVar("gallery/allowfullscreen"))): ?>
                        "allowfullscreen": <?= /* @escapeNotVerified */ $block->getVar("gallery/allowfullscreen") ?>,
                    <?php endif; ?>
                    <?php if (($block->getVar("gallery/caption"))): ?>
                        "showCaption": <?= /* @escapeNotVerified */ $block->getVar("gallery/caption") ?>,
                    <?php endif; ?>
                    "width": "<?= /* @escapeNotVerified */ $block->getImageAttribute('product_page_image_medium', 'width') ?>",
                    "thumbwidth": "<?= /* @escapeNotVerified */ $block->getImageAttribute('product_page_image_small', 'width') ?>",
                    <?php if ($block->getImageAttribute('product_page_image_small', 'height') || $block->getImageAttribute('product_page_image_small', 'width')): ?>
                        "thumbheight": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_small', 'height')
                        ?: $block->getImageAttribute('product_page_image_small', 'width'); ?>,
                    <?php endif; ?>
                    <?php if ($block->getImageAttribute('product_page_image_medium', 'height') || $block->getImageAttribute('product_page_image_medium', 'width')): ?>
                        "height": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_medium', 'height')
                        ?: $block->getImageAttribute('product_page_image_medium', 'width'); ?>,
                    <?php endif; ?>
                    <?php if ($block->getVar("gallery/transition/duration")): ?>
                        "transitionduration": <?= /* @escapeNotVerified */ $block->getVar("gallery/transition/duration") ?>,
                    <?php endif; ?>
                    "transition": "crossfade",
                    "navarrows": "false",
                    "navtype": "thumbs",
                    "navdir": "horizontal"
                },
                "fullscreen": {
                    "nav": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/nav") ?>",
                    <?php if ($block->getVar("gallery/fullscreen/loop")): ?>
                        "loop": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/loop") ?>,
                    <?php endif; ?>
                    "navdir": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/navdir") ?>",
                    <?php if ($block->getVar("gallery/transition/navarrows")): ?>
                        "navarrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/navarrows") ?>,
                    <?php endif; ?>
                    "navtype": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/navtype") ?>",
                    <?php if ($block->getVar("gallery/fullscreen/arrows")): ?>
                        "arrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/arrows") ?>,
                    <?php endif; ?>
                    <?php if ($block->getVar("gallery/fullscreen/caption")): ?>
                        "showCaption": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/caption") ?>,
                    <?php endif; ?>
                    <?php if ($block->getVar("gallery/fullscreen/transition/duration")): ?>
                        "transitionduration": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/transition/duration") ?>,
                    <?php endif; ?>
                    "transition": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/transition/effect") ?>"
                }
            }
        }
    }
</script>
