<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
    $_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
<div class="blog-widget-recent blog-widget-recent-masonry tab-pane fade" id="press" role="tabpanel" aria-labelledby="profile-tab">
	<div class="blogAndPressWrap">
			<?php foreach ($_postCollection as $_post) { ?>
				<?php
					$_postUrl = $_post->getPostUrl();
					$_postName = $block->escapeHtml($_post->getTitle(), null, true);
				?>
				<div class="blogAndPressRow cf post-holder-<?php echo $_post->getId() ?>">
					<?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
					<div class="blogImg">
						<img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
					</div>
					<?php } ?>
					<div class="blogDetails">
						<h3><?php echo $_postName; ?></h3>
						<?php if ($content = $block->getShorContent($_post)) { ?>
							<?php echo $content ?>
						<?php } ?>
						<span class="blogDate"><?php echo $_post->getPublishDate('F d, Y') ?></span>
					 </div>
						<!--<a class="post-read-more" href="<?php //echo $_postUrl ?>" title="<?php //echo $_postName ?>">
							   <?php //echo __('Read more &#187;') ?>
						</a>-->
				</div>

			<?php } ?>
	</div>
	<div class="center">
		 <a href="javascript:void(0)" class="showmore">Show More</a>                  
	</div>
	<?php /**if ($block->useLazyload()) { ?>
    <?php
        $config = $block->getLazyloadConfig([
            'trigger_element' => '.mbblog-lazyload-trigger'
        ]);
    ?>
    <div class="mfblog-autoloader" data-mage-init='{"<?php echo $block->getLazyloadJs() ?>" : <?php echo $config ?>}'>
    	<button class="mbblog-lazyload-trigger mfblog-hide-onload action primary" title="<?php echo __('See more') ?>" type="button">
            <span><?php echo __('See more') ?></span>
        </button>
        <img class="posts-loader mfblog-show-onload" src="<?php echo $block->getViewFileUrl('images/loader-2.gif') ?>" alt="<?php echo __('Posts loader') ?>" />
    </div>
<?php } **/?>
</div>
<script>
requirejs( [ 'require', 'jquery', 'Magefan_Blog/js/lib/masonry.pkgd.min' ],
function( require, $, Masonry ) {
    require( [ 'jquery-bridget/jquery-bridget' ],
    function( jQueryBridget ) {
        jQueryBridget( 'masonry', Masonry, $ );
        $('.post-list').masonry({
            itemSelector: '.post-holder',
            percentPosition: true
        });
		if($(".grid").length){
			var $grid = $('.grid').masonry({
				columnWidth: '.grid-sizer',
				gutter: 10,
				itemSelector: '.grid-item',
				percentPosition: true
			});
			var $container = $('.grid');
			$("#gallery-tab").on("click",function(){
				//$container.masonry('reload');
				setTimeout(function(){ $container.masonry() }, 400);
			});
		}
    });
});
<?php /* more info http://masonry.desandro.com/extras.html */ ?>
</script>

<?php } ?>

