<?php
/**
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/** @var $block \Manadev\LayeredNavigation\Blocks\FilterRenderer */
/** @var $data array */
/** @var $engineFilter \Manadev\LayeredNavigation\EngineFilter */
/** @var $filter \Manadev\LayeredNavigation\Models\Filter */
?>
<style>
input[type="checkbox"]{
	float:right;
}
.filter-options-content a:hover
{
	background-color:white!important;
}
</style>

<ol id="<?php echo $block->getFilterName($filter) ?>" class="items" data-mage-init='{ "Manadev_LayeredNavigation/js/FilterView": {} }'>
    <?php foreach ($data as $item): ?>
        <?php if ($item['is_selected']) : ?>
            <li class="mana-selected item">
                
                    <?php echo $block->escapeItemLabel($engineFilter, $item['label']) ?>
                    <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
				<a id="cb" href="<?php echo $block->getRemoveItemUrl($engineFilter, $item) ?>"<?php echo $block->getRemoveItemLinkAttributes($engineFilter, $item) ?>>	
				
<input id="cb" type="checkbox" onchange="window.location.href='<?php echo $block->getAddItemUrl($engineFilter, $item) ?>'" checked="checked">
                    <?php endif; ?>
                </a>
            </li>
        <?php elseif ($item['count'] > 0) : ?>
            <li class="item">

                    <?php echo $block->escapeItemLabel($engineFilter, $item['label']) ?>
                    <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
                                      <a id="cb" href="<?php echo $block->getAddItemUrl($engineFilter, $item) ?>"<?php echo $block->getAddItemLinkAttributes($engineFilter, $item) ?>>  
						<input id="cb" type="checkbox" onchange="window.location.href='<?php echo $block->getAddItemUrl($engineFilter, $item) ?>'">

                    <?php endif; ?>
                </a>
            </li>
        <?php else : ?>
            <li class="item">
                <?php echo $block->escapeItemLabel($engineFilter, $item['label']) ?>
                <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
				<a id="cb" href="<?php echo $block->getRemoveItemUrl($engineFilter, $item) ?>"<?php echo $block->getRemoveItemLinkAttributes($engineFilter, $item) ?>>	
				
<input id="cb" type="checkbox" onchange="window.location.href='<?php echo $block->getAddItemUrl($engineFilter, $item) ?>'">
                    <?php endif; ?>
                </a>
               
            </li>
        <?php endif; ?>
    <?php endforeach ?>
</ol>
