<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$base_url = $storeManager->getStore()->getBaseUrl();
//echo $base_url; newsletter/subscriber/new/
?>
<div class="modal  block block-customer-login authenticateModal" id="forgotModal" tabindex="-1" role="dialog" aria-labelledby="forgotModal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">
      <div class="form-login popup-login-form-forgot">
         
                <div class="response-msg-forgot"></div>
                    <div class="container" >
                        <div class="cf">
                            <span class="close cancelbtn closeRst forgot-close">
                              <span class="fa fa-close"></span>
                            </span>
                        </div>
                        <div id="forgotForm">
                        <form novalidate id="forgot-validate-detail" action="<?php echo $base_url; ?>customerlogin/ajax/forgot" method="post" data-mage-init='{"validation": {"errorClass": "mage-error"}}' >
                        <h3><span id="block-customer-login-heading" role="heading" aria-level="2">Reset Password</span></h3>
                        <p>Enter the email address associated with your account,<br/>and we'll email you a link to reset your password.</p>
                        <div class="inputArea field required" >
                            <label class="label" for="email_address"><?php echo __('Email Address') ?></label>
                            <input  class="textInput input-text" type="email" id="email_address" placeholder="<?php echo __('Email Address') ?>" name="username" data-validate="{required:true, 'validate-email':true}">
                        </div>  
                          <?php echo $block->getChildHtml('form_additional_info'); ?>
                        <div class="secondary right forgot-link">
                        </div>
                        <div class="cf">
                            <a  class="backToLogin returnlogin" ><span><?php echo __('< Back to Login') ?></span></a> <?php /*echo $block->getForgotPasswordUrl()*/ ?>
                            <button class="forgot-submit signupBtn login resetBtn" type="submit"><?php echo __('Send Reset Link') ?></button>
                        </div>
                </form>
                    </div>
                    </div>
                </div>
</div>
</div>
</div>

    <script type="text/javascript">
        require(['jquery'], function($) {
            var headerElem = $('.login-overlay');
            var forgotLink = headerElem.find('.forgot-link').children('a');
            var returnloginLink = headerElem.find('.returnlogin').children('a');
            var loginOverlay = $('.login-overlay');
            var loginBox = $('.login-overlay').find('.popup-login-form');
            var registerBox = $('.login-overlay').find('.popup-register-form');
            forgotLink.click(function(e){
                // loginOverlay.hide();
                loginBox.hide();
                registerBox.hide();
                $('#forgotModal').show();
                //$('#forgotModal').modal('show');
                });
            
            $(document).ready(function() {
                $('body').delegate('.returnlogin','click',function(e){
                e.preventDefault();
                $('#forgotModal').hide();
                loginOverlay.show();
                loginBox.show();
                registerBox.hide();
                });
            $('body').delegate('.forgot-close','click',function(e){
                $('#forgotModal').hide();
                loginOverlay.show();
                loginBox.show();
                registerBox.hide();
                

                
                //$('#forgotModal').modal('show');
                });
            var self = this,
                form = $('#forgot-validate-detail');
            form.submit(function (e) {
                if (form.validation('isValid')) {
                    var email = $("#email_address").val();
                    var url = form.attr('action');
                    e.preventDefault();
                    $.ajax({
                        url: url,
                        dataType: 'json',
                        type: 'POST',
                        showLoader: true,
                        data: {email: email}
                    }).done(function (data) {
                         console.log(data);
                         if (data.error) {
                            $('.response-msg-forgot').html("<div class='error'>"+data.error+"</div>");
                            setTimeout(function() {
                                $('.response-msg-forgot').html("");
                            }, 5000);
                        } else if (data.success) {
                            $('.response-msg-forgot').html('');
                            $('#forgotForm').html('<h3>THANK YOU</h3><p>'+data.success+'</p><div class="inputArea"><button class="forgot-close signupBtn newsclosebtn" title="Close"  type="submit"> <span>Close</span> </button><a  class="backToLogin returnlogin" ><span><?php echo __('< Back to Login') ?></span></a></div>');
                            //$('.forgot-submit').hide();
                        }
                    });
                }
            });

        });
            });

    </script>

