<?php
/**
 * Solwin Infotech
 * Solwin Instagram Extension
 * 
 * @category   Solwin
 * @package    Solwin_Instagram
 * @copyright  Copyright © 2006-2016 Solwin (https://www.solwininfotech.com)
 * @license    https://www.solwininfotech.com/magento-extension-license/
 */
$helper = $this->helper('\Solwin\Instagram\Helper\Data');
$enable = $helper->getConfig('instagramsection/instagramgroup/active');
$userId = $helper->getConfig('instagramsection/instagramgroup/userid');
$accessToken = $helper->getConfig('instagramsection/instagramgroup/accesstoken');
$imageNumber = $this->getData('numberimage');
$imageResolution = $this->getData('resolution'); 
?>

<?php
if ($enable) {
		$accessToken.'&count='.$imageNumber;
        $url = 'https://api.instagram.com/v1/users/self/media/recent/?access_token=' . $accessToken;
        $args = stream_context_create(array('http' => array('timeout' => 2500,)));
        //for Live server
        //$instagramFeedsData = file_get_contents($url, false, $args);
        // for Local Server
        $instagramFeedsData = $helper->getInstangramData($url);
        $instagramFeeds = json_decode($instagramFeedsData);

        $instangramData = $instagramFeeds->data;
		$username = !empty($instangramData[0]->user->username) ? $instangramData[0]->user->username : '';
    ?>
		<div class="sliderTitle"> <!-- <span class="logoStrip"> <img src="<?php echo $block->getViewFileUrl('images/logo-55.png'); ?>" alt="" title="" /></span> -->
            
           <p class="instaStrip"> Real life SuperHeroes wear Adar uniforms </p>
            
		<span>Follow Us<a href ="https://www.instagram.com/<?php echo $username; ?>" target="_blank">
			<?php echo $this->getData('title'); ?> 
		</a></span>
		</div>
		<ul class="prodSlider" data-id="<?= $imageNumber ? $imageNumber : 7 ?>">
        <?php
        //$url = 'https://api.instagram.com/v1/users/' . $userId . '/media/recent/?access_token=' . 
        foreach ($instangramData as $instagramFeed) {           
                $instagramImage = $instagramFeed->images->$imageResolution->url;
			// $instagramImage = $instagramFeed->images->thumbnail->url;
            ?>

            <?php
            $caption_text = 'Instagram';
            if (is_object($instagramFeed->caption)) {
                $caption_text = $instagramFeed->caption->text;
            }
            ?>
				<li> 
					<a href ="<?php echo $instagramFeed->link; ?>" target="_blank">
						<img src="<?php echo $instagramImage; ?>" title="<?php echo $caption_text; ?>" alt="<?php echo $caption_text; ?>"/>
					</a>
				</li>
            <?php
        } ?>
		</ul>
    <div class="clear gap-30"></div>
<?php }
