<?php
	if($this->customerloged()):
		$adminCutom = $this->getAdminCustomer();
		$data = $this->getCustomerDetails(); 
		$pencile = '<?xml version="1.0" standalone="no"?> <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 20010904//EN""http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd"> <svg version="1.0" xmlns="http://www.w3.org/2000/svg"width="512.000000pt" height="512.000000pt" viewBox="0 0 512.000000 512.000000"preserveAspectRatio="xMidYMid meet"> <g transform="translate(0.000000,512.000000) scale(0.100000,-0.100000)" stroke="none"> <path d="M4170 5105 c-136 -28 -248 -80 -355 -165 -106 -85 -3338 -3329 -3387 -3400 -49 -69 -108 -182 -127 -241 -14 -44 -301 -1292 -297 -1296 1 -1 287 63 636 143 395 90 664 156 711 175 175 69 108 6 1910 1808 1152 1151 1690 1696 1719 1740 198 297 183 679 -39 953 -185 228 -489 340 -771 283z m238 -395 c74 -17 135 -52 192 -110 122 -121 152 -296 80 -455 -19 -42 -294 -321 -1643 -1671 l-1619 -1621 -432 -153 c-237 -85 -437 -158 -443 -163 -19 -14 -4 30 161 478 l148 399 1505 1511 c827 830 1557 1560 1622 1621 65 61 136 119 157 129 88 42 185 55 272 35z"/> </g> </svg>';
?>
<div id="important">
	<div class="block block-dashboard-info" id="accordionExample">	
		<div class="block-title collapsed" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne"><strong class="upperCaseText"><?= $block->escapeHtml(__('Account Details')) ?></strong>
		</div>
		<div id="collapseOne" class="block-content accountDtlSection collapse" aria-labelledby="headingOne">

			<div class="box-information ">
				<div class="box-descrition">
					<span>Full Name:</span>
					<div class="box-content">
						<p><?php echo $this->getCustomerInfo()->getName(); ?></p>
					</div>
				</div>
				<div class="box-actions">
					<a class="action edit" data-backdrop="false" data-toggle="modal" attr-type = "fullname" data-target="#customer-edit"><span> <?= $pencile ?></span></a>
				</div>
			</div>
			<div class="box-information emailBox">
				<div class="box-descrition">
					<span>Email/User ID:</span>
					<div class="box-content emailVal">
						<p><?php echo $this->getCustomerInfo()->getEmail(); ?></p>
					</div>
				</div>
				<div class="box-actions">
					<a class="action edit" data-backdrop="false" data-toggle="modal" attr-type = "email" data-target="#customer-edit"><span><?= $pencile ?></span></a>
				</div>
			</div>
			<div class="box-information pswdBox">
				<div class="box-descrition">
					<span>Password:</span>
					<div class="box-content">
						<p>*****</p>
					</div>
				</div>
				<div class="box-actions">
					<?php if(!$adminCutom ){ ?>
					<a class="action edit" data-backdrop="false" data-toggle="modal" attr-type = "password" data-target="#customer-edit"><span><?= $pencile ?></span></a>
					<?php }else{ ?>
						<a class="action edit adminloginpassword"><span></span></a>
					<?php } ?>
				</div>
			</div>
			<div class="box-information">
				<div class="box-descrition">
					<span>Phone Number:</span>
					<div class="box-content">
						<p><?php echo $this->getCustomerPhoneNo();?></p>
					</div>
				</div>
			</div>
		</div>
	<div class="block block-dashboard-info">
		<div class="block-title collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo"><strong class="upperCaseText"><?= $block->escapeHtml(__('Customer Statement')) ?></strong>
		</div>
		<div id="collapseTwo" class="block-content customerStatement collapse" aria-labelledby="headingOne">
			<div class="box box-information">
				<strong class="box-title">
					<span><?= $block->escapeHtml(__('Customer Code:')) ?></span>
				</strong>
				<div class="box-content">
					<p>
						<?php echo isset($data['CardCode']) ? $data['CardCode'] : 'N/A' ; ?><br>
					</p>
				</div>
				</div>
			<div class="box box-information">
				<strong class="box-title">
					<span><?= $block->escapeHtml(__('Location:')) ?></span>
				</strong>
				<div class="box-content">
					<p>
						<?php
							$cust_location = [];
							if (isset($data['BCity']) && !empty($data['BCity']))
								$cust_location[] = $data['BCity'];

							if (isset($data['BState']) && !empty($data['BState']))
								$cust_location[] = $data['BState'];

							echo (!empty($cust_location)) ? implode(", ", $cust_location) : 'N/A';
						?>
					</p>
				</div>
			</div>
			<div class="box box-information">
				<strong class="box-title">
					<span><?= $block->escapeHtml(__('Current Open Balance:')) ?></span>
				</strong>
				<div class="box-content">
					<p>
						<?php echo isset($data['AccountBalance']) ? '$'.number_format($data['AccountBalance'],2) : 'N/A' ; ?><br>
					</p>
				</div>
			</div>
			<div class="box box-information">
				<strong class="box-title">
					<span><?= $block->escapeHtml(__('Customer Name:')) ?></span>
				</strong>
				<div class="box-content">
					<p>
						<?php echo isset($data['CardName']) ? $data['CardName'] : 'N/A' ; ?><br>
					</p>
				</div>
			</div>
			<div class="box box-information">
				<strong class="box-title">
					<span><?= $block->escapeHtml(__('Discount Program / Tier:')) ?></span>
				</strong>
				<div class="box-content">
					<p>
						<?php
						$discount_program = "N/A";
						if (isset($data['Program']) && !empty($data['Program'])) {
							$flateDiscount = (isset($data['Program']) && !empty($data['Program'])) ? $data['Program'] :  'N/A';
							$tier = (isset($data['Tier']) && !empty($data['Tier'])) ? $data['Tier'] : 'N/A';
							$discount_program = $flateDiscount.' / '.$tier ;
						}
						echo $discount_program; ?><br>
					</p>
				</div>
			</div>
			<div class="box box-information">
				<strong class="box-title">
					<span><?= $block->escapeHtml(__('Current Open Orders:')) ?></span>
				</strong>
				<div class="box-content">
					<p>
						<?php echo isset($data['OpenOrder']) ? '$'.number_format($data['OpenOrder'], 2) : 'N/A' ; ?><br>
					</p>
				</div>
			</div>
		</div>
	</div>
	<div class="block block-dashboard-info paymentBlock">
		<div class="block-title collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree"><strong class="upperCaseText"><?= $block->escapeHtml(__('Payment Information')) ?></strong>
		</div>
		<div id="collapseThree" class="block-content collapse" aria-labelledby="headingOne">

		</div>
	</div>
	<div class="block block-dashboard-info shippingBlock">
		<div class="block-title collapsed" data-toggle="collapse" data-target="#collapseFour" aria-expanded="true" aria-controls="collapseFour"><strong class="upperCaseText"><?= $block->escapeHtml(__('Shipping Information')) ?></strong>
		</div>
		<div id="collapseFour" class="block-content collapse paddL15" aria-labelledby="headingOne"> 

		</div>
	</div>
	</div>
</div>
     
<script type="text/x-magento-init">
	{
	    "#important": {
	        "Magento_Customer/js/account-shipment": {   
	         	"formkey": <?= json_encode($block->getBlockHtml('formkey'))?>,
    	        "baseurl" : "<?= $this->getBaseUrl(); ?>",
	            "viewfileurl" : "<?= $this->getViewFileUrl('/'); ?>",
	            "datapayment": <?= json_encode($data["PaymentTerm"]); ?>
	        }
	    }
	}
</script>
<?
endif;
?>
