<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$required = '';
if ($block->hasRequiredOptions()) {
    $required = ' data-hasrequired="' . __('* Required Fields') . '"';
}
?>
<div class="product-options-wrapper" id="product-options-wrapper"<?= /* @escapeNotVerified */ $required ?>>
    <div class="fieldset" tabindex="0">
        <?= $block->getChildHtml('', true) ?>
    </div>
</div>

<script type="text/javascript">
    require(['jquery'], function($) {
    	jQuery(document).ready(checkContainer);

		function checkContainer() {
		    if ($('.swatch-option.image').is(':visible')) { //if the container is visible on the page
		        changeOrder($('[aria-labelledby=option-label-color-93]')); //Adds a grid to the html
		        changeOrder($('[aria-labelledby=option-label-seasonalcolors-152]'));
		        changeOrder($('[aria-labelledby=option-label-heather_colors-227]'));
		    } else {
		        setTimeout(checkContainer, 50); //wait 50 ms, then try again
		    }
		}

		function changeOrder(lbl) {
		    var $wrapper = lbl;
		    $wrapper.find('.swatch-option').sort(function(a, b) {
		        //return +a.dataset.name - +b.dataset.name;
		        if ($(a).attr('option-label') > $(b).attr('option-label')) {
		            return 1;
		        } else {
		            return -1;
		        }
		    }).appendTo($wrapper);
		}
    });
</script>