<?php

$baseUrl = $this->getBaseUrl();
$baseUrpath = $baseUrl.'customerorder/customer/myaccountemail';
$currentStore = $this->StoreManagerInterface->getStore();
$mediaUrl = $currentStore ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

?>
<div class="orderItem-loader" style="display: none;">
    <div class="loader">
        <img src="<?=$this->getBaseUrl()?>/pub/static/version1608537802/frontend/sttl/adaruniforms/en_US/images/loader-1.gif" alt="Loading...">
    </div>
</div>


<div class="envelope-section">
	<div class="header-section">
		<div>
			<h3>Hi there!</h3>
			<p>Send us a message or give your feedback!</p>
		</div>
		<span class="clsbtn">
			<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"viewBox="0 0 512.001 512.001" style="enable-background:new 0 0 512.001 512.001;" xml:space="preserve"> <g> <g> <path d="M284.286,256.002L506.143,34.144c7.811-7.811,7.811-20.475,0-28.285c-7.811-7.81-20.475-7.811-28.285,0L256,227.717 L34.143,5.859c-7.811-7.811-20.475-7.811-28.285,0c-7.81,7.811-7.811,20.475,0,28.285l221.857,221.857L5.858,477.859 c-7.811,7.811-7.811,20.475,0,28.285c3.905,3.905,9.024,5.857,14.143,5.857c5.119,0,10.237-1.952,14.143-5.857L256,284.287 l221.857,221.857c3.905,3.905,9.024,5.857,14.143,5.857s10.237-1.952,14.143-5.857c7.811-7.811,7.811-20.475,0-28.285 L284.286,256.002z"/> </g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> <g> </g> </svg>
		</span>
	</div>
	<div class="description-section">
		<div id="fedbackformdeiv">
		<form action="<?php echo $baseUrpath; ?>" method="POST" id="feedbackformmyaccount" enctype="multipart/form-data">
			<div class="head-titel">
				<h6>Start a new message</h6>
				<p>Someone from our team will get back to you as soon as they can!</p>
			</div>
			<div class="textareabutton">
				<textarea  name="feedback" class="feedback-area" id="feedback-name" placeholder="Type a message..."></textarea> <label for="feedback"></label>

			</div>	
			<span class="errormessagefileupload"></span>	
			<div class="custom-file">
			    <input type="file" name="fileupload" class="custom-file-input" id="attach_file">
			    <label class="custom-file-label" for="file"> <i class="fa fa-paperclip" aria-hidden="true"></i>Attach Files</label>
			</div>
				<div class="envelope-action">
					<button type="submit" class="envelope-send" id="envelopeSend" ><span>Send</span></button>
				</div>
			 <span id="fileList" class="file-list"></span>
			 <div class="filepreview" style="display: none;"><img id="previewImg" style="display: none;"><span class="remove-list" style="display: none;"><i class="fa fa-times-circle" aria-hidden="true"></i></span></div>
		</form>
		</div>
		<div id="feedbacksuccessdiv" style="display: none;">
			<div class="messagesent">			
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 44 19" width="55" height="30"> <defs> <image width="48" height="29" id="img1" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAdCAMAAADb7h9dAAAAAXNSR0IB2cksfwAAAIpQTFRFAAAAg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJg7NJbpprAQAAAC50Uk5TAP8+/k1v+s/f+Mr7vNHzq9Pvr/zc7qH53enE/eOX7KhW2ddi2Mj3xb3tqfKmtMkTXygAAADCSURBVHic7ZPZEoIwDEVzxR3cl4qouCsu//97loKMlLQdXx3vQzqT5mTrlOivXOBUM8d7LGAmgDrvbhgBQlPztVAAWt0MaKNTiu/CtwMUlIge+o6WiAYfXQ0x0maoViAaY5LfTjHTh+YAmkOoc4HQvSWlJSJpV8pWAKbCGj48CiGwYYDorQKIZeatzLCjfbojZ0uB2tIBR2lPODuBS+kdriltBZKsi0I3wA6Iu+Z7eFYgYbxPMxDx3wGG8KzGl8CP6wUzcQdU8+GckQAAAABJRU5ErkJggg=="/> </defs> <style> tspan { white-space:pre } </style> <g id="Group 1"> <use id="Rectangle 6" href="#img1" x="-1" y="-5" /> </g> </svg>
				<h4>Message Sent!</h4>
				<p>Thank you for your message, someone from our team will get back to you as soon as they can!</p>
			</div>
			
		</div>
	</div>

</div>



<script type="text/javascript">
	require([ 'jquery', 'jquery/ui'], function($){

		function readURL(input) {
		  if (input.files && input.files[0]) {
		    var reader = new FileReader();
		    
		    reader.onload = function(e) {
		    	var extension = input.files[0]['name'].split('.').pop();

		    	var fileSize = input.files[0].size,
			  		errorMessageSelector = $(".errormessagefileupload");

		    	if(extension == 'jpg' || extension == 'jpeg' || extension == 'png' || extension == 'gif' || extension == 'csv' || extension == 'pdf'){
			    	if(fileSize >= 3145728){
			    		const message = "The file is too large. Maximum upload file size: 3MB";
			    		errorMessageSelector.html(message);
			    			errorMessageSelector.fadeIn(800)
			    		setTimeout(function(){
			    			errorMessageSelector.fadeOut(800,function(){
			    				errorMessageSelector.html('');
			    			});
			    		},5000)
			    		return false;
			    	}
			    	if(extension == 'jpg' || extension == 'png' || extension == 'jpeg')
			    	{
			          $('#previewImg').css({'display':'block'});
			          $('#previewImg').attr('src', e.target.result);
			          $('.remove-list').css({'display':'block'});
			    	  $('.filepreview').css({'display':'flex'});
			    	  $('.custom-file').css({'opacity':'0.5','pointer-events':'none'});

			    	}
			    	else
			    	{
			    		$('#fileList').html(input.files[0]['name']+'<span class="remove-list"><i class="fa fa-times-circle" aria-hidden="true"></i></span>');
			    		$('.custom-file').css({'opacity':'0.5','pointer-events':'none'});
			    	}
		    	}else{
		    		errorMessageSelector.html('Please Attach Valid file.');
		    		errorMessageSelector.fadeIn(700);
            		setTimeout(function(){ errorMessageSelector.fadeOut(700,function(){
            			errorMessageSelector.html('');
            		}); }, 5000);
		  			$('#attach_file').val('');
            		return false;
		    	}
		    }
		    // input.files.item(i).name
		    reader.readAsDataURL(input.files[0]); // convert to base64 string
		  }
		}

		$("#attach_file").change(function() {
		  readURL(this);
		});

		$(document).on('click','.remove-list',function(){
			$('#attach_file').val('');
			$('#fileList').html('');
			$('#previewImg').attr('src','');
		    $('#previewImg').css({'display':'none'});
		    $('.filepreview').css({'display':'none'});
			$(this).css({'display':'none'});
			$('.custom-file').css({'opacity':'unset','pointer-events':'unset'});
		});
		$('.feedback-area').on('input',function(){
			// var len = $(this).val().length
			var lenth = $(this).val().replace(/\s/g, '');
			var len = lenth.length;
			if(len > 0)
			{
				$('.envelope-action .envelope-send').css({'display':'block'});	
			}
			else
			{
				$('.envelope-action .envelope-send').css({'display':'none'});
			}
		});
		$(document).keyup(function(e){

			if(e.keyCode == 27)
			{
				if($('.envelope-conatiner').css('display') == 'block')
                {
                    $('.envelopecontainer').trigger('click');
                }
                if($('.serach-conatiner').css('display') == 'block')
                {
                    $('.sidesearch').trigger('click');
                }
			
			} 

		})
		$('#main-blur').click(function(){
			 
                if($('.serach-conatiner').css('display') == 'block')
                {
                    $('.sidesearch').trigger('click');
                }
		})
		$('.back-view').click(function(){
			if($('.envelope-conatiner').css('display') == 'block')
                {
                    $('.envelopecontainer').trigger('click');
                }
		})
		

		$("#feedbackformmyaccount").submit(function(e) {

			    e.preventDefault(); // avoid to execute the actual submit of the form.

			    var form = $(this);
			    var url = form.attr('action');

			    var form_data = new FormData();

			    var files = $('#attach_file')[0].files;


			     if(files.lenth > 0){

					    var fileName = files[0].name;
					    fileExtension = fileName.substr((fileName.lastIndexOf('.') + 1));
		            	
            	}

            	form_data.append('fileupload',files[0]);
            	form_data.append('feedback',$('#feedback-name').val());

        	 	$.ajax({
	              url: url,
	              type: 'post',
	              beforeSend: function(){
			           	$('.envelope-conatiner .orderItem-loader').css({'display':'block'});
			           },
	              data: form_data,
	              contentType: false,
	              processData: false,
	              success: function(response){
	              	
	                 if(!response.errors){
	                    $('#feedbacksuccessdiv').css({'display':'block'});
						$('#fedbackformdeiv').css({'display':'none'});
	                 }else{
	                    alert(response.message);
	                 }
	              },
	              complete:function(){
			           	$('.envelope-conatiner .orderItem-loader').css({'display':'none'});
			      },
	           });

			    
			});
		$('.clsbtn').on('click',function(){
				$('.envelopecontainer').trigger('click');
				$('#feedbacksuccessdiv').css({'display':'none'});
				$('#fedbackformdeiv').css({'display':'block'});
				$('#feedbackformmyaccount').trigger("reset");
				$('.remove-list').trigger('click');
		});


	});
</script>