<div class="block myaccount_nav">
	<div class="block-title block-dashboard-info collapsed" data-toggle="collapse" data-target=".account_menu_nav" aria-expanded="false" aria-controls="account_menu_nav">
		<strong class="upperCaseText">My Account</strong>
	</div>
</div>
<style>

    .block.myaccount_nav .block-title{  color: #0c4269;
    font-size: 20px; text-align: left; padding: 15px 15px; }

    .block.myaccount_nav{ margin-bottom: -1px !important; }

.myaccount_nav .block-title.collapsed:after {
    content: "\f078" !important;
    color: #0c4269;
    font: normal normal normal 14px/1 FontAwesome;
}
.myaccount_nav .block-title:after {
    content: "\f077" !important;
    color: #0c4269;
    font: normal normal normal 14px/1 FontAwesome;
    display: inline-block;
    float: right;
    margin-top: 5px;
}

</style>