<?php
	$ordersPacakge = $block->getOrderDataCollection();
	$orders = json_decode(json_encode($ordersPacakge['data']), true);	
	// echo '<pre>'; print_r($orders); die;
	$page = $ordersPacakge['page'];
	$total =  $ordersPacakge['total']; 
	$totalPage = ceil($total/30);
	$back_redirect = $this->getBaseUrl()."customerorder/customer/index";	
?>
	<!--- tables div -->
	
		
		<table class="orderList">
			<thead>
			<tr class="table-header">
					<th>Status</th>
					<th>SO Number</th>
					<th>PO Number</th>					  
				</tr>
			</thead>
			<tbody>   
			<?php
			$ordered = 0;
			$open = 0;
			$shipped = 0;
			$total_order = 0;			
			if($total > 0)
			{
				$count = $page * 30 + 1;
				foreach($orders as $order)
				{
					$ordered += $order['TotalQTYUnits'] > 0 ? $order['TotalQTYUnits'] : 0;
					$open += $order['TotalOpen'] > 0 ? $order['TotalOpen'] : 0;
					$shipped += $order['TotalShipped'] > 0 ? $order['TotalShipped'] : 0;
					$total_order += $order['DocTotal'] > 0 ? $order['DocTotal'] : 0;
					
					$id_b_e = base64_encode($order['Id']);
					if($order['dataFrom'] == 'V')
					{
						$id_b_e = base64_encode($order['DocNum']);
					}
					
					$order_view_url = $block->getBaseUrl().'customerorder/customer/orderview/id/'.$id_b_e.'/back/'.base64_encode($back_redirect).'/df/'.base64_encode($order['dataFrom']);		
					if($order['DocStatus'] == "Draft")	{
							$order_view_url = $block->getBaseUrl().'customerorder/customer/payment?back_order_id='.$id_b_e.'&back_po_number='.base64_encode($order['NumatCardPo']);
					}
				?>

					<!-- <tr option-redirect = "<?php echo $order_view_url;?>" style="cursor: pointer;">
						<td class="option-redirect">
							<?php  
							if($order['DocStatus'] == 'PartiallyShipped') {
								echo 'Partially Shipped';
							}elseif ($order['DocStatus'] == 'Shipped') {
								echo '<i class="fa fa-check">Shipped</i>';
							} elseif ($order['DocStatus'] == 'Draft') { ?>
										Draft <a class="newLinkText" href="<?php echo $this->getBaseUrl();?>customerorder/customer/neworder/id/<?php echo base64_encode($order['Id']);?>/ncp/<?php echo base64_encode($order['NumatCardPo']);?>#block-title"><span class="fa fa-pencil"></span></a>
										<a class="newLinkTextRemove" href="<?php echo $this->getBaseUrl();?>customerorder/customer/delete/id/<?php echo base64_encode($order['Id']).'/back/'.base64_encode($back_redirect);?>/"><span class="fa fa-close"></span></a>
							<?php }
							else{
								echo $order['DocStatus'];	
							} 
						?>
							
						</td>
						<td class="option-redirect"><?php echo ($order['DocNum'] != '') ? $order['DocNum'] : "";?></td>
						<td class="option-redirect"><?php echo ($order['NumatCardPo'] != '') ? $order['NumatCardPo'] : "-";?></td>						
					</tr> -->
						<tr option-redirect = "" style="cursor: pointer;">
							<td class="option-redirect">
									<?php  
										if($order['DocStatus'] == 'PartiallyShipped') {
											echo 'Partially Shipped';
										}elseif ($order['DocStatus'] == 'Shipped') {
											echo '<i class="fa fa-check">Shipped</i>';
										} elseif ($order['DocStatus'] == 'Draft') { ?>
											<div class="d-flex draft-section">
												Draft 
												<div class="action-conatiner">
													<img id="draftAction" src="https://img.pngio.com/action-icon-png-153835-free-icons-library-action-icon-png-696_738.jpg" alt="action" />
													<div class="draft-action">
														<a class="newLinkText" href="<?php echo $this->getBaseUrl();?>customerorder/customer/neworder/id/<?php echo base64_encode($order['Id']);?>/ncp/<?php echo base64_encode($order['NumatCardPo']);?>#block-title"><span class="fa fa-pencil"></span></a>
														<a class="newLinkTextRemove" href="<?php echo $this->getBaseUrl();?>customerorder/customer/delete/id/<?php echo base64_encode($order['Id']).'/back/'.base64_encode($back_redirect);?>/"><span class="fa fa-close"></span></a>
														<a class="newLinkTextView" href="<?php echo $order_view_url;?>"><span class="fa fa-eye" aria-hidden="true" ></span></a>
													</div>
												</div>
												
											</div>
										<?php }
										else{
											echo $order['DocStatus'];	
										 
										} 
								?>
							</td>
							<td class="option-redirect"><?php echo ($order['DocNum'] != '') ? $order['DocNum'] : "";?></td>
							<td class="option-redirect">
								<?php //if($order_stats == "Draft" || $order['DocStatus'] == "Draft" || $order_stats == "Submitted" || $order['DocStatus'] == "Submitted"){ ?>
								<?php echo ($order['NumatCardPo'] != '') ? $order['NumatCardPo'] : "-";?><?php /* }else{ ?>
									<?php echo ($order['NumatCardPo'] != '') ? $order['NumatCardPo'] : "-";?>
								<?php }*/ ?>
							</td>

						</tr>

				<?php
				$count++;
			}?>
			</tbody>
			<tfoot>
				<tr class="paginationRow" id="paginationId" data-id=1>
					<td colspan="9" class="testTable" rowspan="1">
						<div class="fa-pull-right d-flex">
							<div class="fa-pull-left recordTotal"> Displaying <?= $page * 30+1 ?> to <?= $count-1 ?> of <?= $total ?></div>
							<?php if($total > 30){?>
								<div class="pagination">
									<div class="dataTables_paginate paging_full_numbers" id="example_paginate">
										<?php if($page > 0){ ?>
											<a class="paginate_button first" aria-controls="example" data-dt-idx="1" tabindex="0" id="example_first"><span class="pageIcon first"></span></a>
											<a class="paginate_button previous" aria-controls="example" data-dt-idx="<?= $page  ?>" tabindex="0" id="example_previous"><span class="pageIcon previous"></span></a>	
										<?php } ?>
										<span class="cdatatableDetails">
											<input type="text" value="<?= $page +1  ?>" class="direct-serach" data-dt-idx="<?= $page +1  ?>"> / <?= $totalPage ?>
										</span>
										<?php if($page < $totalPage){ ?>
											<a class="paginate_button next" aria-controls="example" data-dt-idx="<?= $page+2 ?>" tabindex="0" id="example_next"><span class="pageIcon next"></span></a>
											<a class="paginate_button last" aria-controls="example" data-dt-idx="<?= $totalPage; ?>" tabindex="0" id="example_last"><span class="pageIcon last"></span></a>
										<?php } ?>
									</div>
								</div>
							<?php } ?>
						</div>
					</td>
				</tr>
			<!-- 	<tr>
					<td colspan="5" align="right"> Total Quantity:</td>
					<td><?php echo number_format((int)$ordered);?></td>
					<td><?php echo number_format((int)$open);?></td>
					<td><?php echo number_format((int)$shipped);?></td>
					<td>$<?php echo number_format($total_order,2);?></td>
					<td></td>
				</tr> -->
			</tfoot>
			<?php
		}
		else
		{?>
			<tr>
				<td class="no-records" colspan="9" >No Orders Found!</td>            
			</tr>
		<?php } ?>
	</table>
