<?php
$ragisterdata = $block->getRegisterData();
$helper = $this->helper('Sttl\Adaruniforms\Helper\Sap');
$customerdata = $ragisterdata['customerdata'];
if(isset($customerdata) && isset($customerdata['errors']))
{
	echo $customerdata['message'];
}
else
{
	$post = $this->getRequest()->getParams();
	$orderdata = $ragisterdata['orderdata'];
	$currentorderdata = $orderdata[0];
	$customerdata = $customerdata[0];
	$notshow = true;
if(strtolower($currentorderdata['DocStatus']) == strtolower('Submitted'))
    {
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $redirect = $objectManager->get('\Magento\Framework\App\Response\Http');
        $baseurl =  $block->getBaseUrl().'customerorder/customer/index';
        $redirect->setRedirect($baseurl);
    }
?>
<form name="ordersummary" id="ordersummary" method="POST" enctype="multipart/form-data" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" autocomplete="off" data-mage-init='{"validation": {"errorClass": "mage-error"}, "theAdarValidationMethod":{}}' action="<?php echo $block->getBaseUrl().'customerorder/customer/reviewordersubmit' ?>">
	<div class="block block-dashboard-info cf newOrderStep3 ordersummary">
    	<div class="header-title" >
			<strong style="font-size: 20px; "> Review and submit your order.</strong>
		</div>
		<div class="cols12 mb-2">
			<div class="box box-information"><strong>P.O. Number:</strong> <span id="poNumber"><?php echo $currentorderdata['NumatCardPo'];?></span></div>
		</div>
		<div class="Shipping-details">
            <strong class="box-title main-box">
                <span>Shipping Details:</span>
			</strong>
			<div class="d-flex">
            	<?php echo $this->getLayout()->createBlock("Sttl\Customerorder\Block\Viewordersummary")->setCustomerData($customerdata)->setTemplate("Sttl_Customerorder::createorder/summaryshippinginformation.phtml")->toHtml();?>

				<div class="box box-information shmet">
					<strong class="box-title">
						<span>Shipping Method:</span>
					</strong>
					<div class="box-content">
						<?php if($currentorderdata['ShippingType'] != '') { ?>
							<?php if($currentorderdata['ShippingType'] == $customerdata['ShipCode']) {
								$notshow = false;
							 ?>
								<span><?php echo $customerdata['ShipType'];?></span>
							<?php } ?>
							<?php if($currentorderdata['ShippingType'] == "STD") { ?>
								<span>Ground (3 - 5 business)</span>
							<?php } ?>
							<?php if($currentorderdata['ShippingType'] == "NXD") { ?>
								<span>Next Day</span>
							<?php } ?>
							<?php if($currentorderdata['ShippingType'] == "SCD") { ?>
								<span>2nd Day</span>
							<?php } ?>
							<?php if($currentorderdata['ShippingType'] == "THD") { ?>
								<span>3 Day Select</span>
							<?php } ?>
							<?php if($currentorderdata['ShippingType'] == "4" && $notshow) { ?>
								<span>Pick Up</span>
							<?php } ?>

							<?php  }else{ ?>
							<select class="col-md-12" name="shiiping_method" >
								<option>Select</option>
								<?php if($customerdata['ShipCode'] != '128' && $customerdata['ShipType'] != 'All') { ?>
									<option value="<?php echo $customerdata['ShipCode'];?>" <?php if($currentorderdata['ShippingType'] ==  $customerdata['ShipCode']) { echo 'selected="selected"'; } ?> ><?php echo $customerdata['ShipType'].'(Default Shipping Method)'; ?></option>
								<?php }?>
								<option value="STD" <?php if($currentorderdata['ShippingType'] == "STD") { echo 'selected="selected"'; } ?> >Ground (3 - 5 business)</option>
								<option value="NXD" <?php if($currentorderdata['ShippingType'] == "NXD") { echo 'selected="selected"'; } ?>>Next Day </option>
								<option value="SCD" <?php if($currentorderdata['ShippingType'] == "SCD") { echo 'selected="selected"'; } ?>>2nd Day </option>
								<option value="THD" <?php if($currentorderdata['ShippingType'] == "THD") { echo 'selected="selected"'; } ?>>3 Day Select</option>
							</select>
						<?php } ?>
					</div>
				</div>
			</div>
		</div>
		<div class="billingDtl">
			<strong class="box-title main-box">
                <span>Billing Details:</span>
			</strong>
			<div class="billingDtl-container">
			<?php echo $this->getLayout()->createBlock("Sttl\Customerorder\Block\Viewordersummary")->setCustomerData($customerdata)->setTemplate("Sttl_Customerorder::createorder/summarysavepament.phtml")->toHtml();?>
			</div>

		</div>
		<div class="cf">
            <input type="hidden" name="order_id" id="order_id" value="<?php echo $post['order_id']?>">
            <input type="hidden" name="order_method" id="order_method" value="Mobile">
            <input type="hidden" name="po_number" id="po_number" value="<?php echo $post['po_number']?>">
            <input type="hidden" name="WebOrderId" id="WebOrderId" value="<?php echo $currentorderdata['WebOrderId']?>">
		</div>
		<div class="cols12 mb-2">
			<p><strong>Delivery Notes:</strong> <span id="DeliveryNotes"><?php echo (isset($currentorderdata['DeliveryNotes']) && !empty($currentorderdata['DeliveryNotes'])) ? $currentorderdata['DeliveryNotes'] : "";?></span></p>
		</div>
		<div class="cols12 mb-2 text-center">
			<p><strong>Please Note:</strong> <span id="freightNotes">Freight will be calculated once the order is processed.</span></p>
		</div>
        <div class="cf line-item">
            <h3 class="subTitle">Line Items <!-- <a href="javascript:void(0);" class="printBtn alignRight"> <span class="fa fa-print"></span> Print/Export PDF</a> --></h3>
            <div class="orderListing">
                <?php

					$style = '';
					$submitcolor = '';
					$viewmode = 'ordersummary';
					echo $this->getLayout()->createBlock("Sttl\Adaruniforms\Block\View")->setOrderId($post['order_id'])->setViewmode($viewmode)->setStyle($style)->setSubmitcolor($submitcolor)->setTemplate("Sttl_Customerorder::OrderTotal.phtml")->toHtml();
				?>
			</div>
		</div>
        <div class="cf orderBtnRow">
            <div class="actions-container alignRight d-flex">
                <a href="<?php echo $block->getBaseUrl();?>customerorder/customer/payment?back_order_id=<?php echo base64_encode($post['order_id']);?>&back_po_number=<?php echo base64_encode($post['po_number']) ?>" class="delUrl newLinkText">Back</a>
                <button type="submit" class="themeBtn mobile-button action save submitorder_sttl" title="Submit Order"><span>Submit Order</span></button>
			</div>
		</div>
	</div>
</form>
<script type="text/javascript">
    require(['jquery'], function($) {
        $(document).ready(function() {
        	$(".toggletable"). children('td:first').attr("colspan",4);
			$(".submitorder_sttl").click(function(e){

				$('body').trigger('processStart');
			});
			$(".newLinkText").click(function(e){
				$('body').trigger('processStart');
			});
            $('.removeeditbillurl').remove();
            $('.removeeditshipurl').remove();
		});
		$(document).on('click','.orderList.mobile.lineItemsList td.toggleshow-line', function() {

          var a = $(this);
          // $(this).parent().next('tr').slideToggle("slow");
					event.preventDefault();
   				 // We break and store the result so we can use it to hide
   				 // the row after the slideToggle is closed
   				 var targetrow = $(this).closest('tr').next('.toggletable');
   				 targetrow.show().find('div').slideToggle('slow', function(){
   					 if (!$(this).is(':visible')) {
   						 targetrow.hide();
   					 }
   				 });
          if($(a).parent().children().first().find('i').hasClass('fa-caret-down')){
          	// console.log($(this).parent().next('tr').offset().top);
			 $('html, body').animate({
		        scrollTop: $(this).parent().next('tr').offset().top - 100
		    }, 1000);
            $(a).parent().children().first().find('i').removeClass('fa-caret-down');
            $(a).parent().children().first().find('i').addClass('fa-caret-up');
          }else{

            $(a).parent().children().first().find('i').addClass('fa-caret-down');
            $(a).parent().children().first().find('i').removeClass('fa-caret-up');
          }
      });

	});

</script>
<?php
}
?>
