<?php
	/**
		* Copyright © Magento, Inc. All rights reserved.
		* See COPYING.txt for license details.
	*/
	
	// @codingStandardsIgnoreFile
	
	/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<div class="cf sidebarSearch">
	<span class="searchLable">Search an existing order</span>
    <input type="text" name="" placeholder="P.O. Number" class="searchInput">
    <div class="loginSection">
        <a data-toggle="modal" href="#">Search</a>
	</div>
</div>