<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<div class="blogAndPressRow cf post-holder-<?php echo $_post->getId() ?>">
      <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
            <div class="blogImg">
                <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
            </div>
            <?php } ?>
    <div class="blogDetails">
        <h3><?php echo $_postName; ?></h3>
        <?php if ($content = $block->getShorContent($_post)) { ?>
            <?php echo $content ?><a  href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>"><?php echo __('Read More') ?></a>
        <?php } ?>
        <span class="blogDate"><?php echo $_post->getPublishDate('F d, Y') ?></span>
     </div>

    <div class="post-footer">

    </div>

    </div>

    <div class="post-footer">

    </div>
</li>