<?php
	$tmp_orderdata = $block->getALLOrdersListDashboard();
	$InventoryData = $block->getInvData();
	$customerdata = [];
	$isAbletoSearch = $block->isValidforSearch();
	$permission =  $this->getPermissionJson();
	$CustomerPriceList = $block->getCustomerPriceListType();
	$CustomerPriceList = @$CustomerPriceList['PriceList'];

	// AB for user permisson
	$order = true;
	$invoice = true;
	$create_order = true;
	if($permission){

	    $order = false;
	    $invoice = false;
	    $create_order = false;
	    $permissionarray = json_decode($permission, true);
	    foreach ($permissionarray as $value) { 
	        foreach ($value as $upermission) { 
	            if($upermission === 'place_oder'){
	                $create_order = true;
	            }
	            if($upermission === 'view_order'){
	                $order = true;
	            }
	            if($upermission === 'view_invoice' || $upermission === 'pay_invoice'){
	                $invoice = true;
	            }
	        } 
	    }  
?>
	<script>
	     window.permissionjson = <?php  echo \Zend_Json::encode($permission); ?>;
	     window.permission = true
	</script>
<?php }else{?>
	<script>
	     window.permissionjson = <?php  echo \Zend_Json::encode($permission); ?>;
	     window.permission = false
	</script>
<?php }?>
<script type="text/x-magento-init">
{
    "*": {
        "Sttl_Customerorder/js/render_dashboard": {        	
            "baseurl": "<?=$this->getBaseUrl();?>",
            "isAbletoSearch": "<?=$isAbletoSearch;?>",
            "customerPriceList": "<?=$CustomerPriceList;?>"
        }
    }
}</script>
<input type="hidden" name="" id="isAbletoSearch" value="<?=$isAbletoSearch;?>">
<div class="dashboardmain row" data-role="dashboard_collection">
	<div class="left-side col-3">
		<div class="row">
			<div class="announcements col-12">
				<?php echo $this->getChildHtml('notes_section');?>
			</div>
		</div>
		<div class="row">
			<div class="col-12">
				<div class="accountinfo">
					<div class="accountinfo-title">
						<h2>Account Info</h2>
					</div>
					<div class="accountinfo-content">
						<div class="spend-amount">
							<p><span class="anount-con">Year to Date Spend</span><span class="amount custom_loader" render_yeartodate_spent='0'></span></p>
							<p><span class="anount-con">Last Full Year Spend</span><span class="amount LastYearSale custom_loader" render_lastyear_spent='0'></span></p>
						</div>
						<div class="discount-pro">
							<h6>DISCOUNT PROGRAM/TIER</h6>
						</div>
						<div class="acc-content discount_section_content backLoader">
					        <span class="dis-label"></span>	
							<span class="flate-dis-info"></span>
						    <span class="dis-message-info-first"></span>
						    <span class="dis-message-info-second"></span>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-12">
				<div class="catalogs">
					<div class="accountinfo-title">
						<h2>Catalogs</h2>
					</div>
					<div class="catalogslider-div catalog-slider-loader">
						<span class="cs-slider-img"></span>
						<span class="cs-slider-label"></span>
					</div>
				</div>	
			</div>
		</div>
	</div>
	<div class="righ-side col-9">
		<div class="row"> 
			<div class="main-slider col-12" >
				<div class="myAccountCustomBanner"  style="width: 100%; height:auto;" >
					<?php echo $this->getChildHtml('banner_slider_block');?>
				</div>
			</div>
		</div>
		<div class="row statusdetail" >
			<div class="col-6 recent-order-col-section">
				<div class="recent-order order">
					<div class="new-div recentorderdiv">
						<span class="statustitle">Recent Order Status</span>
						<div class="container-fluid">
							<div class="row recent_order_status">
								<div class="col-xl-6 col-lg-12 p_i_number">
									<div class="searchInput">
										<input type="text" class="order_search" name="po_number" placeholder="P.O. or Order Number" autocomplete="off" data-validate="{required:true}">
										<span class="errormessage"></span>
									</div>
								</div>
								<div class="col-xl-4 col-lg-12 recentorderdropdown">
									<div class="statusDropdown">
										<!-- <span>Status:</span> -->
										<div class="orderDevelop"><div>Recent Orders</div>
										<div style=""><span id="lodingshippdata" class="loadShipping" style="/* display: block; */">
												<span class="loadDots">
													<span></span>
													<span></span>
													<span></span>
													<span class="tooltip-element" tooltip="' + values.description + '"></span>
												</span>
													</span>
										</div>	
									</div>

										<select name="order_stats" id="order_stats" class="filter_loading" style="display: none;">
											<option value="recent_order" selected="selected">Recent Orders</option>
											<option value="viewall">View All</option>
											<option value="Draft">Draft</option>
											<option value="Submitted">Submitted</option>
											<option value="Processing">Processing</option>
											<option value="Shipped">Shipped</option>
											<option value="PartiallyShipped">Partially Shipped</option>
										</select>
									</div>

								</div>
								<div class="col-xl-1 col-lg-12 neworderlink">
									<?php
									$neworderlinkurl = $this->getBaseUrl().'customerorder/customer/neworder';
									?>
									<a href="<?=$neworderlinkurl?>">+</a>
								</div>
							</div>
						</div>
				</div>
				<div class="orderItem-loader" style="display: none;">
		            <div class="cf loaderAdd">
						<div class="lds-ellipsis" style="display: block;">
							<h1>Loading</h1>
							<div></div>
							<div></div>
							<div></div>
							<div></div>
							<div></div>
							<div></div>
						</div>
					</div>
		        </div>
				<div class="ord_table">
					<?php
					if($order){
					if(count($tmp_orderdata) > 0  )
					{
					?>
						<table class="order_table">
							<tbody>
								<?php 
									$main_tr = '';
									$max_value = count($tmp_orderdata);
									if($max_value >= 4){
										$max_value = 4;
									}
									for ($i=0; $i < $max_value; $i++) { 
										$id_b_e = base64_encode($tmp_orderdata[$i]['Id']);
										if($tmp_orderdata[$i]['dataFrom'] == 'V')
										{
											$id_b_e = base64_encode($tmp_orderdata[$i]['DocNum']);
										}
										$order_date = '';
										if($tmp_orderdata[$i]['CreateDate'] != ''){
											$order_date = str_replace('-', '/', $tmp_orderdata[$i]['CreateDate']);
										}
										$order_redirect_url = $this->getBaseUrl().'customerorder/customer/orderview/id/'.$id_b_e.'/df/'.base64_encode($tmp_orderdata[$i]['dataFrom']);
										$main_tr .= '<tr mysql_order_id='.$tmp_orderdata[$i]['Id'].'>';
										if($tmp_orderdata[$i]['NumatCardPo'] != '' || $tmp_orderdata[$i]['NumatCardPo'] != null){

											$ponum = $tmp_orderdata[$i]['NumatCardPo'];
											if(strlen($ponum) > 8){
											
												$ponum = substr($ponum,0,8)."...";
											}

											$main_tr .= '<td><a class="order-redirect-url" data-toggle="tooltip" data-placement="right" title="'.$tmp_orderdata[$i]['NumatCardPo'].'" href='.$order_redirect_url.'>PO# '.$ponum.'</a></td>';
										}
										else
										{
											$ponum = $tmp_orderdata[$i]['DocNum'];
											if(strlen($ponum) > 8){
												$ponum = substr($ponum,0,8)."...";
											}
											$main_tr .= '<td><a class="order-redirect-url" data-toggle="tooltip" data-placement="right" title="'.$tmp_orderdata[$i]['DocNum'].'" href='.$order_redirect_url.'>Order# '. $ponum.'</a></td>';

										}
										$main_tr .= '<td>$'.number_format($tmp_orderdata[$i]['DocTotal'],2).'</td>';
										$main_tr .= '<td>'.$order_date.'</td>';
										
										if($tmp_orderdata[$i]['DocStatus'] == 'Shipped' || $tmp_orderdata[$i]['DocStatus'] == 'PartiallyShipped'){
											
											$tmp_partialy = ($tmp_orderdata[$i]['DocStatus'] == 'PartiallyShipped') ? 'Partially Shipped' : $tmp_orderdata[$i]['DocStatus'];

											$main_tr .= '<td class="'.$tmp_orderdata[$i]['DocStatus'].' custom_loading"><a href="#" data-backdrop="false" data-toggle="modal" data-target="#shipment-track" id="shipttreckdata" class="tracking_disabled" data-num="'.$tmp_orderdata[$i]['DocEntry'].'">'.$tmp_partialy.'</a></td>';
										}else{

											if($tmp_orderdata[$i]['DocStatus'] == 'Draft')
											{
												$main_tr .= '<td class='.$tmp_orderdata[$i]['DocStatus'].'><a href="'.$this->getBaseUrl().'customerorder/customer/neworder/id/'. base64_encode( $tmp_orderdata[$i]['Id']).'/ncp/'.base64_encode($tmp_orderdata[$i]['NumatCardPo']).'#block-title"> <i class="fa fa-pencil editdraftdashboard" orderid ="'.base64_encode( $tmp_orderdata[$i]['Id']).'" po_number="'.base64_encode($tmp_orderdata[$i]['NumatCardPo']).'" ></i></a><span> '.$tmp_orderdata[$i]['DocStatus'].'</span></td>';
											}
											else
											{
												$main_tr .= '<td class='.$tmp_orderdata[$i]['DocStatus'].'>'.$tmp_orderdata[$i]['DocStatus'].'</td>';
											}
										}

										$main_tr .= '</tr>';
									}
									echo $main_tr;
								?>

							</tbody>
						</table>
						<?php
							}
							else
							{
								$baseurlneworder= $this->getBaseUrl().'customerorder/customer/neworder';
									?>
										<div class="emptyrecentorder">
											
												<p>You don't yet have any orders yet!</br>Start your first order now!</p>
												<div class="neworderrecentorder"><a href="<?=$baseurlneworder?>">Place New Order</a></div>

										</div>
								<?php
							}
						}else{?>
							<div class="emptyrecentorder">
								<h1>Access Denied</h1>
								<p>You Don't have to permission to access</p>
							</div>
						<?php } ?>
					</div>
					<div class="order-link"> <span><a href="#">View All Orders</a></span></div>
				</div>
			</div>
			<div class="col-6 recent-imv-col-section">
				<div class="recent-order inv">
					<div class="new-div">
						<span class="statustitle">Inventory Status</span>
						<div class="container-fluid">
							<div class="row">
								<div class="col-md-4">
									<div class="searchInput">
										<input type="text" autocomplete="off" class="inv_search" id="style_number_search" name="style_number" placeholder="Style Number" data-validate="{required:true}">
									</div>
								</div>
								<div class="col-md-4">
									<div class="searchInput">
										<input type="text" autocomplete="off" name="style_color" id="inv_search_color" class="inv_search" placeholder="Color" >
										<ul class="autosearchcolor" style="display: none;">
											
										</ul>
									</div>
								</div>
								<div class="col-md-4">
									<button type="submit" class="themeBtn action save" style="width: 100%;" title="Search"><span>Search</span></button>	
								</div>
							</div>
						</div>
				</div>
				<div class="tooltip11">
				</div>
				<div class="inv_table">
				<table class="inventory_table">
					<tbody>
						<?php 
							$main_inv_tr = '';
							foreach ($InventoryData as $key => $value) {
								// echo "<pre>";
									// print_r(str_replace('-', '/', $value["ETA1"]));
								$eta_date = array(
									"ETA1" => array(
										"Date" => date("m/d/Y", strtotime($value["ETA1"])), 
										"Qty" => $value["EtaQty1"],
										"compare" => date("Y-m-d", strtotime($value["ETA1"])),
									), 
									"ETA2" => array(
										"Date" => date("m/d/Y", strtotime($value["ETA2"])), 
										"Qty" => $value["EtaQty2"],
										"compare" => date("Y-m-d", strtotime($value["ETA2"])),
									), 
									"ETA3" => array(
										"Date" => date("m/d/Y", strtotime($value["ETA3"])), 
										"Qty" => $value["EtaQty3"],
										"compare" => date("Y-m-d", strtotime($value["ETA3"])),
									));

								$currentdate = date('m/d/Y', strtotime('-7 days'));



								$main_inv_tr .= '<tr>';
								$main_inv_tr .= '<td>'.$value['Style'].'-'.$value['ColorCode'].'-'.$value['Size'].'</td>';
								$main_inv_tr .= '<td>$'.$value['UnitPrice'].'</td>';
								$current_avail_items = (Int) $value['ActualQty'];
								if($value['ActualQty'] >= 500){
									$current_avail_items = '500+';
								}
								$main_inv_tr .= '<td><b>'.$current_avail_items.'</b></td>';


								$tooltipbyphp = '';


								if (!empty($eta_date)) {
	                                $count = 1;
	                                $tag_count = 0;
	                                $eta_count_top = 0;
	                                $eta_class = "eta-tooltip";
	                                $eta_avail_to_show = true;

	                                    foreach ($eta_date as $key => $date_eta) {

	                                        if (strtotime($date_eta['compare']) > strtotime($currentdate) && !empty($date_eta["compare"]) && $date_eta['Qty'] > 0) {

	                                            $eta_qty_show = $eta_date[$key]["Qty"];
	                                            if ($eta_qty_show > 500) {
	                                                $eta_qty_show = "500+";
	                                            }


	                                            if(($currentdate < $eta_date[$key]["compare"]) && ($eta_date[$key]["compare"] < date('Y-m-d'))){
	                                                
	                                                $tooltipbyphp .= "<span class='eta-date'>";

	                                                $tooltipbyphp .= "<p class='eta-date-list'>";

	                                                $tooltipbyphp .= "<span class='back_date_tooltip'>Receiving Delay: The receiving of this date is delayed with few days due to port congestion.</span>";

	                                                $tooltipbyphp .= "<svg version='1.1' id='Layer_1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px' viewBox='0 0 286.054 286.054' style='enable-background:new 0 0 286.054 286.054;' xml:space='preserve'>
	                                                        <g>
	                                                            <path style='fill:#a70417;' d='M143.027,0C64.04,0,0,64.04,0,143.027c0,78.996,64.04,143.027,143.027,143.027
	                                                                c78.996,0,143.027-64.022,143.027-143.027C286.054,64.04,222.022,0,143.027,0z M143.027,259.236
	                                                                c-64.183,0-116.209-52.026-116.209-116.209S78.844,26.818,143.027,26.818s116.209,52.026,116.209,116.209
	                                                                S207.21,259.236,143.027,259.236z M143.036,62.726c-10.244,0-17.995,5.346-17.995,13.981v79.201c0,8.644,7.75,13.972,17.995,13.972
	                                                                c9.994,0,17.995-5.551,17.995-13.972V76.707C161.03,68.277,153.03,62.726,143.036,62.726z M143.036,187.723
	                                                                c-9.842,0-17.852,8.01-17.852,17.86c0,9.833,8.01,17.843,17.852,17.843s17.843-8.01,17.843-17.843
	                                                                C160.878,195.732,152.878,187.723,143.036,187.723z'/>
	                                                        </g>
	                                                        </svg>
	                                                        ";
	                                                $tooltipbyphp .= "<span>".$eta_date[$key]['Date']."</span>";
	                                                // $tooltipbyphp .= "</p>";
	                                                $tooltipbyphp .= $eta_qty_show."</p></span>";
	                                            }else{
	                                                $tooltipbyphp .= "<span class='eta-date'>";
	                                            	$tooltipbyphp .= "<p class='eta-date-list'>".$eta_date[$key]["Date"].' - '."<span class='eta_dash_qty'>".$eta_qty_show."</p>";
	                                                $tooltipbyphp .= "</span>";
	                                            	
	                                            }
	                                            
	                                            $count++;
	                                        }
	                                    }
	                                    // $tooltipbyphp.= '</td>';
	                                }


								$main_inv_tr .= '<td class="inventory_table_ETA hover-info" eta_js_tool = "'.$tooltipbyphp.'">ETA '.date("m/d/y", strtotime($value["ETA1"])).'</td>';
								$main_inv_tr .= '</tr>';
							}

							echo $main_inv_tr;
						?>
					</tbody>
				</table>
				</div>
			</div>
			</div>	
		</div>
		<div class="row outstandingdiv">
			<div class="main-slider col-12">
				<div class="top-section-outstanding-invoice">
					<div class="container-fluid">
						<div class="row outstanding_main render_invoice_header_page">
							<div class="titleoutstanding col-md-6">
								<span style="font-size: 30px;">Outstanding Invoice and Balance</span>
							</div>
						</div>
					</div>
				</div>
				
					<?php if($invoice){?>
				<div class="bottom-section-outstanding-invoice invoiceLoader">
					<span class="invoice-item-loading"></span>
					<span class="invoice-item-loading"></span>
					<span class="invoice-item-loading"></span>
					<span class="invoice-item-loading"></span>
					<span class="invoice-item-loading"></span>
				</div>
				<div class="invoice-link"> <span><a href="#">View All Invoices</a></span></div>
			        <?}else{?>
			        	<div class="bottom-section-outstanding-invoice">
			        		<div class="emptyrecentorder">
			        			<div class="permissiondened">
									<h1>Access Denied</h1>
									<p>You Don't have to permission to access</p>
			        			</div>
							</div>
						</div>
			        <?}?>
			</div>
		</div>
		<div class="row featured-row">
			<div class="col-12 featured">
				<div class="featured-pro row">
					<h2 class="col-md-9">Browse Product</h2>
					<div class="searchstyledata col-md-3" style="display: none;">
			        	<input type="text" name="searchstyle" id="searchstyle" placeholder="Search Style">
			      	</div>
				</div>
				<?php echo $this->getChildHtml('collection_slider');?>
			</div>
		</div>
	</div>
</div>
<?php echo $this->getLayout()->createBlock("Sttl\Adaruniforms\Block\View")->setTemplate("Magento_Catalog::product/ViewStockpopup.phtml")->toHtml();?>
<div id="fquickview">
	
</div>
<?php echo $this->getLayout()->createBlock("Sttl\Customerorder\Block\Orderview")->setTemplate("Sttl_Customerorder::shiptrack.phtml")->toHtml();?>

<script type="text/javascript">

require([ 'jquery' , 'functions'], function($){
	// $('.editdraftdashboard').click

	$(document).on("mouseover","td.inventory_table_ETA",function() {
        var content = $(this).attr("eta_js_tool");
        $(".tooltip11").html(content)
        var position = $(this).position()
        var left = $(".new-div").width()-70+"px"
        if($(window).width() > 1500)
	    {
	    	left =  $(".new-div").width()-100+"px"

	    }else if($(window).width() > 768){
	    	left =  $(".new-div").width()-110+"px"
	    }
        $(".tooltip11").css({
            "display":"block",
            "top": position.top -  $(".tooltip11").height()+"px",
            "left": left
        })
    });
    $(document).on("mouseout","td.inventory_table_ETA",function() {
        var position = $(this).position()
        $(".tooltip11").css({
            "display":"none"
        })
    });
    
    var trigger_click_temp_data = 0,
	marketing_timeout = "";
	$(document).on('click',".myAccountCustomBanner .magestore-bannerslider-standard .flexslider .slides a", function(e){
	  if($(this).attr('target') == "_self"){
	  	trigger_click_temp_data = 1;
	    $(".myAccountCustomBanner .magestore-bannerslider-standard .flexslider .slides").find('a').addClass('action-disabled');
	  }
	  if(marketing_timeout === "" && trigger_click_temp_data){
			marketing_timeout = setTimeout(function() {
			    trigger_click_temp_data = 0;
			    marketing_timeout = "";
			    $(".myAccountCustomBanner .magestore-bannerslider-standard .flexslider .slides").find('a').removeClass('action-disabled');
			}, 2000);
	  }
	})
    // Render a Customer Info for the Dashboard START

    $( document ).ready(function() {
		  console.log("sduihf")
	});
    // Render a Customer Info for the Dashboard END
            


});</script>
